// Generated by `wit-bindgen` 0.30.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace AggWorldWorld.wit.exports.local.agg
{
    public static class OpsInterop {

        [UnmanagedCallersOnly(EntryPoint = "local:agg/ops#make-list")]
        public static unsafe nint wasmExportMakeList() {

            uint[] ret;
            ret = OpsImpl.MakeList();

            var ptr = InteropReturnArea.returnArea.AddressOfReturnArea();

            byte[] buffer = new byte[(4) * ret.Length];
            Buffer.BlockCopy(ret.ToArray(), 0, buffer, 0, (4) * ret.Length);
            var gcHandle = GCHandle.Alloc(buffer, GCHandleType.Pinned);
            var address = gcHandle.AddrOfPinnedObject();
            BitConverter.TryWriteBytes(new Span<byte>((void*)(ptr + 4), 4), unchecked((int)ret.Length));
            BitConverter.TryWriteBytes(new Span<byte>((void*)(ptr + 0), 4), unchecked((int)((IntPtr)(address)).ToInt32()));
            return ptr;

        }

        [UnmanagedCallersOnly(EntryPoint = "cabi_post_local:agg/ops#make-list")]
        public static void cabi_post_wasmExportMakeList(nint returnValue) {
            Console.WriteLine("TODO: cabi_post_local:agg/ops#make-list");
        }

        [UnmanagedCallersOnly(EntryPoint = "local:agg/ops#take-list")]
        public static unsafe int wasmExportTakeList(nint p0, int p1) {

            var array = new uint[p1];
            new Span<uint>((void*)(p0), p1).CopyTo(new Span<uint>(array));
            uint ret;
            ret = OpsImpl.TakeList((array));
            return unchecked((int)(ret));

        }

        [UnmanagedCallersOnly(EntryPoint = "cabi_post_local:agg/ops#take-list")]
        public static void cabi_post_wasmExportTakeList(int returnValue) {
            Console.WriteLine("TODO: cabi_post_local:agg/ops#take-list");
        }

        [UnmanagedCallersOnly(EntryPoint = "local:agg/ops#make-opt")]
        public static unsafe nint wasmExportMakeOpt() {

            uint? ret;
            ret = OpsImpl.MakeOpt();

            var ptr = InteropReturnArea.returnArea.AddressOfReturnArea();

            if (ret != null) {
                var payload2 = (uint) ret;
                *(byte*)(ptr + 0) = (byte)1;
                BitConverter.TryWriteBytes(new Span<byte>((void*)(ptr + 4), 4), unchecked((int)unchecked((int)(payload2))));

            } else {

                *(byte*)(ptr + 0) = (byte)0;

            }
            return ptr;

        }

        [UnmanagedCallersOnly(EntryPoint = "cabi_post_local:agg/ops#make-opt")]
        public static void cabi_post_wasmExportMakeOpt(nint returnValue) {
            Console.WriteLine("TODO: cabi_post_local:agg/ops#make-opt");
        }

        [UnmanagedCallersOnly(EntryPoint = "local:agg/ops#take-opt")]
        public static unsafe int wasmExportTakeOpt(int p0, int p1) {

            uint? lifted;

            switch (p0) {
                case 0: {
                    lifted = null;
                    break;
                }

                case 1: {

                    lifted = unchecked((uint)(p1));
                    break;
                }

                default: throw new ArgumentException("invalid discriminant: " + (p0));
            }
            uint ret;
            ret = OpsImpl.TakeOpt((lifted));
            return unchecked((int)(ret));

        }

        [UnmanagedCallersOnly(EntryPoint = "cabi_post_local:agg/ops#take-opt")]
        public static void cabi_post_wasmExportTakeOpt(int returnValue) {
            Console.WriteLine("TODO: cabi_post_local:agg/ops#take-opt");
        }

        [UnmanagedCallersOnly(EntryPoint = "local:agg/ops#make-result")]
        public static unsafe nint wasmExportMakeResult() {

            Result<uint, string> ret;
            try {
                ret = Result<uint, string>.ok(OpsImpl.MakeResult());
            } catch (WitException e) {
                switch (e.NestingLevel) {
                    case 0: {
                        ret = Result<uint, string>.err((string) e.Value);
                        break;
                    }

                    default: throw new ArgumentException($"invalid nesting level: {e.NestingLevel}");
                }
            }

            var ptr = InteropReturnArea.returnArea.AddressOfReturnArea();

            switch (ret.Tag) {
                case 0: {
                    uint payload = ret.AsOk;
                    *(byte*)(ptr + 0) = (byte)0;
                    BitConverter.TryWriteBytes(new Span<byte>((void*)(ptr + 4), 4), unchecked((int)unchecked((int)(payload))));

                    break;
                }
                case 1: {
                    string payload2 = ret.AsErr;
                    *(byte*)(ptr + 0) = (byte)1;

                    var result = payload2;
                    IntPtr interopString = InteropString.FromString(result, out int lengthresult);
                    BitConverter.TryWriteBytes(new Span<byte>((void*)(ptr + 8), 4), unchecked((int)lengthresult));
                    BitConverter.TryWriteBytes(new Span<byte>((void*)(ptr + 4), 4), unchecked((int)interopString.ToInt32()));

                    break;
                }

                default: throw new ArgumentException($"invalid discriminant: {ret}");
            }
            return ptr;

        }

        [UnmanagedCallersOnly(EntryPoint = "cabi_post_local:agg/ops#make-result")]
        public static void cabi_post_wasmExportMakeResult(nint returnValue) {
            Console.WriteLine("TODO: cabi_post_local:agg/ops#make-result");
        }

        [UnmanagedCallersOnly(EntryPoint = "local:agg/ops#take-result")]
        public static unsafe int wasmExportTakeResult(int p0, nint p1, int p2) {

            Result<uint, string> lifted;

            switch (p0) {
                case 0: {

                    lifted = Result<uint, string>.ok(unchecked((uint)(p1)));
                    break;
                }
                case 1: {

                    lifted = Result<uint, string>.err(Encoding.UTF8.GetString((byte*)p1, p2));
                    break;
                }

                default: throw new ArgumentException($"invalid discriminant: {p0}");
            }
            uint ret;
            ret = OpsImpl.TakeResult((lifted));
            return unchecked((int)(ret));

        }

        [UnmanagedCallersOnly(EntryPoint = "cabi_post_local:agg/ops#take-result")]
        public static void cabi_post_wasmExportTakeResult(int returnValue) {
            Console.WriteLine("TODO: cabi_post_local:agg/ops#take-result");
        }

        [UnmanagedCallersOnly(EntryPoint = "local:agg/ops#make-tuple")]
        public static unsafe nint wasmExportMakeTuple() {

            (uint, string) ret;
            ret = OpsImpl.MakeTuple();

            var ptr = InteropReturnArea.returnArea.AddressOfReturnArea();
            BitConverter.TryWriteBytes(new Span<byte>((void*)(ptr + 0), 4), unchecked((int)unchecked((int)(ret.Item1))));

            var result = ret.Item2;
            IntPtr interopString = InteropString.FromString(result, out int lengthresult);
            BitConverter.TryWriteBytes(new Span<byte>((void*)(ptr + 8), 4), unchecked((int)lengthresult));
            BitConverter.TryWriteBytes(new Span<byte>((void*)(ptr + 4), 4), unchecked((int)interopString.ToInt32()));
            return ptr;

        }

        [UnmanagedCallersOnly(EntryPoint = "cabi_post_local:agg/ops#make-tuple")]
        public static void cabi_post_wasmExportMakeTuple(nint returnValue) {
            Console.WriteLine("TODO: cabi_post_local:agg/ops#make-tuple");
        }

        [UnmanagedCallersOnly(EntryPoint = "local:agg/ops#make-string")]
        public static unsafe nint wasmExportMakeString() {

            string ret;
            ret = OpsImpl.MakeString();

            var ptr = InteropReturnArea.returnArea.AddressOfReturnArea();

            var result = ret;
            IntPtr interopString = InteropString.FromString(result, out int lengthresult);
            BitConverter.TryWriteBytes(new Span<byte>((void*)(ptr + 4), 4), unchecked((int)lengthresult));
            BitConverter.TryWriteBytes(new Span<byte>((void*)(ptr + 0), 4), unchecked((int)interopString.ToInt32()));
            return ptr;

        }

        [UnmanagedCallersOnly(EntryPoint = "cabi_post_local:agg/ops#make-string")]
        public static void cabi_post_wasmExportMakeString(nint returnValue) {
            Console.WriteLine("TODO: cabi_post_local:agg/ops#make-string");
        }

        [UnmanagedCallersOnly(EntryPoint = "local:agg/ops#take-string")]
        public static unsafe int wasmExportTakeString(nint p0, int p1) {

            uint ret;
            ret = OpsImpl.TakeString((Encoding.UTF8.GetString((byte*)p0, p1)));
            return unchecked((int)(ret));

        }

        [UnmanagedCallersOnly(EntryPoint = "cabi_post_local:agg/ops#take-string")]
        public static void cabi_post_wasmExportTakeString(int returnValue) {
            Console.WriteLine("TODO: cabi_post_local:agg/ops#take-string");
        }

    }
}
