// Generated by `wit-bindgen` 0.30.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace AggWorldWorld.wit.exports.local.agg;

public interface IOps {
    static abstract uint[] MakeList();

    static abstract uint TakeList(uint[] xs);

    static abstract uint? MakeOpt();

    static abstract uint TakeOpt(uint? x);

    static abstract uint MakeResult();

    static abstract uint TakeResult(Result<uint, string> r);

    static abstract (uint, string) MakeTuple();

    static abstract string MakeString();

    static abstract uint TakeString(string s);

}
