// Generated by `wit-bindgen` 0.30.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace ResWorldWorld.wit.imports.local.res;

public interface IEnv {

    public class Clock: IDisposable {
        internal int Handle { get; set; }

        public readonly record struct THandle(int Handle);

        public Clock(THandle handle) {
            Handle = handle.Handle;
        }

        public void Dispose() {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        [DllImport("local:res/env", EntryPoint = "[resource-drop]clock"), WasmImportLinkage]
        private static extern void wasmImportResourceDrop(int p0);

        protected virtual void Dispose(bool disposing) {
            if (Handle != 0) {
                wasmImportResourceDrop(Handle);
                Handle = 0;
            }
        }

        ~Clock() {
            Dispose(false);
        }

        internal static class TickWasmInterop
        {
            [DllImport("local:res/env", EntryPoint = "[method]clock.tick"), WasmImportLinkage]
            internal static extern long wasmImportTick(int p0);

        }

        public   unsafe ulong Tick()
        {
            var handle = this.Handle;
            var result =  TickWasmInterop.wasmImportTick(handle);
            return unchecked((ulong)(result));

            //TODO: free alloc handle (interopString) if exists
        }

        internal static class SetOffsetWasmInterop
        {
            [DllImport("local:res/env", EntryPoint = "[method]clock.set-offset"), WasmImportLinkage]
            internal static extern void wasmImportSetOffset(int p0, int p1);

        }

        public   unsafe void SetOffset(int offset)
        {
            var handle = this.Handle;
            SetOffsetWasmInterop.wasmImportSetOffset(handle, offset);

            //TODO: free alloc handle (interopString) if exists
        }

        internal static class IsRunningWasmInterop
        {
            [DllImport("local:res/env", EntryPoint = "[method]clock.is-running"), WasmImportLinkage]
            internal static extern int wasmImportIsRunning(int p0);

        }

        public   unsafe bool IsRunning()
        {
            var handle = this.Handle;
            var result =  IsRunningWasmInterop.wasmImportIsRunning(handle);
            return (result != 0);

            //TODO: free alloc handle (interopString) if exists
        }

    }

}
