#!/usr/bin/env bash
# fetch-openvino-native.sh — download Intel's official OpenVINO
# native runtime and drop the dylibs/.so/.dll into the host's
# native-runtime probe path so the WACS.WASI.NN.OpenVino backend
# can find them at `Core` init time.
#
# Why this exists: the NuGet `OpenVINO.runtime.<rid>` wrapper
# packages (which carry the platform natives the C# API binds
# against) are stuck at OpenVINO 2024.4.0.1 for every RID
# except `win`. The wrapper-shipped runtime can only read IR
# generated by OpenVINO 2024.4 or earlier — guests handing in
# IR exported by `pip install openvino==2025.x` (or 2026.x)
# trip "Incorrect weights in bin file!" at `Core.read_model`.
# This script bridges the gap by pulling Intel's official
# release directly and staging it at the location the C#
# wrapper's P/Invoke layer dlopens against.
#
# Usage:
#   ./fetch-openvino-native.sh [-v <version>] [-r <rid>] [-d <dest>]
#
# Defaults:
#   -v 2025.4.1      OpenVINO release to fetch. 2024.x reads only
#                    2024.x IR (i.e. you're already covered by the
#                    NuGet runtime); 2025.x reads 2024.x + 2025.x;
#                    2026.x reads 2024.x + 2025.x + 2026.x.
#                    Pick the lowest version that covers your
#                    IR-export side.
#   -r osx-arm64     Currently the only supported RID. macOS x64
#                    + Linux + Windows users typically have a
#                    workable NuGet runtime already — open an
#                    issue if you need this script extended.
#   -d <wacs-runtimes>  Destination directory. Defaults to the
#                    `runtimes/osx-arm64/native/` subdir of the
#                    `wacs` install location resolved via
#                    `dotnet tool list -g`.
#
# Exit codes:
#   0 — success
#   1 — usage error / unknown flag
#   2 — unsupported RID
#   3 — download or extract failure
#   4 — destination not writable / could not auto-detect

set -euo pipefail

VERSION="2025.4.1"
RID="osx-arm64"
DEST=""

usage() {
    sed -n '2,/^$/p' "$0" | sed 's/^# \?//'
    exit "${1:-1}"
}

while (( $# )); do
    case "$1" in
        -v|--version) VERSION="$2"; shift 2 ;;
        -r|--rid)     RID="$2"; shift 2 ;;
        -d|--dest)    DEST="$2"; shift 2 ;;
        -h|--help)    usage 0 ;;
        *) echo "error: unknown flag '$1'" >&2; usage 1 ;;
    esac
done

# Build the Intel asset URL for the requested (version, RID) pair.
# Known patterns (verified against
# `https://storage.openvinotoolkit.org/repositories/openvino/packages/`):
#   macOS arm64:  openvino_toolkit_macos_12_6_<full-version>_arm64.tgz
# The `full-version` carries a build suffix per release. We probe
# the directory listing to resolve the exact filename rather than
# hardcoding suffixes that change per release.
case "$RID" in
    osx-arm64)
        SUBDIR="macos"
        # Anchor on `_arm64.tgz$` so we don't accidentally pick the
        # `.tgz.sha256` companion that lives next to the asset in
        # the same directory listing.
        PATTERN="openvino_toolkit_macos_12_6_${VERSION}.*_arm64\.tgz\$"
        ;;
    *)
        echo "error: RID '$RID' not yet supported by this script. "        \
             "Open an issue at https://github.com/kelnishi/WACS/issues "   \
             "with your platform target." >&2
        exit 2
        ;;
esac

BASE="https://storage.openvinotoolkit.org/repositories/openvino/packages/${VERSION}/${SUBDIR}/"
echo "==> resolving asset filename for OpenVINO ${VERSION} (${RID})..."
ASSET=$(curl -sL "${BASE}" 2>/dev/null \
    | grep -oE "openvino_toolkit_[a-zA-Z0-9_.-]+_arm64\.tgz" \
    | grep -E "${PATTERN}" \
    | head -1) || true

# Intel's listing pages render via JS — the raw HTML doesn't
# include the asset names directly. Fall back to the filetree JSON.
if [[ -z "${ASSET:-}" ]]; then
    echo "==> directory index didn't surface the asset; using filetree.json"
    ASSET=$(curl -sL "https://storage.openvinotoolkit.org/filetree.json" \
        | python3 -c "
import json, sys, re
d = json.load(sys.stdin)
pattern = re.compile(r'${PATTERN}')
def walk(n, path):
    p = path + '/' + n['name'] if path else n['name']
    if n['type'] == 'file' and pattern.search(n['name']) and '/${VERSION}/' in p:
        print(n['name'])
    for c in n.get('children', []):
        walk(c, p)
walk(d, '')
" | head -1) || true
fi

if [[ -z "${ASSET:-}" ]]; then
    echo "error: could not resolve asset URL for OpenVINO ${VERSION} ${RID}" >&2
    echo "       check that the version exists at ${BASE}" >&2
    exit 3
fi

URL="${BASE}${ASSET}"
echo "==> downloading ${URL}"
TMP=$(mktemp -d -t wacs-openvino.XXXXXX)
trap 'rm -rf "$TMP"' EXIT
curl -fL --progress-bar -o "${TMP}/asset.tgz" "${URL}" || {
    echo "error: download failed" >&2
    exit 3
}

echo "==> extracting"
tar -xzf "${TMP}/asset.tgz" -C "${TMP}"
ROOT=$(find "${TMP}" -maxdepth 1 -type d -name "openvino_toolkit*" | head -1)
if [[ -z "${ROOT}" ]]; then
    echo "error: extracted tarball has unexpected layout" >&2
    exit 3
fi

# Resolve the destination. Per-platform conventions:
#   .NET CLI tools store global tools under
#   `$DOTNET_TOOLS_PATH/.store/<id>/<version>/<id>/<version>/tools/net*/any/`
#   — the runtime/native/ subtree lives there. Easiest path is to
#   find the wacs binary on PATH, then walk up to the tools dir
#   that contains a `runtimes/${RID}/native/` subdir.
if [[ -z "${DEST}" ]]; then
    WACS_BIN=$(command -v wacs || true)
    if [[ -z "${WACS_BIN}" ]]; then
        echo "error: --dest not specified and 'wacs' not on PATH." >&2
        echo "       install via 'dotnet tool install -g WACS.Cli' or "  \
             "pass --dest explicitly." >&2
        exit 4
    fi
    WACS_REAL=$(readlink -f "${WACS_BIN}" 2>/dev/null || \
                python3 -c "import os; print(os.path.realpath('${WACS_BIN}'))")
    WACS_DIR=$(dirname "${WACS_REAL}")
    # Look for an existing runtimes/<rid>/native/ subtree; if
    # present we land alongside the ORT natives that are already
    # bundled there.
    for try in "${WACS_DIR}/runtimes/${RID}/native" \
               "${WACS_DIR}/../../tools/net8.0/any/runtimes/${RID}/native" \
               "${WACS_DIR}/../../tools/net9.0/any/runtimes/${RID}/native"
    do
        if [[ -d "${try}" ]]; then
            DEST=$(cd "${try}" && pwd)
            break
        fi
    done
    if [[ -z "${DEST}" ]]; then
        echo "error: could not auto-detect a runtimes/${RID}/native/ " \
             "subdir near ${WACS_BIN}." >&2
        echo "       pass --dest explicitly." >&2
        exit 4
    fi
fi

echo "==> staging dylibs into ${DEST}"
mkdir -p "${DEST}"
cp -P "${ROOT}/runtime/lib/arm64/Release/"*.dylib "${DEST}/"
cp -P "${ROOT}/runtime/3rdparty/tbb/lib/"*.dylib "${DEST}/"

echo "==> done. OpenVINO ${VERSION} runtime installed."
echo "    Sanity check:"
echo "      ls ${DEST}/libopenvino*.dylib"
ls "${DEST}/libopenvino"*.dylib | head -5
