// Generated by `wit-bindgen` 0.30.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace Res2WorldWorld.wit.imports.local.res2;

public interface IEnv {

    public class Counter: IDisposable {
        internal int Handle { get; set; }

        public readonly record struct THandle(int Handle);

        public Counter(THandle handle) {
            Handle = handle.Handle;
        }

        public void Dispose() {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        [DllImport("local:res2/env", EntryPoint = "[resource-drop]counter"), WasmImportLinkage]
        private static extern void wasmImportResourceDrop(int p0);

        protected virtual void Dispose(bool disposing) {
            if (Handle != 0) {
                wasmImportResourceDrop(Handle);
                Handle = 0;
            }
        }

        ~Counter() {
            Dispose(false);
        }

        internal static class ConstructorWasmInterop
        {
            [DllImport("local:res2/env", EntryPoint = "[constructor]counter"), WasmImportLinkage]
            internal static extern int wasmImportConstructor(int p0);

        }

        public   unsafe  Counter(uint initial)
        {
            var result =  ConstructorWasmInterop.wasmImportConstructor(unchecked((int)(initial)));
            this.Handle = result;

            //TODO: free alloc handle (interopString) if exists
        }

        internal static class FromBytesWasmInterop
        {
            [DllImport("local:res2/env", EntryPoint = "[static]counter.from-bytes"), WasmImportLinkage]
            internal static extern int wasmImportFromBytes(int p0);

        }

        public  static unsafe global::Res2WorldWorld.wit.imports.local.res2.IEnv.Counter FromBytes(uint data)
        {
            var result =  FromBytesWasmInterop.wasmImportFromBytes(unchecked((int)(data)));
            var resource = new global::Res2WorldWorld.wit.imports.local.res2.IEnv.Counter(new global::Res2WorldWorld.wit.imports.local.res2.IEnv.Counter.THandle(result));
            return resource;

            //TODO: free alloc handle (interopString) if exists
        }

        internal static class GetWasmInterop
        {
            [DllImport("local:res2/env", EntryPoint = "[method]counter.get"), WasmImportLinkage]
            internal static extern int wasmImportGet(int p0);

        }

        public   unsafe uint Get()
        {
            var handle = this.Handle;
            var result =  GetWasmInterop.wasmImportGet(handle);
            return unchecked((uint)(result));

            //TODO: free alloc handle (interopString) if exists
        }

        internal static class IncrementWasmInterop
        {
            [DllImport("local:res2/env", EntryPoint = "[method]counter.increment"), WasmImportLinkage]
            internal static extern void wasmImportIncrement(int p0);

        }

        public   unsafe void Increment()
        {
            var handle = this.Handle;
            IncrementWasmInterop.wasmImportIncrement(handle);

            //TODO: free alloc handle (interopString) if exists
        }

    }

}
