// Generated by `wit-bindgen` 0.30.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace HelloWorld.wit.imports.wasi.cli.v0_2_3
{
    public static class StdoutInterop {

        internal static class GetStdoutWasmInterop
        {
            [DllImport("wasi:cli/stdout@0.2.3", EntryPoint = "get-stdout"), WasmImportLinkage]
            internal static extern int wasmImportGetStdout();

        }

        public  static unsafe global::HelloWorld.wit.imports.wasi.io.v0_2_3.IStreams.OutputStream GetStdout()
        {
            var result =  GetStdoutWasmInterop.wasmImportGetStdout();
            var resource = new global::HelloWorld.wit.imports.wasi.io.v0_2_3.IStreams.OutputStream(new global::HelloWorld.wit.imports.wasi.io.v0_2_3.IStreams.OutputStream.THandle(result));
            return resource;

            //TODO: free alloc handle (interopString) if exists
        }

    }
}
