// Generated by `wit-bindgen` 0.30.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace HelloWorld.wit.exports.wasi.cli.v0_2_3
{
    public static class RunInterop {

        [UnmanagedCallersOnly(EntryPoint = "wasi:cli/run@0.2.3#run")]
        public static unsafe int wasmExportRun() {

            Result<None, None> ret;
            try {
                RunImpl.Run();
                ret = Result<None, None>.ok(new None());
            } catch (WitException e) {
                switch (e.NestingLevel) {
                    case 0: {
                        ret = Result<None, None>.err((None) e.Value);
                        break;
                    }

                    default: throw new ArgumentException($"invalid nesting level: {e.NestingLevel}");
                }
            }

            int lowered;

            switch (ret.Tag) {
                case 0: {

                    lowered = 0;

                    break;
                }
                case 1: {

                    lowered = 1;

                    break;
                }

                default: throw new ArgumentException($"invalid discriminant: {ret}");
            }
            return lowered;

        }

        [UnmanagedCallersOnly(EntryPoint = "cabi_post_wasi:cli/run@0.2.3#run")]
        public static void cabi_post_wasmExportRun(int returnValue) {
            Console.WriteLine("TODO: cabi_post_wasi:cli/run@0.2.3#run");
        }

    }
}
