// Generated by `wit-bindgen` 0.30.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace PvWorldWorld.wit.imports.local.pv
{
    public static class EnvInterop {

        internal static class SendWasmInterop
        {
            [DllImport("local:pv/env", EntryPoint = "send"), WasmImportLinkage]
            internal static extern void wasmImportSend(int p0, int p1);

        }

        public  static unsafe void Send(global::PvWorldWorld.wit.imports.local.pv.IEnv.Msg m)
        {

            int lowered;
            int lowered6;

            switch (m.Tag) {
                case 0: {
                    uint payload = m.AsInfo;

                    lowered = 0;
                    lowered6 = unchecked((int)(payload));

                    break;
                }
                case 1: {

                    lowered = 1;
                    lowered6 = 0;

                    break;
                }
                case 2: {
                    uint payload5 = m.AsError;

                    lowered = 2;
                    lowered6 = unchecked((int)(payload5));

                    break;
                }

                default: throw new ArgumentException($"invalid discriminant: {m}");
            }
            SendWasmInterop.wasmImportSend(lowered, lowered6);

            //TODO: free alloc handle (interopString) if exists
        }

        internal static class FetchWasmInterop
        {
            [DllImport("local:pv/env", EntryPoint = "fetch"), WasmImportLinkage]
            internal static extern void wasmImportFetch(nint p0);

        }

        public  static unsafe global::PvWorldWorld.wit.imports.local.pv.IEnv.Msg Fetch()
        {

            var retArea = new uint[2];
            fixed (uint* retAreaByte0 = &retArea[0])
            {
                var ptr = (nint)retAreaByte0;
                FetchWasmInterop.wasmImportFetch(ptr);

                global::PvWorldWorld.wit.imports.local.pv.IEnv.Msg lifted;

                switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                    case 0: {

                        lifted = global::PvWorldWorld.wit.imports.local.pv.IEnv.Msg.info(unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4)))));
                        break;
                    }
                    case 1: {

                        lifted = global::PvWorldWorld.wit.imports.local.pv.IEnv.Msg.warning();
                        break;
                    }
                    case 2: {

                        lifted = global::PvWorldWorld.wit.imports.local.pv.IEnv.Msg.error(unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4)))));
                        break;
                    }

                    default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
                }
                return lifted;
            }

            //TODO: free alloc handle (interopString) if exists
        }

        internal static class TryOpWasmInterop
        {
            [DllImport("local:pv/env", EntryPoint = "try-op"), WasmImportLinkage]
            internal static extern void wasmImportTryOp(int p0, nint p1);

        }

        public  static unsafe uint TryOp(uint x)
        {

            var retArea = new uint[3];
            fixed (uint* retAreaByte0 = &retArea[0])
            {
                var ptr = (nint)retAreaByte0;
                TryOpWasmInterop.wasmImportTryOp(unchecked((int)(x)), ptr);

                Result<uint, global::PvWorldWorld.wit.imports.local.pv.IEnv.Msg> lifted8;

                switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                    case 0: {

                        lifted8 = Result<uint, global::PvWorldWorld.wit.imports.local.pv.IEnv.Msg>.ok(unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4)))));
                        break;
                    }
                    case 1: {

                        global::PvWorldWorld.wit.imports.local.pv.IEnv.Msg lifted;

                        switch (new Span<byte>((void*)(ptr + 4), 1)[0]) {
                            case 0: {

                                lifted = global::PvWorldWorld.wit.imports.local.pv.IEnv.Msg.info(unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4)))));
                                break;
                            }
                            case 1: {

                                lifted = global::PvWorldWorld.wit.imports.local.pv.IEnv.Msg.warning();
                                break;
                            }
                            case 2: {

                                lifted = global::PvWorldWorld.wit.imports.local.pv.IEnv.Msg.error(unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4)))));
                                break;
                            }

                            default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 4), 1)[0]}");
                        }

                        lifted8 = Result<uint, global::PvWorldWorld.wit.imports.local.pv.IEnv.Msg>.err(lifted);
                        break;
                    }

                    default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
                }
                if (lifted8.IsOk) {
                    var tmp = lifted8.AsOk;
                    return tmp;
                } else {
                    throw new WitException(lifted8.AsErr!, 0);
                }
            }

            //TODO: free alloc handle (interopString) if exists
        }

    }
}
