// Generated by `wit-bindgen` 0.30.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace Bor2WorldWorld.wit.imports.local.bor2
{
    public static class EnvInterop {

        internal static class ScanWasmInterop
        {
            [DllImport("local:bor2/env", EntryPoint = "scan"), WasmImportLinkage]
            internal static extern int wasmImportScan(int p0, int p1);

        }

        public  static unsafe uint Scan(global::Bor2WorldWorld.wit.imports.local.bor2.IEnv.Alpha a, global::Bor2WorldWorld.wit.imports.local.bor2.IEnv.Alpha b)
        {
            var handle = a.Handle;
            var handle0 = b.Handle;
            var result =  ScanWasmInterop.wasmImportScan(handle, handle0);
            return unchecked((uint)(result));

            //TODO: free alloc handle (interopString) if exists
        }

    }
}
