// Generated by `wit-bindgen` 0.30.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace Bor2WorldWorld.wit.imports.local.bor2;

public interface IEnv {

    public class Alpha: IDisposable {
        internal int Handle { get; set; }

        public readonly record struct THandle(int Handle);

        public Alpha(THandle handle) {
            Handle = handle.Handle;
        }

        public void Dispose() {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        [DllImport("local:bor2/env", EntryPoint = "[resource-drop]alpha"), WasmImportLinkage]
        private static extern void wasmImportResourceDrop(int p0);

        protected virtual void Dispose(bool disposing) {
            if (Handle != 0) {
                wasmImportResourceDrop(Handle);
                Handle = 0;
            }
        }

        ~Alpha() {
            Dispose(false);
        }

        internal static class ConstructorWasmInterop
        {
            [DllImport("local:bor2/env", EntryPoint = "[constructor]alpha"), WasmImportLinkage]
            internal static extern int wasmImportConstructor();

        }

        public   unsafe  Alpha()
        {
            var result =  ConstructorWasmInterop.wasmImportConstructor();
            this.Handle = result;

            //TODO: free alloc handle (interopString) if exists
        }

        internal static class PokeWasmInterop
        {
            [DllImport("local:bor2/env", EntryPoint = "[method]alpha.poke"), WasmImportLinkage]
            internal static extern int wasmImportPoke(int p0, int p1);

        }

        public   unsafe uint Poke(global::Bor2WorldWorld.wit.imports.local.bor2.IEnv.Alpha other)
        {
            var handle = this.Handle;
            var handle0 = other.Handle;
            var result =  PokeWasmInterop.wasmImportPoke(handle, handle0);
            return unchecked((uint)(result));

            //TODO: free alloc handle (interopString) if exists
        }

    }

}
