// Copyright 2026 Kelvin Nishikawa
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
//
//     http://www.apache.org/licenses/LICENSE-2.0

using System;
using System.Collections.Generic;
using System.Text;
using Wacs.ComponentModel.Types;

namespace Wacs.ComponentModel.CSharpEmit
{
    /// <summary>
    /// Emits <b>host-side</b> C# interfaces from a WIT model. The
    /// output is a set of <c>public interface IXxx { ... }</c>
    /// declarations a runtime binding implements — distinct from
    /// the consumer-side <see cref="CSharpEmitter"/> output which
    /// produces DllImport-stub instantiation classes for guest
    /// components.
    ///
    /// <para>One <see cref="EmittedSource"/> per WIT interface,
    /// plus one per top-level type declaration that needs its
    /// own file. Each generated symbol carries a
    /// <see cref="Wacs.ComponentModel.Runtime.WitSourceAttribute"/>
    /// with the verbatim WIT-text fragment for runtime
    /// validation.</para>
    ///
    /// <para>Faithful type mapping (per the project's
    /// "Faithful" rule):
    /// <list type="bullet">
    /// <item><c>option&lt;T&gt;</c> → <c>Option&lt;T&gt;</c> (not <c>T?</c>)</item>
    /// <item><c>result&lt;T, E&gt;</c> → <c>Result&lt;T, E&gt;</c> (in both param and return)</item>
    /// <item><c>list&lt;u8&gt;</c> → <c>byte[]</c>; <c>list&lt;T&gt;</c> → <c>T[]</c></item>
    /// <item><c>tuple&lt;a, b&gt;</c> → <c>(A, B)</c></item>
    /// <item><c>own&lt;X&gt;</c> / <c>borrow&lt;X&gt;</c> → <c>IX</c></item>
    /// </list></para>
    /// </summary>
    public static class HostInterfaceEmit
    {
        /// <summary>
        /// Emit one or more interface files for each interface in
        /// the supplied package. Cross-package references are
        /// resolved against <paramref name="allPackages"/> so
        /// <c>use</c> chains can be followed for namespace-qualified
        /// type names.
        /// </summary>
        public static IReadOnlyList<EmittedSource> EmitPackage(
            CtPackage package, IReadOnlyList<CtPackage> allPackages,
            EmitOptions? options = null)
        {
            options ??= new EmitOptions();
            var sources = new List<EmittedSource>();
            foreach (var iface in package.Interfaces)
                sources.Add(EmitInterfaceFile(iface, package, options));
            return sources;
        }

        /// <summary>Emit the single interface file for one
        /// <see cref="CtInterfaceType"/>. Captures all of:
        /// type declarations, resource interfaces, and the
        /// free-function interface.</summary>
        public static EmittedSource EmitInterfaceFile(
            CtInterfaceType iface, CtPackage owningPackage,
            EmitOptions options)
        {
            // Push ambient state so EmitTypeRefInner can detect
            // same-vs-cross-interface refs and route to the
            // qualified-name path for the latter.
            using var _ = EmitAmbient.Push(
                worldNs: "",   // unused in host mode
                iface: iface, options: options,
                alwaysQualifyTypeRefs: false);

            var ns = ResolveNamespace(iface, options);
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Source WIT: " + iface.QualifiedName);
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using Wacs.ComponentModel.Runtime;");
            sb.AppendLine();
            sb.Append("namespace ").Append(ns).AppendLine();
            sb.AppendLine("{");

            // Top-level type declarations (records, variants,
            // enums, flags). Aliases skipped — they inline at use.
            foreach (var t in iface.Types)
            {
                if (t.Type is CtRecordType rec)
                    EmitRecord(sb, rec, t, indent: "    ");
                else if (t.Type is CtVariantType var)
                    EmitVariant(sb, var, t, indent: "    ");
                else if (t.Type is CtEnumType en)
                    EmitEnum(sb, en, t, indent: "    ");
                else if (t.Type is CtFlagsType flg)
                    EmitFlags(sb, flg, t, indent: "    ");
                else if (t.Type is CtResourceType res)
                    EmitResourceInterface(sb, res, t, iface, indent: "    ");
                // Type aliases (CtTypeRef body) are inlined at
                // each use site by EmitTypeRef — no emission here.
            }

            // Free-function interface (only when the WIT
            // interface declares any). Always emit a marker
            // interface so the binding always has something to
            // implement, even for type-only WIT interfaces — that
            // makes the validation layer's job uniform.
            EmitFreeFunctionInterface(sb, iface, indent: "    ");

            sb.AppendLine("}");

            // Filename qualifies by namespace so collisions across
            // packages (e.g. wasi:filesystem/types vs wasi:http/types)
            // don't shadow each other in Roslyn's hint-name space.
            var fileName = ns.Replace('.', '_') + "_"
                + ToPascal(iface.Name) + ".g.cs";
            return new EmittedSource(fileName, sb.ToString());
        }

        // ---------- type declarations ------------------------------

        private static void EmitRecord(StringBuilder sb,
            CtRecordType rec, CtNamedType named, string indent)
        {
            EmitWitSourceAttr(sb, indent, BuildRecordWit(rec, named));
            sb.Append(indent).Append("public sealed class ")
                .Append(ToPascal(rec.Name)).AppendLine();
            sb.Append(indent).AppendLine("{");
            foreach (var f in rec.Fields)
            {
                sb.Append(indent).Append("    public ")
                    .Append(EmitTypeRef(f.Type)).Append(' ')
                    .Append(ToPascal(f.Name))
                    .AppendLine(" { get; set; } = default!;");
            }
            sb.Append(indent).AppendLine("}");
            sb.AppendLine();
        }

        private static void EmitVariant(StringBuilder sb,
            CtVariantType var, CtNamedType named, string indent)
        {
            EmitWitSourceAttr(sb, indent, BuildVariantWit(var, named));
            sb.Append(indent).Append("public abstract class ")
                .Append(ToPascal(var.Name)).AppendLine();
            sb.Append(indent).AppendLine("{");
            foreach (var c in var.Cases)
            {
                var caseName = ToPascal(var.Name)
                    + ToPascal(c.Name);
                sb.Append(indent).Append("    public sealed class ")
                    .Append(caseName).Append(" : ")
                    .Append(ToPascal(var.Name)).AppendLine();
                sb.Append(indent).AppendLine("    {");
                if (c.Payload != null)
                {
                    sb.Append(indent).Append("        public ")
                        .Append(EmitTypeRef(c.Payload))
                        .AppendLine(" Value { get; }");
                    sb.Append(indent).Append("        public ")
                        .Append(caseName).Append('(')
                        .Append(EmitTypeRef(c.Payload))
                        .AppendLine(" value) { Value = value; }");
                }
                sb.Append(indent).AppendLine("    }");
            }
            sb.Append(indent).AppendLine("}");
            sb.AppendLine();
        }

        private static void EmitEnum(StringBuilder sb,
            CtEnumType en, CtNamedType named, string indent)
        {
            EmitWitSourceAttr(sb, indent, BuildEnumWit(en, named));
            sb.Append(indent).Append("public enum ")
                .Append(ToPascal(en.Name)).AppendLine();
            sb.Append(indent).AppendLine("{");
            for (int i = 0; i < en.Cases.Count; i++)
            {
                sb.Append(indent).Append("    ")
                    .Append(ToPascal(en.Cases[i]))
                    .Append(" = ").Append(i)
                    .AppendLine(",");
            }
            sb.Append(indent).AppendLine("}");
            sb.AppendLine();
        }

        private static void EmitFlags(StringBuilder sb,
            CtFlagsType flg, CtNamedType named, string indent)
        {
            EmitWitSourceAttr(sb, indent, BuildFlagsWit(flg, named));
            sb.Append(indent).AppendLine("[Flags]");
            sb.Append(indent).Append("public enum ")
                .Append(ToPascal(flg.Name)).AppendLine(" : uint");
            sb.Append(indent).AppendLine("{");
            sb.Append(indent).AppendLine("    None = 0,");
            for (int i = 0; i < flg.Flags.Count; i++)
            {
                sb.Append(indent).Append("    ")
                    .Append(ToPascal(flg.Flags[i]))
                    .Append(" = 1u << ").Append(i)
                    .AppendLine(",");
            }
            sb.Append(indent).AppendLine("}");
            sb.AppendLine();
        }

        // ---------- resource interface -----------------------------

        private static void EmitResourceInterface(StringBuilder sb,
            CtResourceType res, CtNamedType named,
            CtInterfaceType iface, string indent)
        {
            var ifaceName = "I" + ToPascal(res.Name);
            EmitWitSourceAttr(sb, indent, BuildResourceWit(res, named),
                pkg: iface.Package?.ToString(),
                @interface: iface.Name, item: res.Name);
            sb.Append(indent).Append("public interface ")
                .Append(ifaceName).AppendLine();
            sb.Append(indent).AppendLine("{");
            foreach (var m in res.Methods)
                EmitResourceMethod(sb, m, res, iface,
                    indent: indent + "    ");
            sb.Append(indent).AppendLine("}");
            sb.AppendLine();
        }

        private static void EmitResourceMethod(StringBuilder sb,
            CtResourceMethod m, CtResourceType res,
            CtInterfaceType iface, string indent)
        {
            var fn = m.Function;
            var name = m.Name ?? "";
            var pascalName = m.Kind == CtResourceMethodKind.Constructor
                ? "Create"
                : ToPascal(name);

            EmitWitSourceAttr(sb, indent,
                BuildResourceMethodWit(m, res),
                pkg: iface.Package?.ToString(),
                @interface: iface.Name,
                item: res.Name + "."
                    + (m.Kind == CtResourceMethodKind.Constructor
                        ? "constructor" : name));

            // WIT `static func` lowers to a C# `static` default
            // interface method. The transpiler-direct-link path
            // routes [static]X.foo via this method's IsStatic
            // classification — without the `static` modifier the
            // resolver categorizes it as [method]X.foo and the
            // wasm import goes unbound. The body delegates to a
            // discovered impl class's `{Name}Static` factory
            // (Wacs.WASI.GFX.DependencyInjection.Buffer.
            // FromGraphicsBufferStatic-shaped) via the
            // ComponentModel runtime helper, mirroring how
            // Wacs.WASI.Preview2's Fields.FromListStatic
            // pattern is invoked.
            if (m.Kind == CtResourceMethodKind.Static)
            {
                var returnType = EmitReturnType(fn);
                bool isVoid = returnType == "void";
                var ifaceQualified = "global::" + ResolveNamespace(iface,
                        EmitAmbient.Options ?? new EmitOptions())
                    + ".I" + ToPascal(res.Name);
                sb.Append(indent).Append("static ")
                    .Append(returnType)
                    .Append(' ').Append(pascalName).Append('(');
                EmitParamList(sb, fn);
                sb.AppendLine(")");
                sb.Append(indent).AppendLine("{");

                // Build the args array — wraps each lifted param
                // for the reflective Invoke call.
                sb.Append(indent).Append("    var __args = new object?[] { ");
                bool firstArg = true;
                foreach (var p in fn.Params)
                {
                    if (!firstArg) sb.Append(", ");
                    sb.Append(ToCamel(p.Name));
                    firstArg = false;
                }
                sb.AppendLine(" };");

                if (isVoid)
                {
                    sb.Append(indent).Append("    ")
                        .Append("global::Wacs.ComponentModel.Runtime.HostInterfaceRuntime")
                        .Append(".InvokeStaticFactoryReflective(typeof(")
                        .Append(ifaceQualified).Append("), \"")
                        .Append(pascalName).AppendLine("Static\", __args);");
                }
                else
                {
                    sb.Append(indent).Append("    var __result = ")
                        .Append("global::Wacs.ComponentModel.Runtime.HostInterfaceRuntime")
                        .Append(".InvokeStaticFactoryReflective(typeof(")
                        .Append(ifaceQualified).Append("), \"")
                        .Append(pascalName).AppendLine("Static\", __args);");
                    sb.Append(indent).Append("    return (")
                        .Append(returnType).AppendLine(")__result!;");
                }
                sb.Append(indent).AppendLine("}");
                return;
            }

            sb.Append(indent)
                .Append(EmitReturnType(fn))
                .Append(' ').Append(pascalName).Append('(');
            EmitParamList(sb, fn);
            sb.AppendLine(");");
        }

        // ---------- free-function interface ------------------------

        private static void EmitFreeFunctionInterface(StringBuilder sb,
            CtInterfaceType iface, string indent)
        {
            if (iface.Functions.Count == 0)
                return;
            // Detect a name collision with a same-named resource
            // (common in WITs like `interface network { resource
            // network; ... }`). When colliding, suffix the
            // free-function interface to avoid duplicate `INetwork`
            // emissions in one namespace.
            bool collidesWithResource = false;
            foreach (var t in iface.Types)
            {
                if (t.Type is CtResourceType
                    && string.Equals(t.Name, iface.Name,
                        System.StringComparison.OrdinalIgnoreCase))
                {
                    collidesWithResource = true;
                    break;
                }
            }
            var suffix = collidesWithResource ? "Funcs" : "";

            EmitWitSourceAttr(sb, indent,
                BuildInterfaceWitHeader(iface),
                pkg: iface.Package?.ToString(),
                @interface: iface.Name);
            sb.Append(indent).Append("public interface I")
                .Append(ToPascal(iface.Name)).Append(suffix)
                .AppendLine();
            sb.Append(indent).AppendLine("{");
            foreach (var f in iface.Functions)
                EmitFreeFunction(sb, f, iface, indent + "    ");
            sb.Append(indent).AppendLine("}");
            sb.AppendLine();
        }

        private static void EmitFreeFunction(StringBuilder sb,
            CtInterfaceFunction f, CtInterfaceType iface,
            string indent)
        {
            EmitWitSourceAttr(sb, indent,
                BuildFreeFunctionWit(f),
                pkg: iface.Package?.ToString(),
                @interface: iface.Name, item: f.Name);
            sb.Append(indent)
                .Append(EmitReturnType(f.Type))
                .Append(' ').Append(ToPascal(f.Name)).Append('(');
            EmitParamList(sb, f.Type);
            sb.AppendLine(");");
        }

        private static void EmitParamList(StringBuilder sb,
            CtFunctionType fn)
        {
            for (int i = 0; i < fn.Params.Count; i++)
            {
                if (i > 0) sb.Append(", ");
                var p = fn.Params[i];
                sb.Append(EmitTypeRef(p.Type)).Append(' ')
                    .Append(ToCamel(p.Name));
            }
        }

        // ---------- type-ref translation (faithful) ---------------

        /// <summary>Faithful host-mode type ref: result/option do
        /// not unwrap, list/tuple/own/borrow follow canon shapes.
        /// Cross-interface refs emit fully-qualified names through
        /// <see cref="ResolveCrossInterfaceQualifiedName"/>.</summary>
        public static string EmitTypeRef(CtValType type)
        {
            return type switch
            {
                CtPrimType p => EmitPrim(p.Kind),
                CtListType { Element: CtPrimType ep } when ep.Kind == CtPrim.U8
                    => "byte[]",
                CtListType l => EmitTypeRef(l.Element) + "[]",
                CtOptionType o => "Option<" + EmitTypeRef(o.Inner) + ">",
                CtResultType r => EmitResult(r),
                CtTupleType t => EmitTuple(t),
                CtOwnType o => EmitResourceRef(o.Resource),
                CtBorrowType b => EmitResourceRef(b.Resource),
                CtTypeRef r => EmitTypeRefInner(r),
                _ => throw new NotSupportedException(
                    "Host-mode emission for "
                    + type.GetType().Name + " is unsupported."),
            };
        }

        private static string EmitReturnType(CtFunctionType fn)
        {
            if (fn.HasNoResult) return "void";
            if (fn.NamedResults != null && fn.NamedResults.Count > 0)
            {
                var nr = fn.NamedResults;
                if (nr.Count == 1)
                    return EmitTypeRef(nr[0].Type);
                var sb = new StringBuilder("(");
                for (int i = 0; i < nr.Count; i++)
                {
                    if (i > 0) sb.Append(", ");
                    sb.Append(EmitTypeRef(nr[i].Type)).Append(' ')
                        .Append(ToCamel(nr[i].Name));
                }
                sb.Append(')');
                return sb.ToString();
            }
            return EmitTypeRef(fn.Result!);
        }

        private static string EmitResult(CtResultType r)
        {
            // result<_, _> → Result<Unit, Unit>
            // result<T, _> → Result<T, Unit>
            // result<_, E> → Result<Unit, E>
            // result<T, E> → Result<T, E>
            var ok = r.Ok != null ? EmitTypeRef(r.Ok) : "Unit";
            var err = r.Err != null ? EmitTypeRef(r.Err) : "Unit";
            return "Result<" + ok + ", " + err + ">";
        }

        private static string EmitTuple(CtTupleType t)
        {
            var sb = new StringBuilder("(");
            for (int i = 0; i < t.Elements.Count; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append(EmitTypeRef(t.Elements[i]));
            }
            sb.Append(')');
            return sb.ToString();
        }

        private static string EmitResourceRef(CtValType inner)
        {
            if (inner is CtTypeRef r && r.Target != null)
            {
                var t = ResolveTarget(r.Target);
                if (t.Type is CtResourceType res)
                {
                    if (t.Owner != null
                        && !ReferenceEquals(t.Owner, EmitAmbient.EmittingInterface))
                    {
                        return ResolveCrossInterfaceQualifiedName(
                            t, isResource: true);
                    }
                    return "I" + ToPascal(res.Name);
                }
            }
            return EmitTypeRef(inner);
        }

        private static string EmitTypeRefInner(CtTypeRef r)
        {
            if (r.Target == null)
                return ToPascal(r.Name);

            var target = ResolveTarget(r.Target);

            // Type aliases pointing at non-declarable bodies
            // inline at use site.
            if (target.Type is not (CtRecordType or CtVariantType
                or CtEnumType or CtFlagsType or CtResourceType))
            {
                return EmitTypeRef(target.Type);
            }

            bool isResource = target.Type is CtResourceType;

            // Cross-interface? Emit fully-qualified.
            if (target.Owner != null
                && !ReferenceEquals(target.Owner,
                    EmitAmbient.EmittingInterface))
            {
                return ResolveCrossInterfaceQualifiedName(
                    target, isResource);
            }

            return (isResource ? "I" : "") + ToPascal(target.Name);
        }

        private static CtNamedType ResolveTarget(CtNamedType t)
        {
            // Follow alias chains.
            while (t.Type is CtTypeRef inner && inner.Target != null
                   && !ReferenceEquals(inner.Target, t))
            {
                t = inner.Target;
            }
            return t;
        }

        private static string ResolveCrossInterfaceQualifiedName(
            CtNamedType target, bool isResource)
        {
            var owner = target.Owner!;
            var ns = ResolveNamespace(owner,
                EmitAmbient.Options ?? new EmitOptions());
            return "global::" + ns + "."
                + (isResource ? "I" : "")
                + ToPascal(target.Name);
        }

        private static string EmitPrim(CtPrim k) => k switch
        {
            CtPrim.Bool => "bool",
            CtPrim.S8 => "sbyte",
            CtPrim.S16 => "short",
            CtPrim.S32 => "int",
            CtPrim.S64 => "long",
            CtPrim.U8 => "byte",
            CtPrim.U16 => "ushort",
            CtPrim.U32 => "uint",
            CtPrim.U64 => "ulong",
            CtPrim.F32 => "float",
            CtPrim.F64 => "double",
            CtPrim.Char => "uint",
            CtPrim.String => "string",
            _ => throw new NotSupportedException("CtPrim: " + k),
        };

        // ---------- WIT-source builders ----------------------------

        private static string BuildResourceWit(CtResourceType res,
            CtNamedType named)
        {
            var sb = new StringBuilder();
            sb.Append("resource ").Append(res.Name);
            if (res.Methods.Count == 0)
            {
                sb.Append(';');
                return sb.ToString();
            }
            sb.AppendLine(" {");
            foreach (var m in res.Methods)
            {
                sb.Append("    ");
                AppendResourceMethodWit(sb, m);
                sb.AppendLine();
            }
            sb.Append('}');
            return sb.ToString();
        }

        private static string BuildResourceMethodWit(
            CtResourceMethod m, CtResourceType res)
        {
            var sb = new StringBuilder();
            AppendResourceMethodWit(sb, m);
            return sb.ToString();
        }

        private static void AppendResourceMethodWit(StringBuilder sb,
            CtResourceMethod m)
        {
            switch (m.Kind)
            {
                case CtResourceMethodKind.Constructor:
                    sb.Append("constructor(");
                    AppendParamsWit(sb, m.Function.Params);
                    sb.Append(");");
                    return;
                case CtResourceMethodKind.Static:
                    sb.Append(m.Name).Append(": static func(");
                    AppendParamsWit(sb, m.Function.Params);
                    sb.Append(')');
                    AppendReturnWit(sb, m.Function);
                    sb.Append(';');
                    return;
                case CtResourceMethodKind.Instance:
                default:
                    sb.Append(m.Name).Append(": func(");
                    AppendParamsWit(sb, m.Function.Params);
                    sb.Append(')');
                    AppendReturnWit(sb, m.Function);
                    sb.Append(';');
                    return;
            }
        }

        private static string BuildFreeFunctionWit(
            CtInterfaceFunction f)
        {
            var sb = new StringBuilder();
            sb.Append(f.Name).Append(": func(");
            AppendParamsWit(sb, f.Type.Params);
            sb.Append(')');
            AppendReturnWit(sb, f.Type);
            sb.Append(';');
            return sb.ToString();
        }

        private static string BuildInterfaceWitHeader(
            CtInterfaceType iface)
            => "interface " + iface.Name;

        private static string BuildRecordWit(CtRecordType r,
            CtNamedType named)
        {
            var sb = new StringBuilder();
            sb.Append("record ").Append(r.Name).Append(" { ");
            for (int i = 0; i < r.Fields.Count; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append(r.Fields[i].Name).Append(": ")
                    .Append(EmitWitTypeRef(r.Fields[i].Type));
            }
            sb.Append(" }");
            return sb.ToString();
        }

        private static string BuildVariantWit(CtVariantType v,
            CtNamedType named)
        {
            var sb = new StringBuilder();
            sb.Append("variant ").Append(v.Name).Append(" { ");
            for (int i = 0; i < v.Cases.Count; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append(v.Cases[i].Name);
                if (v.Cases[i].Payload != null)
                    sb.Append('(')
                        .Append(EmitWitTypeRef(v.Cases[i].Payload!))
                        .Append(')');
            }
            sb.Append(" }");
            return sb.ToString();
        }

        private static string BuildEnumWit(CtEnumType e,
            CtNamedType named)
        {
            var sb = new StringBuilder("enum ").Append(e.Name)
                .Append(" { ");
            for (int i = 0; i < e.Cases.Count; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append(e.Cases[i]);
            }
            sb.Append(" }");
            return sb.ToString();
        }

        private static string BuildFlagsWit(CtFlagsType f,
            CtNamedType named)
        {
            var sb = new StringBuilder("flags ").Append(f.Name)
                .Append(" { ");
            for (int i = 0; i < f.Flags.Count; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append(f.Flags[i]);
            }
            sb.Append(" }");
            return sb.ToString();
        }

        private static void AppendParamsWit(StringBuilder sb,
            IReadOnlyList<CtFuncParam> ps)
        {
            for (int i = 0; i < ps.Count; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append(ps[i].Name).Append(": ")
                    .Append(EmitWitTypeRef(ps[i].Type));
            }
        }

        private static void AppendReturnWit(StringBuilder sb,
            CtFunctionType fn)
        {
            if (fn.HasNoResult) return;
            sb.Append(" -> ");
            if (fn.NamedResults != null && fn.NamedResults.Count > 0)
            {
                if (fn.NamedResults.Count == 1)
                {
                    sb.Append(EmitWitTypeRef(fn.NamedResults[0].Type));
                    return;
                }
                sb.Append('(');
                for (int i = 0; i < fn.NamedResults.Count; i++)
                {
                    if (i > 0) sb.Append(", ");
                    sb.Append(fn.NamedResults[i].Name).Append(": ")
                        .Append(EmitWitTypeRef(fn.NamedResults[i].Type));
                }
                sb.Append(')');
                return;
            }
            sb.Append(EmitWitTypeRef(fn.Result!));
        }

        private static string EmitWitTypeRef(CtValType t)
        {
            return t switch
            {
                CtPrimType p => p.Kind switch
                {
                    CtPrim.Bool => "bool",
                    CtPrim.S8 => "s8",
                    CtPrim.S16 => "s16",
                    CtPrim.S32 => "s32",
                    CtPrim.S64 => "s64",
                    CtPrim.U8 => "u8",
                    CtPrim.U16 => "u16",
                    CtPrim.U32 => "u32",
                    CtPrim.U64 => "u64",
                    CtPrim.F32 => "f32",
                    CtPrim.F64 => "f64",
                    CtPrim.Char => "char",
                    CtPrim.String => "string",
                    _ => "?",
                },
                CtListType l => "list<" + EmitWitTypeRef(l.Element) + ">",
                CtOptionType o => "option<" + EmitWitTypeRef(o.Inner) + ">",
                CtResultType r => EmitWitResult(r),
                CtTupleType tp => EmitWitTuple(tp),
                CtOwnType o => "own<" + EmitWitTypeRef(o.Resource) + ">",
                CtBorrowType b => "borrow<" + EmitWitTypeRef(b.Resource) + ">",
                CtTypeRef rf => rf.Name,
                CtResourceType res => res.Name,
                CtRecordType rc => rc.Name,
                CtVariantType vt => vt.Name,
                CtEnumType en => en.Name,
                CtFlagsType fl => fl.Name,
                _ => "?",
            };
        }

        private static string EmitWitResult(CtResultType r)
        {
            if (r.Ok == null && r.Err == null) return "result";
            if (r.Ok != null && r.Err == null)
                return "result<" + EmitWitTypeRef(r.Ok) + ">";
            if (r.Ok == null && r.Err != null)
                return "result<_, " + EmitWitTypeRef(r.Err) + ">";
            return "result<" + EmitWitTypeRef(r.Ok!)
                + ", " + EmitWitTypeRef(r.Err!) + ">";
        }

        private static string EmitWitTuple(CtTupleType t)
        {
            var sb = new StringBuilder("tuple<");
            for (int i = 0; i < t.Elements.Count; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append(EmitWitTypeRef(t.Elements[i]));
            }
            sb.Append('>');
            return sb.ToString();
        }

        // ---------- attribute emission -----------------------------

        private static void EmitWitSourceAttr(StringBuilder sb,
            string indent, string source,
            string? pkg = null, string? @interface = null,
            string? item = null)
        {
            sb.Append(indent).Append("[WitSource(")
                .Append(EscapeForCSharp(source));
            if (pkg != null)
                sb.Append(", Package = \"").Append(pkg).Append("\"");
            if (@interface != null)
                sb.Append(", Interface = \"").Append(@interface)
                    .Append("\"");
            if (item != null)
                sb.Append(", Item = \"").Append(item).Append("\"");
            sb.AppendLine(")]");
        }

        private static string EscapeForCSharp(string s)
        {
            var sb = new StringBuilder("@\"");
            foreach (var c in s)
            {
                if (c == '"') sb.Append("\"\"");
                else sb.Append(c);
            }
            sb.Append('"');
            return sb.ToString();
        }

        // ---------- namespace / naming -----------------------------

        /// <summary>Compute the C# namespace for an interface.
        /// Default convention: <c>{PkgNs}.{PkgPath}.{V_xxx}</c>
        /// — e.g. <c>wasi:cli@0.2.3</c> → <c>Wasi.Cli.V0_2_3</c>.
        /// When <see cref="EmitOptions.HostNamespaceOverride"/> is
        /// set, that string replaces the package's namespace
        /// component (the leftmost segment) so consumers can
        /// land generated code under their existing tree —
        /// <c>HostNamespaceOverride="Wacs.WASI.Preview2"</c> +
        /// <c>wasi:cli</c> → <c>Wacs.WASI.Preview2.Cli</c>.
        /// The path + version segments still follow.</summary>
        public static string ResolveNamespace(CtInterfaceType iface,
            EmitOptions options)
        {
            var pkg = iface.Package;
            if (pkg == null)
            {
                return string.IsNullOrEmpty(options.HostNamespaceOverride)
                    ? "Wasi"
                    : options.HostNamespaceOverride!;
            }

            // Per-package remap: when a referenced WIT package has
            // its canonical CLR namespace in another assembly
            // (e.g. wasi:io lives in Wacs.WASI.Preview2), use that
            // namespace rather than re-rooting under the local
            // HostNamespaceOverride. Without this, every emitter
            // would re-emit a parallel host-interface tree for
            // every cross-package reference; resource-table
            // tracking depends on identity at the CLR type level,
            // so the parallel emits would diverge and break the
            // direct-link path.
            if (options.PackageNamespaceMap != null
                && options.PackageNamespaceMap.TryGetValue(
                    pkg.Namespace + ":" + string.Join(":", pkg.Path),
                    out var remap))
            {
                var sbRemap = new StringBuilder();
                sbRemap.Append(remap);
                foreach (var seg in pkg.Path)
                    sbRemap.Append('.').Append(ToPascal(seg));
                return sbRemap.ToString();
            }

            var sb = new StringBuilder();
            sb.Append(string.IsNullOrEmpty(options.HostNamespaceOverride)
                ? ToPascal(pkg.Namespace)
                : options.HostNamespaceOverride!);
            foreach (var seg in pkg.Path)
                sb.Append('.').Append(ToPascal(seg));
            // Drop the version segment when an override is set —
            // consumers landing into their own tree already know
            // which version they're vendoring; multi-version
            // coexistence is uncommon at this layer.
            if (string.IsNullOrEmpty(options.HostNamespaceOverride)
                && !string.IsNullOrEmpty(pkg.Version))
                sb.Append('.').Append(SanitizeVersion(pkg.Version!));
            return sb.ToString();
        }

        private static string SanitizeVersion(string v)
            => "V" + v.Replace('.', '_').Replace('-', '_');

        // Local PascalCase / camelCase that handles kebab + escapes
        // C# keywords. Mirrors NameMangler but kept self-contained
        // so this file can be moved into the source-gen project
        // (which can't reference internal helpers in
        // Wacs.ComponentModel without InternalsVisibleTo).
        private static string ToPascal(string s)
        {
            // WIT identifiers may be `%`-prefixed when shadowing
            // a WIT keyword (e.g. `%type`). The prefix exists only
            // in the source text; the actual identifier is the
            // tail. Strip it before casing.
            if (s.Length > 0 && s[0] == '%') s = s.Substring(1);
            var sb = new StringBuilder();
            bool upper = true;
            foreach (var c in s)
            {
                if (c == '-' || c == '_' || c == ' ')
                {
                    upper = true;
                    continue;
                }
                if (upper)
                {
                    sb.Append(char.ToUpperInvariant(c));
                    upper = false;
                }
                else sb.Append(c);
            }
            return sb.ToString();
        }

        private static string ToCamel(string s)
        {
            if (s.Length > 0 && s[0] == '%') s = s.Substring(1);
            var p = ToPascal(s);
            if (p.Length == 0) return p;
            var c = char.ToLowerInvariant(p[0]) + p.Substring(1);
            // Escape C# keywords.
            return IsKeyword(c) ? "@" + c : c;
        }

        private static bool IsKeyword(string s)
        {
            switch (s)
            {
                case "abstract": case "as": case "base": case "bool":
                case "break": case "byte": case "case": case "catch":
                case "char": case "checked": case "class": case "const":
                case "continue": case "decimal": case "default":
                case "delegate": case "do": case "double": case "else":
                case "enum": case "event": case "explicit": case "extern":
                case "false": case "finally": case "fixed": case "float":
                case "for": case "foreach": case "goto": case "if":
                case "implicit": case "in": case "int": case "interface":
                case "internal": case "is": case "lock": case "long":
                case "namespace": case "new": case "null": case "object":
                case "operator": case "out": case "override": case "params":
                case "private": case "protected": case "public":
                case "readonly": case "ref": case "return": case "sbyte":
                case "sealed": case "short": case "sizeof": case "stackalloc":
                case "static": case "string": case "struct": case "switch":
                case "this": case "throw": case "true": case "try":
                case "typeof": case "uint": case "ulong": case "unchecked":
                case "unsafe": case "ushort": case "using": case "virtual":
                case "void": case "volatile": case "while":
                    return true;
                default: return false;
            }
        }
    }
}
