// Generated by `wit-bindgen` 0.30.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace SpWorldWorld.wit.imports.local.sp
{
    public static class EnvInterop {

        internal static class LogWasmInterop
        {
            [DllImport("local:sp/env", EntryPoint = "log"), WasmImportLinkage]
            internal static extern void wasmImportLog(nint p0, int p1);

        }

        public  static unsafe void Log(string msg)
        {

            IntPtr msgPtr = InteropString.FromString(msg, out int msgLen);
            LogWasmInterop.wasmImportLog(msgPtr.ToInt32(), msgLen);

            //TODO: free alloc handle (interopString) if exists
        }

        internal static class WriteToWasmInterop
        {
            [DllImport("local:sp/env", EntryPoint = "write-to"), WasmImportLinkage]
            internal static extern void wasmImportWriteTo(nint p0, int p1, int p2);

        }

        public  static unsafe void WriteTo(string path, uint data)
        {

            IntPtr pathPtr = InteropString.FromString(path, out int pathLen);
            WriteToWasmInterop.wasmImportWriteTo(pathPtr.ToInt32(), pathLen, unchecked((int)(data)));

            //TODO: free alloc handle (interopString) if exists
        }

    }
}
