<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <RootNamespace>WitHarnessSpike.ResultParams.Generated.Validate</RootNamespace>
        <AssemblyName>WitHarnessSpike.ResultParams.Generated.Validate</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\wasm\dispatcher.component.wasm">
            <Link>dispatcher.component.wasm</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\..\Wacs.Core\Wacs.Core\Wacs.Core.csproj" />
        <ProjectReference Include="..\..\..\..\..\Wacs.ComponentModel\Wacs.ComponentModel.Harness.Runtime\Wacs.ComponentModel.Harness.Runtime.csproj" />
        <ProjectReference Include="..\..\..\..\..\Wacs.ComponentModel\Wacs.ComponentModel.Harness.Lib\Wacs.ComponentModel.Harness.Lib.csproj" />
    </ItemGroup>

</Project>
