// Generated by `wit-bindgen` 0.30.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace O64WorldWorld.wit.imports.local.o64
{
    public static class EnvInterop {

        internal static class MaybeBigWasmInterop
        {
            [DllImport("local:o64/env", EntryPoint = "maybe-big"), WasmImportLinkage]
            internal static extern void wasmImportMaybeBig(nint p0);

        }

        public  static unsafe ulong? MaybeBig()
        {

            var retArea = new ulong[2];
            fixed (ulong* retAreaByte0 = &retArea[0])
            {
                var ptr = (nint)retAreaByte0;
                MaybeBigWasmInterop.wasmImportMaybeBig(ptr);

                ulong? lifted;

                switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                    case 0: {
                        lifted = null;
                        break;
                    }

                    case 1: {

                        lifted = unchecked((ulong)(BitConverter.ToInt64(new Span<byte>((void*)(ptr + 8), 8))));
                        break;
                    }

                    default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 0), 1)[0]));
                }
                return lifted;
            }

            //TODO: free alloc handle (interopString) if exists
        }

        internal static class TakeBigWasmInterop
        {
            [DllImport("local:o64/env", EntryPoint = "take-big"), WasmImportLinkage]
            internal static extern void wasmImportTakeBig(int p0, long p1);

        }

        public  static unsafe void TakeBig(ulong? x)
        {

            int xTag;
            long xVal;
            if (x != null) {
                xTag = 1;
                xVal = unchecked((long)((ulong)x));
            } else {
                xTag = 0;
                xVal = 0L;
            }
            TakeBigWasmInterop.wasmImportTakeBig(xTag, xVal);

            //TODO: free alloc handle (interopString) if exists
        }

        internal static class GetBothWasmInterop
        {
            [DllImport("local:o64/env", EntryPoint = "get-both"), WasmImportLinkage]
            internal static extern void wasmImportGetBoth(nint p0);

        }

        public  static unsafe ulong GetBoth()
        {

            var retArea = new ulong[2];
            fixed (ulong* retAreaByte0 = &retArea[0])
            {
                var ptr = (nint)retAreaByte0;
                GetBothWasmInterop.wasmImportGetBoth(ptr);

                Result<ulong, uint> lifted;

                switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                    case 0: {

                        lifted = Result<ulong, uint>.ok(unchecked((ulong)(BitConverter.ToInt64(new Span<byte>((void*)(ptr + 8), 8)))));
                        break;
                    }
                    case 1: {

                        lifted = Result<ulong, uint>.err(unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4)))));
                        break;
                    }

                    default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
                }
                if (lifted.IsOk) {
                    var tmp = lifted.AsOk;
                    return tmp;
                } else {
                    throw new WitException(lifted.AsErr!, 0);
                }
            }

            //TODO: free alloc handle (interopString) if exists
        }

    }
}
