// Generated by `wit-bindgen` 0.30.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace TrampWorldWorld.wit.exports.local.tramp
{
    public static class OpsInterop {

        [UnmanagedCallersOnly(EntryPoint = "local:tramp/ops#add")]
        public static unsafe int wasmExportAdd(int p0, int p1) {

            uint ret;
            ret = OpsImpl.Add((unchecked((uint)(p0))), (unchecked((uint)(p1))));
            return unchecked((int)(ret));

        }

        [UnmanagedCallersOnly(EntryPoint = "cabi_post_local:tramp/ops#add")]
        public static void cabi_post_wasmExportAdd(int returnValue) {
            Console.WriteLine("TODO: cabi_post_local:tramp/ops#add");
        }

        [UnmanagedCallersOnly(EntryPoint = "local:tramp/ops#square")]
        public static unsafe int wasmExportSquare(int p0) {

            int ret;
            ret = OpsImpl.Square((p0));
            return ret;

        }

        [UnmanagedCallersOnly(EntryPoint = "cabi_post_local:tramp/ops#square")]
        public static void cabi_post_wasmExportSquare(int returnValue) {
            Console.WriteLine("TODO: cabi_post_local:tramp/ops#square");
        }

        [UnmanagedCallersOnly(EntryPoint = "local:tramp/ops#ping")]
        public static unsafe void wasmExportPing() {

            OpsImpl.Ping();

        }

    }
}
