// Generated by `wit-bindgen` 0.30.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace Tramp2WorldWorld.wit.exports.local.tramp2
{
    public static class OpsInterop {

        [UnmanagedCallersOnly(EntryPoint = "local:tramp2/ops#take-bool")]
        public static unsafe int wasmExportTakeBool(int p0) {

            bool ret;
            ret = OpsImpl.TakeBool(((p0 != 0)));
            return (ret ? 1 : 0);

        }

        [UnmanagedCallersOnly(EntryPoint = "cabi_post_local:tramp2/ops#take-bool")]
        public static void cabi_post_wasmExportTakeBool(int returnValue) {
            Console.WriteLine("TODO: cabi_post_local:tramp2/ops#take-bool");
        }

        [UnmanagedCallersOnly(EntryPoint = "local:tramp2/ops#take-s8")]
        public static unsafe int wasmExportTakeS8(int p0) {

            sbyte ret;
            ret = OpsImpl.TakeS8((((sbyte)p0)));
            return ret;

        }

        [UnmanagedCallersOnly(EntryPoint = "cabi_post_local:tramp2/ops#take-s8")]
        public static void cabi_post_wasmExportTakeS8(int returnValue) {
            Console.WriteLine("TODO: cabi_post_local:tramp2/ops#take-s8");
        }

        [UnmanagedCallersOnly(EntryPoint = "local:tramp2/ops#take-char")]
        public static unsafe int wasmExportTakeChar(int p0) {

            uint ret;
            ret = OpsImpl.TakeChar((unchecked((uint)(p0))));
            return ((int)ret);

        }

        [UnmanagedCallersOnly(EntryPoint = "cabi_post_local:tramp2/ops#take-char")]
        public static void cabi_post_wasmExportTakeChar(int returnValue) {
            Console.WriteLine("TODO: cabi_post_local:tramp2/ops#take-char");
        }

        [UnmanagedCallersOnly(EntryPoint = "local:tramp2/ops#take-u64")]
        public static unsafe long wasmExportTakeU64(long p0) {

            ulong ret;
            ret = OpsImpl.TakeU64((unchecked((ulong)(p0))));
            return unchecked((long)(ret));

        }

        [UnmanagedCallersOnly(EntryPoint = "cabi_post_local:tramp2/ops#take-u64")]
        public static void cabi_post_wasmExportTakeU64(long returnValue) {
            Console.WriteLine("TODO: cabi_post_local:tramp2/ops#take-u64");
        }

    }
}
