// Generated by `wit-bindgen` 0.30.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace Rec2WorldWorld.wit.exports.local.rec2;

public interface IDef {

    public class WebAddress {
        public readonly string hostName;
        public readonly ushort portNumber;
        public readonly bool isSecure;

        public WebAddress(string hostName, ushort portNumber, bool isSecure) {
            this.hostName = hostName;
            this.portNumber = portNumber;
            this.isSecure = isSecure;
        }
    }
    static abstract bool Connect(WebAddress addr);

}
