// Generated by `wit-bindgen` 0.30.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace RecWorldWorld.wit.exports.local.rec;

public interface IDef {

    public class Point {
        public readonly uint x;
        public readonly uint y;

        public Point(uint x, uint y) {
            this.x = x;
            this.y = y;
        }
    }

    public class Person {
        public readonly string name;
        public readonly byte age;

        public Person(string name, byte age) {
            this.name = name;
            this.age = age;
        }
    }
    static abstract Point Origin();

    static abstract Point Translate(Point p, int dx, int dy);

}
