// Generated by `wit-bindgen` 0.30.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace VarWorldWorld.wit.exports.local.var;

public interface IDef {

    public class Shape {
        public readonly byte Tag;
        private readonly object? value;

        private Shape(byte tag, object? value) {
            this.Tag = tag;
            this.value = value;
        }

        public static Shape circle(float circle) {
            return new Shape(CIRCLE, circle);
        }

        public static Shape rectangle((float, float) rectangle) {
            return new Shape(RECTANGLE, rectangle);
        }

        public static Shape empty() {
            return new Shape(EMPTY, null);
        }

        public static Shape labeled(string labeled) {
            return new Shape(LABELED, labeled);
        }

        public float AsCircle
        {
            get
            {
                if (Tag == CIRCLE)
                return (float)value!;
                else
                throw new ArgumentException("expected CIRCLE, got " + Tag);
            }
        }

        public (float, float) AsRectangle
        {
            get
            {
                if (Tag == RECTANGLE)
                return ((float, float))value!;
                else
                throw new ArgumentException("expected RECTANGLE, got " + Tag);
            }
        }

        public string AsLabeled
        {
            get
            {
                if (Tag == LABELED)
                return (string)value!;
                else
                throw new ArgumentException("expected LABELED, got " + Tag);
            }
        }

        public const byte CIRCLE = 0;
        public const byte RECTANGLE = 1;
        public const byte EMPTY = 2;
        public const byte LABELED = 3;
    }
    static abstract void Draw(Shape s);

    static abstract Shape MakeCircle(float r);

}
