// Generated by `wit-bindgen` 0.30.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace L32WorldWorld.wit.imports.local.l32
{
    public static class EnvInterop {

        internal static class SendWasmInterop
        {
            [DllImport("local:l32/env", EntryPoint = "send"), WasmImportLinkage]
            internal static extern void wasmImportSend(nint p0, int p1);

        }

        public  static unsafe void Send(uint[] vals)
        {

            void* buffer = stackalloc uint[(vals).Length];
            vals.AsSpan<uint>().CopyTo(new Span<uint>(buffer, vals.Length));
            SendWasmInterop.wasmImportSend((int)buffer, (vals).Length);

            //TODO: free alloc handle (interopString) if exists
        }

        internal static class RecvWasmInterop
        {
            [DllImport("local:l32/env", EntryPoint = "recv"), WasmImportLinkage]
            internal static extern void wasmImportRecv(nint p0);

        }

        public  static unsafe uint[] Recv()
        {

            var retArea = new uint[2];
            fixed (uint* retAreaByte0 = &retArea[0])
            {
                var ptr = (nint)retAreaByte0;
                RecvWasmInterop.wasmImportRecv(ptr);

                var array = new uint[BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4))];
                new Span<uint>((void*)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 0), 4))), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4))).CopyTo(new Span<uint>(array));
                return array;
            }

            //TODO: free alloc handle (interopString) if exists
        }

    }
}
