// Generated by `wit-bindgen` 0.30.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace TupWorldWorld.wit.imports.local.tup
{
    public static class EnvInterop {

        internal static class SwapWasmInterop
        {
            [DllImport("local:tup/env", EntryPoint = "swap"), WasmImportLinkage]
            internal static extern void wasmImportSwap(int p0, int p1, nint p2);

        }

        public  static unsafe (int, uint) Swap((uint, int) p)
        {

            var retArea = new uint[2];
            fixed (uint* retAreaByte0 = &retArea[0])
            {
                var ptr = (nint)retAreaByte0;
                SwapWasmInterop.wasmImportSwap(unchecked((int)(p.Item1)), p.Item2, ptr);
                return (BitConverter.ToInt32(new Span<byte>((void*)(ptr + 0), 4)), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4))))
                );
            }

            //TODO: free alloc handle (interopString) if exists
        }

    }
}
