// Generated by `wit-bindgen` 0.30.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace OptWorldWorld.wit.imports.local.opt
{
    public static class EnvInterop {

        internal static class MaybeU32WasmInterop
        {
            [DllImport("local:opt/env", EntryPoint = "maybe-u32"), WasmImportLinkage]
            internal static extern void wasmImportMaybeU32(nint p0);

        }

        public  static unsafe uint? MaybeU32()
        {

            var retArea = new uint[2];
            fixed (uint* retAreaByte0 = &retArea[0])
            {
                var ptr = (nint)retAreaByte0;
                MaybeU32WasmInterop.wasmImportMaybeU32(ptr);

                uint? lifted;

                switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                    case 0: {
                        lifted = null;
                        break;
                    }

                    case 1: {

                        lifted = unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4))));
                        break;
                    }

                    default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 0), 1)[0]));
                }
                return lifted;
            }

            //TODO: free alloc handle (interopString) if exists
        }

        internal static class TakeU32WasmInterop
        {
            [DllImport("local:opt/env", EntryPoint = "take-u32"), WasmImportLinkage]
            internal static extern void wasmImportTakeU32(int p0, int p1);

        }

        public  static unsafe void TakeU32(uint? x)
        {

            int lowered;
            int lowered3;

            if (x != null) {
                var payload2 = (uint) x;

                lowered = 1;
                lowered3 = unchecked((int)(payload2));

            } else {

                lowered = 0;
                lowered3 = 0;

            }
            TakeU32WasmInterop.wasmImportTakeU32(lowered, lowered3);

            //TODO: free alloc handle (interopString) if exists
        }

    }
}
