// Generated by `wit-bindgen` 0.30.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace XvWorldWorld.wit.imports.local.xv
{
    public static class EnvInterop {

        internal static class QueryWasmInterop
        {
            [DllImport("local:xv/env", EntryPoint = "query"), WasmImportLinkage]
            internal static extern void wasmImportQuery(nint p0);

        }

        public  static unsafe global::XvWorldWorld.wit.imports.local.xv.IEnv.Status Query()
        {

            var retArea = new uint[2];
            fixed (uint* retAreaByte0 = &retArea[0])
            {
                var ptr = (nint)retAreaByte0;
                QueryWasmInterop.wasmImportQuery(ptr);

                global::XvWorldWorld.wit.imports.local.xv.IEnv.Status lifted;

                switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                    case 0: {

                        lifted = global::XvWorldWorld.wit.imports.local.xv.IEnv.Status.okMsg(unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4)))));
                        break;
                    }
                    case 1: {
                        var resource = new global::XvWorldWorld.wit.imports.local.xv.IErrs.Fail(new global::XvWorldWorld.wit.imports.local.xv.IErrs.Fail.THandle(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4))));

                        lifted = global::XvWorldWorld.wit.imports.local.xv.IEnv.Status.failed(resource);
                        break;
                    }
                    case 2: {

                        lifted = global::XvWorldWorld.wit.imports.local.xv.IEnv.Status.closed();
                        break;
                    }

                    default: throw new ArgumentException($"invalid discriminant: {new Span<byte>((void*)(ptr + 0), 1)[0]}");
                }
                return lifted;
            }

            //TODO: free alloc handle (interopString) if exists
        }

    }
}
