// Copyright 2025 Kelvin Nishikawa
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0

using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;

namespace Wacs.Transpiler.Cli
{
    /// <summary>
    /// DispatchProxy that implements a generated IImports interface by
    /// routing each import method call to a handler registered by name.
    /// Used by <see cref="WasiRunner"/> to bridge transpiled-module imports
    /// to the interpreter's bound WASI host functions.
    /// <para>
    /// Default behavior: throws <see cref="InvalidOperationException"/>
    /// on the first call to an import without a registered handler. The
    /// alternative (silently returning <c>default(ReturnType)</c>) hides
    /// configuration bugs and produces wrong-but-non-trapping wasm
    /// execution. Pass <c>lenient: true</c> to <see cref="Create"/> for
    /// the silent-default behavior — used by ComponentMainHost when
    /// every import is direct-linked and the IImports proxy exists
    /// only as a slot-filler for the Module ctor.
    /// </para>
    /// </summary>
    public class ImportDispatcher : DispatchProxy
    {
        private readonly Dictionary<string, Func<object?[], object?>> _handlers = new();
        private bool _lenient;
        private string? _interfaceName;

        public void Register(string methodName, Func<object?[], object?> handler)
        {
            _handlers[methodName] = handler;
        }

        protected override object? Invoke(MethodInfo? targetMethod, object?[]? args)
        {
            if (targetMethod == null) return null;
            if (_handlers.TryGetValue(targetMethod.Name, out var handler))
                return handler(args ?? Array.Empty<object?>());

            if (!_lenient)
            {
                throw new InvalidOperationException(
                    $"No handler registered for import method '{targetMethod.Name}' on " +
                    $"'{_interfaceName ?? targetMethod.DeclaringType?.FullName}'. " +
                    $"Register a handler via ImportDispatcher.Create's handlers " +
                    $"dictionary keyed on the import method's name (typically " +
                    $"'{{wasmModule}}_{{wasmName}}' as sanitized by InterfaceGenerator), " +
                    $"or pass lenient: true to opt into default-return behavior.");
            }

            if (targetMethod.ReturnType == typeof(void)) return null;
            if (targetMethod.ReturnType.IsValueType)
                return Activator.CreateInstance(targetMethod.ReturnType);
            return null;
        }

        /// <summary>
        /// Create a proxy implementing the given IImports interface type,
        /// backed by an ImportDispatcher with the given handlers.
        /// </summary>
        /// <param name="importsInterface">The IImports interface type the
        /// proxy should implement. Generated by
        /// <see cref="InterfaceGenerator"/> as part of every transpiled
        /// module.</param>
        /// <param name="handlers">Map from import method name (sanitized
        /// <c>{wasmModule}_{wasmName}</c> form) to a handler taking the
        /// boxed arg array and returning the boxed result.</param>
        /// <param name="lenient">When true, an unmatched method invocation
        /// returns <c>default(ReturnType)</c> instead of throwing. Use
        /// this for component-mode hosts where every import is
        /// direct-linked and the proxy exists only because the Module
        /// ctor's IImports slot must be populated. Default false —
        /// missing handlers throw <see cref="InvalidOperationException"/>
        /// with a message naming the offending import.</param>
        public static object Create(Type importsInterface,
            Dictionary<string, Func<object?[], object?>> handlers,
            bool lenient = false)
        {
            var createMethod = typeof(DispatchProxy)
                .GetMethods(BindingFlags.Public | BindingFlags.Static)
                .First(m => m.Name == "Create" && m.GetGenericArguments().Length == 2)
                .MakeGenericMethod(importsInterface, typeof(ImportDispatcher));

            var proxy = createMethod.Invoke(null, null)!;
            var dispatcher = (ImportDispatcher)proxy;
            dispatcher._lenient = lenient;
            dispatcher._interfaceName = importsInterface.FullName;
            foreach (var kv in handlers)
                dispatcher.Register(kv.Key, kv.Value);
            return proxy;
        }
    }
}
