// Generated by `wit-bindgen` 0.30.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace RsWorldWorld.wit.imports.local.rs;

public interface IEnv {

    public class Token: IDisposable {
        internal int Handle { get; set; }

        public readonly record struct THandle(int Handle);

        public Token(THandle handle) {
            Handle = handle.Handle;
        }

        public void Dispose() {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        [DllImport("local:rs/env", EntryPoint = "[resource-drop]token"), WasmImportLinkage]
        private static extern void wasmImportResourceDrop(int p0);

        protected virtual void Dispose(bool disposing) {
            if (Handle != 0) {
                wasmImportResourceDrop(Handle);
                Handle = 0;
            }
        }

        ~Token() {
            Dispose(false);
        }

        internal static class ToDebugWasmInterop
        {
            [DllImport("local:rs/env", EntryPoint = "[method]token.to-debug"), WasmImportLinkage]
            internal static extern void wasmImportToDebug(int p0, nint p1);

        }

        public   unsafe string ToDebug()
        {
            var handle = this.Handle;

            var retArea = new uint[2];
            fixed (uint* retAreaByte0 = &retArea[0])
            {
                var ptr = (nint)retAreaByte0;
                ToDebugWasmInterop.wasmImportToDebug(handle, ptr);
                return Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4)));
            }

            //TODO: free alloc handle (interopString) if exists
        }

        internal static class TagWasmInterop
        {
            [DllImport("local:rs/env", EntryPoint = "[method]token.tag"), WasmImportLinkage]
            internal static extern int wasmImportTag(int p0);

        }

        public   unsafe uint Tag()
        {
            var handle = this.Handle;
            var result =  TagWasmInterop.wasmImportTag(handle);
            return unchecked((uint)(result));

            //TODO: free alloc handle (interopString) if exists
        }

    }

}
