// Generated by `wit-bindgen` 0.30.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace OwnrWorldWorld.wit.imports.local.ownr
{
    public static class EnvInterop {

        internal static class GetWidgetWasmInterop
        {
            [DllImport("local:ownr/env", EntryPoint = "get-widget"), WasmImportLinkage]
            internal static extern int wasmImportGetWidget();

        }

        public  static unsafe global::OwnrWorldWorld.wit.imports.local.ownr.IEnv.Widget GetWidget()
        {
            var result =  GetWidgetWasmInterop.wasmImportGetWidget();
            var resource = new global::OwnrWorldWorld.wit.imports.local.ownr.IEnv.Widget(new global::OwnrWorldWorld.wit.imports.local.ownr.IEnv.Widget.THandle(result));
            return resource;

            //TODO: free alloc handle (interopString) if exists
        }

    }
}
