// Copyright 2026 Kelvin Nishikawa
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System;
using System.IO;
using System.Reflection;
using System.Reflection.Metadata;
using System.Reflection.Metadata.Ecma335;
using System.Reflection.PortableExecutable;

namespace Wacs.Transpiler.AOT
{
    /// <summary>
    /// In-place rewrite of a saved PAB-emitted .dll's AssemblyRef table to
    /// turn its `System.Private.CoreLib` reference into `System.Runtime`.
    /// Applied at <see cref="ModuleTranspiler.TranspilationResult.SaveAssembly"/>
    /// time so saved-to-disk DLLs can be referenced from a consumer csproj
    /// (notably the host project generated by `wacs aot`). The in-process
    /// Bake/Load round-trip skips this rewriter entirely — its loaded
    /// `_assembly` keeps the impl-corelib identity that PAB emits natively.
    ///
    /// ===== Why this hack exists =====
    ///
    /// PersistedAssemblyBuilder (the .NET 9+ replacement for AssemblyBuilder
    /// `Save`) stamps the saved DLL's corelib AssemblyRef using the
    /// `coreAssembly` we hand it. We pass `typeof(object).Assembly`, which
    /// the runtime reports as `System.Private.CoreLib` (the implementation
    /// assembly that holds Object, String, Int32, generic List, etc.).
    /// That's the runtime-impl identity, not the contract identity
    /// (`System.Runtime`) that the C# compiler sees when it consumes the
    /// .NET ref pack. Result: a consumer csproj that statically references
    /// our saved .dll trips CS0012 at compile time:
    ///
    ///   error CS0012: The type 'Object' is defined in an assembly that is
    ///   not referenced. You must add a reference to assembly
    ///   'System.Private.CoreLib, Version=9.0.0.0, ...'
    ///
    /// The official fix (https://github.com/dotnet/runtime/issues/103357)
    /// is to give PAB a MetadataLoadContext-loaded `System.Runtime` from
    /// the ref pack instead of `typeof(object).Assembly`. Saved DLLs then
    /// stamp `System.Runtime` (which IS in every consumer's ref pack), and
    /// CS0012 goes away. But there's a catch: per the official PAB docs,
    /// "you should use types returned by the MetadataLoadContext instance
    /// when referencing core types. For example, instead of typeof(int),
    /// find the System.Int32 type in MetadataLoadContext.CoreAssembly by
    /// name". Our IL emit uses impl `typeof(...)` everywhere — every
    /// generic-instantiation, every parameter encoding, every member ref.
    /// Mixing impl types with an MLC corelib produces saved DLLs whose
    /// memberrefs cannot be runtime-bound (e.g. MissingMethodException for
    /// `InitializeFromEmbedded(ReadOnlySpan&lt;byte&gt;, int)` because PAB
    /// encoded the parameter via the impl type's `System.Private.CoreLib`
    /// identity and the AssemblyRef row says `System.Runtime`). Migrating
    /// the entire IL-emit pipeline to MLC-bound types is a large refactor
    /// touching dozens of files. We don't do it here.
    ///
    /// Instead, we keep PAB on `typeof(object).Assembly` and post-process
    /// the saved bytes at SaveAssembly time, swapping the AssemblyRef row's
    /// name + public-key-token from `System.Private.CoreLib` to
    /// `System.Runtime`. The runtime treats the two as type-equivalent via
    /// type-forwards (System.Runtime forwards Object, List, etc. to
    /// System.Private.CoreLib at the impl level), so semantics are
    /// preserved. The C# compiler now sees `System.Runtime` in the consumer
    /// csproj's framework reference and CS0012 goes away.
    ///
    /// ===== What this rewriter does, step by step =====
    ///
    /// Three byte-level edits on the raw PE:
    ///
    /// 1. #Strings heap rewrite. The 22-byte UTF-8 entry
    ///    "System.Private.CoreLib\0" is overwritten with
    ///    "System.Runtime\0" (15 bytes). The 8 trailing bytes of the
    ///    original are LEFT UNTOUCHED. This matters because Roslyn-emitted
    ///    metadata interns suffixes — for example, "CoreLib" and ".CoreLib"
    ///    may exist as separate strings whose offsets point INTO the middle
    ///    of "System.Private.CoreLib\0". Zeroing the trailing bytes (which
    ///    a naive rewrite does) corrupts those interned suffixes and
    ///    breaks signature/typeref resolution downstream. Only the NUL
    ///    terminator at offset (idx + "System.Runtime".Length) is set;
    ///    everything past that is preserved.
    ///
    /// 2. #Blob heap rewrite. PAB writes the corelib AssemblyRef with the
    ///    `PublicKey` flag set, so the PublicKeyOrToken column points at a
    ///    160-byte full RSA public-key blob. We shrink that blob to the
    ///    8-byte `System.Runtime` PublicKeyToken (b03f5f7f11d50a3a). The
    ///    blob's 2-byte length prefix is updated from 0x80 0xa0 (160) to
    ///    0x80 0x08 (8). The 152 bytes of the old key past the new token
    ///    become unused garbage that no other blob index references —
    ///    blob indices are by-offset, so shrinking one blob doesn't
    ///    invalidate any others. The blob's starting offset doesn't move,
    ///    so the AssemblyRef row's PublicKeyOrToken column stays valid.
    ///
    /// 3. AssemblyRef row Flags edit. We clear the `PublicKey` flag bit
    ///    (0x0001) on the row's Flags column. The runtime now reads the
    ///    blob as a raw 8-byte token rather than a full key needing SHA-1
    ///    hashing. We compute the row's Flags byte offset using
    ///    System.Reflection.Metadata's table layout APIs — see
    ///    <see cref="ComputeAssemblyRefFlagsOffset"/>.
    ///
    /// ===== Known limitation =====
    ///
    /// FieldRefs whose signatures contain a generic instantiation across
    /// the renamed corelib boundary (e.g. `[System.Runtime]List`1&lt;Value&gt;`)
    /// can fail to bind at runtime when the saved DLL is loaded into an
    /// isolated AssemblyLoadContext. The CrossProcessLoadTests fixture
    /// `AotLinkedCallIndirectModule_CrossProcess_RoundTrip` exposes this:
    /// the AOT-linked emission inlines IL touching
    /// `Wacs.Core.Runtime.Types.TableInstance.Elements` (a
    /// `List&lt;Value&gt;` field), and after the rewrite the runtime cannot
    /// unify the renamed-corelib FieldRef with the host's already-loaded
    /// `[System.Private.CoreLib]List`1` type instance. The byte-array path
    /// (MemoryInstance.Data) does not hit this because SZARRAY signatures
    /// don't go through generic-instantiation unification. The smoke test
    /// for `wacs aot --wasi` (which uses Standard emission and never
    /// triggers AOT-linked generic FieldRefs) works correctly.
    ///
    /// ===== When this hack can be removed =====
    ///
    /// Either of these would let us delete this file:
    ///
    /// (a) PAB upstream learns to emit `System.Runtime` as the corelib
    ///     identity when the impl `typeof(object).Assembly` is passed
    ///     (mapping types via reference-pack type-forwards transparently
    ///     during signature encoding). Tracked at
    ///     https://github.com/dotnet/runtime/issues/103357.
    ///
    /// (b) The transpiler's IL-emit pipeline is migrated to use
    ///     MetadataLoadContext-bound types throughout (every `typeof(int)`
    ///     swapped for `coreAssembly.GetType("System.Int32")`, every
    ///     generic instantiation built via MLC types, every reference to
    ///     methods on the codec/init helpers re-bound through MLC-loaded
    ///     impl assemblies). At that point we'd hand PAB the
    ///     ref-pack-loaded `System.Runtime` and the saved DLL's corelib
    ///     reference would be `System.Runtime` natively.
    ///
    /// Until either of those lands, this rewriter is the path of least
    /// surgery.
    /// </summary>
    internal static class CoreLibAssemblyRefRewriter
    {
        // System.Private.CoreLib full public key (160 bytes), as PAB writes
        // it into #Blob. Used to locate the blob for in-place replacement.
        // Source: typeof(object).Assembly.GetName().GetPublicKey() at
        // .NET 9.0.0.
        private static readonly byte[] PrivateCoreLibPublicKey = new byte[]
        {
            0x00, 0x24, 0x00, 0x00, 0x04, 0x80, 0x00, 0x00, 0x94, 0x00, 0x00, 0x00, 0x06, 0x02, 0x00, 0x00,
            0x00, 0x24, 0x00, 0x00, 0x52, 0x53, 0x41, 0x31, 0x00, 0x04, 0x00, 0x00, 0x01, 0x00, 0x01, 0x00,
            0x8d, 0x56, 0xc7, 0x6f, 0x9e, 0x86, 0x49, 0x38, 0x30, 0x49, 0xf3, 0x83, 0xc4, 0x4b, 0xe0, 0xec,
            0x20, 0x41, 0x81, 0x82, 0x2a, 0x6c, 0x31, 0xcf, 0x5e, 0xb7, 0xef, 0x48, 0x69, 0x44, 0xd0, 0x32,
            0x18, 0x8e, 0xa1, 0xd3, 0x92, 0x07, 0x63, 0x71, 0x2c, 0xcb, 0x12, 0xd7, 0x5f, 0xb7, 0x7e, 0x98,
            0x11, 0x14, 0x9e, 0x61, 0x48, 0xe5, 0xd3, 0x2f, 0xba, 0xab, 0x37, 0x61, 0x1c, 0x18, 0x78, 0xdd,
            0xc1, 0x9e, 0x20, 0xef, 0x13, 0x5d, 0x0c, 0xb2, 0xcf, 0xf2, 0xbf, 0xec, 0x3d, 0x11, 0x58, 0x10,
            0xc3, 0xd9, 0x06, 0x96, 0x38, 0xfe, 0x4b, 0xe2, 0x15, 0xdb, 0xf7, 0x95, 0x86, 0x19, 0x20, 0xe5,
            0xab, 0x6f, 0x7d, 0xb2, 0xe2, 0xce, 0xef, 0x13, 0x6a, 0xc2, 0x3d, 0x5d, 0xd2, 0xbf, 0x03, 0x17,
            0x00, 0xae, 0xc2, 0x32, 0xf6, 0xc6, 0xb1, 0xc7, 0x85, 0xb4, 0x30, 0x5c, 0x12, 0x3b, 0x37, 0xab,
        };

        // System.Runtime's PublicKeyToken: b0 3f 5f 7f 11 d5 0a 3a.
        private static readonly byte[] SystemRuntimePublicKeyToken =
            { 0xb0, 0x3f, 0x5f, 0x7f, 0x11, 0xd5, 0x0a, 0x3a };

        /// <summary>
        /// Rewrite the bytes of a saved .dll in place. Returns true if the
        /// AssemblyRef was found and rewritten, false if the file didn't
        /// reference System.Private.CoreLib (already-rewritten or a
        /// different corelib path; harmless either way).
        /// </summary>
        public static bool RewritePrivateCoreLibToSystemRuntime(byte[] peBytes)
        {
            // Use System.Reflection.Metadata to find the AssemblyRef row
            // and the byte offset of its Flags field. Heap edits are
            // simple byte searches; the Flags edit is the only piece
            // requiring a structural metadata read.
            using var ms = new MemoryStream(peBytes, writable: false);
            using var pe = new PEReader(ms);
            if (!pe.HasMetadata) return false;
            var reader = pe.GetMetadataReader();

            AssemblyReferenceHandle? targetHandle = null;
            foreach (var arh in reader.AssemblyReferences)
            {
                var ar = reader.GetAssemblyReference(arh);
                var name = reader.GetString(ar.Name);
                if (name == "System.Private.CoreLib")
                {
                    targetHandle = arh;
                    break;
                }
            }
            if (targetHandle == null) return false;

            int flagsByteOffset = ComputeAssemblyRefFlagsOffset(pe, reader, targetHandle.Value);

            // 1. #Strings rewrite: name "System.Private.CoreLib\0" →
            //    "System.Runtime\0", leaving suffix-interned bytes
            //    (e.g. "oreLib\0" at offset+15) intact.
            RewriteStringInPlace(peBytes, "System.Private.CoreLib", "System.Runtime");

            // 2. #Blob rewrite: shrink the 160-byte full key blob to the
            //    8-byte System.Runtime PKT.
            ShrinkPublicKeyBlobToToken(peBytes);

            // 3. Clear the PublicKey bit (0x0001) in the AssemblyRef Flags.
            //    Flags is a uint32, little-endian; bit 0 is the PublicKey
            //    flag. Clearing it tells the runtime to read the blob as a
            //    raw 8-byte token rather than a full key needing hashing.
            if (flagsByteOffset > 0 && flagsByteOffset + 4 <= peBytes.Length)
                peBytes[flagsByteOffset] &= 0xfe;

            return true;
        }

        /// <summary>
        /// Convenience overload: rewrite a file in place. Used by external
        /// tooling and tests.
        /// </summary>
        public static bool RewriteFile(string path)
        {
            var bytes = File.ReadAllBytes(path);
            if (!RewritePrivateCoreLibToSystemRuntime(bytes)) return false;
            File.WriteAllBytes(path, bytes);
            return true;
        }

        // The metadata #~ stream lays AssemblyRef rows at a stable offset:
        //   tableStart + (rowIndex - 1) * rowSize + columnOffset.
        // System.Reflection.Metadata exposes the row size and table offset
        // via GetTableRowSize / GetTableMetadataOffset; we add the
        // structurally-fixed column offset.
        //
        // Layout of an AssemblyRef row (ECMA-335 §22.5):
        //   MajorVersion (2) | MinorVersion (2) | BuildNumber (2) |
        //   RevisionNumber (2) | Flags (4) | PublicKeyOrToken (blobIdxSize)|
        //   Name (stringIdxSize) | Culture (stringIdxSize) |
        //   HashValue (blobIdxSize)
        //
        // Flags lives 8 bytes into the row. blobIdxSize/stringIdxSize
        // depend on the heap-size flags but are irrelevant for this
        // calculation since Flags precedes them all.
        private static int ComputeAssemblyRefFlagsOffset(
            PEReader pe, MetadataReader reader, AssemblyReferenceHandle handle)
        {
            int rowOffsetInTable = reader.GetTableRowSize(TableIndex.AssemblyRef)
                                   * (MetadataTokens.GetRowNumber(handle) - 1);
            int tableOffset = reader.GetTableMetadataOffset(TableIndex.AssemblyRef);
            int metadataStart = pe.PEHeaders.MetadataStartOffset;
            return metadataStart + tableOffset + rowOffsetInTable + 8; // +8 → Flags
        }

        // Overwrite the bytes of `oldStr\0` with `newStr\0`, leaving any
        // bytes past the new NUL terminator untouched. This is critical
        // for the #Strings heap: Roslyn-emitted metadata interns suffixes,
        // so the bytes between (idx + newStr.Length + 1) and
        // (idx + oldStr.Length) — originally e.g. "oreLib\0" inside
        // "System.Private.CoreLib\0" — may be referenced by other rows
        // pointing to that suffix offset. Zeroing them turns those
        // referenced strings into empty strings and breaks
        // type/member binding.
        private static void RewriteStringInPlace(byte[] peBytes, string oldStr, string newStr)
        {
            var oldBytes = System.Text.Encoding.UTF8.GetBytes(oldStr);
            var newBytes = System.Text.Encoding.UTF8.GetBytes(newStr);
            if (newBytes.Length >= oldBytes.Length) return; // not in scope
            int idx = IndexOf(peBytes, oldBytes, 0);
            while (idx >= 0)
            {
                int nulPos = idx + oldBytes.Length;
                if (nulPos < peBytes.Length && peBytes[nulPos] == 0)
                {
                    Buffer.BlockCopy(newBytes, 0, peBytes, idx, newBytes.Length);
                    peBytes[idx + newBytes.Length] = 0; // single NUL terminator
                    return;
                }
                idx = IndexOf(peBytes, oldBytes, idx + 1);
            }
        }

        // The blob heap stores the public key prefixed by a variable-length
        // size field. PAB writes 160-byte full keys with prefix 0x80 0xa0
        // (2-byte form, top bits 10). We shrink the blob in place: keep
        // the 2-byte prefix slot (so the row's PublicKeyOrToken offset
        // stays valid) but encode length=8 as 0x80 0x08, then write the
        // 8-byte System.Runtime token, then zero out the trailing 152
        // bytes (unused — no other blob index references them, per
        // offset-based addressing).
        private static void ShrinkPublicKeyBlobToToken(byte[] peBytes)
        {
            int idx = IndexOf(peBytes, PrivateCoreLibPublicKey, 0);
            if (idx < 0) return;
            if (idx < 2) return;
            // Sanity-check the length prefix to make sure we're at the
            // expected blob position (not a stray pubkey-byte sequence
            // that happened to match).
            if (peBytes[idx - 2] != 0x80 || peBytes[idx - 1] != 0xa0) return;

            // 2-byte length form encoding length=8: 0x80 0x08.
            peBytes[idx - 2] = 0x80;
            peBytes[idx - 1] = 0x08;
            Buffer.BlockCopy(SystemRuntimePublicKeyToken, 0, peBytes, idx, 8);
            for (int i = idx + 8; i < idx + PrivateCoreLibPublicKey.Length; i++)
                peBytes[i] = 0;
        }

        private static int IndexOf(byte[] haystack, byte[] needle, int start)
        {
            if (needle.Length == 0) return start;
            int last = haystack.Length - needle.Length;
            for (int i = start; i <= last; i++)
            {
                int j = 0;
                while (j < needle.Length && haystack[i + j] == needle[j]) j++;
                if (j == needle.Length) return i;
            }
            return -1;
        }
    }
}
