// Copyright 2026 Kelvin Nishikawa
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.

using System.IO;
using System.Linq;
using Wacs.ComponentModel.CSharpEmit;
using Wacs.ComponentModel.Types;
using Wacs.ComponentModel.WIT;
using Xunit;

namespace Wacs.ComponentModel.Test
{
    /// <summary>
    /// Phase 1a.2 snapshot tests comparing <see cref="CSharpEmitter"/>
    /// output to the pinned <c>wit-bindgen-csharp</c> 0.30.0 reference
    /// under <c>Spec.Test/components/fixtures/hello-world/reference/</c>.
    ///
    /// <para><b>Coverage this session:</b> world shell file,
    /// empty-interface Interop files, and the standalone
    /// <c>WasmImportLinkageAttribute</c> file. Interface files with
    /// methods, Interop files with DllImport trampolines, and the
    /// various type-level class/struct/enum emissions are explicit
    /// Phase 1a.2 follow-ups — see the TODOs in CSharpEmitter.cs.</para>
    ///
    /// <para>The roundtrip gate (Phase 1b verification) needs the
    /// full emitter to pass end-to-end; this test file is the
    /// incremental gate — each new emitter ships with its snapshot
    /// here.</para>
    /// </summary>
    public class CSharpEmitterTests
    {
        // ---- Fixture helpers -----------------------------------------------

        private static string FindFixturesDir()
        {
            var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
            while (dir != null && !File.Exists(Path.Combine(dir.FullName, "WACS.sln")))
                dir = dir.Parent;
            if (dir == null) return string.Empty;
            return Path.Combine(dir.FullName, "Spec.Test", "components",
                                "fixtures", "hello-world");
        }

        /// <summary>
        /// Load the hello-world WIT and parse it into
        /// <see cref="CtWorldType"/> for emitter input. Pulls from the
        /// pinned fixture so any grammar drift trips this test before
        /// it trips a downstream emitter test.
        /// </summary>
        private static CtWorldType LoadHelloWorld()
        {
            var dir = FindFixturesDir();
            var src = File.ReadAllText(Path.Combine(dir, "wit", "hello.wit"));
            var doc = WitParser.Parse(src);
            var pkgs = WitToTypes.Convert(doc);
            var pkg = Assert.Single(pkgs);
            return Assert.Single(pkg.Worlds);
        }

        private static string LoadReference(string fileName) =>
            File.ReadAllText(Path.Combine(FindFixturesDir(), "reference", fileName));

        // ---- World shell file ----------------------------------------------

        [Fact]
        public void World_shell_file_matches_reference_Hello_cs()
        {
            var world = LoadHelloWorld();
            var sources = CSharpEmitter.EmitWorld(world);
            var hello = sources.Single(s => s.FileName == "Hello.cs");

            var expected = LoadReference("Hello.cs");
            Assert.Equal(expected, hello.Content);
        }

        // ---- Linkage attribute standalone file -----------------------------

        [Fact]
        public void WasmImportLinkage_attribute_file_matches_reference()
        {
            var world = LoadHelloWorld();
            var sources = CSharpEmitter.EmitWorld(world);
            var attrFile = sources.Single(s =>
                s.FileName == "HelloWorld_wasm_import_linkage_attribute.cs");

            var expected = LoadReference(
                "HelloWorld_wasm_import_linkage_attribute.cs");
            Assert.Equal(expected, attrFile.Content);
        }

        // ---- Empty Interop files -------------------------------------------

        [Fact]
        public void Empty_interop_file_matches_reference_ErrorInterop_cs()
        {
            // wasi:io/error has only a resource type and no free
            // functions, so wit-bindgen-csharp emits an empty Interop.
            // We don't emit this file directly (hello-world doesn't
            // import wasi:io/error), but the file IS generated by
            // wit-bindgen because wasi:io/streams depends on
            // wasi:io/error. Skip for now — we'll revisit the
            // transitive-deps emission question in a later session.
            // For the immediate test, we have StreamsInterop.
            var world = LoadHelloWorld();
            var sources = CSharpEmitter.EmitWorld(world);
            var streamsInterop = sources.Single(s =>
                s.FileName == "HelloWorld.wit.imports.wasi.io.v0_2_3.StreamsInterop.cs");

            var expected = LoadReference(
                "HelloWorld.wit.imports.wasi.io.v0_2_3.StreamsInterop.cs");
            Assert.Equal(expected, streamsInterop.Content);
        }

        // ---- Output inventory ---------------------------------------------

        /// <summary>
        /// Phase 1a.2 scope: the emitter returns the world shell file,
        /// one empty Interop per imported/exported interface, and the
        /// linkage attribute support file. As we implement more of the
        /// emitter the expected count grows — update this alongside.
        /// </summary>
        [Fact]
        public void EmitWorld_returns_phase_1a2_file_set()
        {
            var world = LoadHelloWorld();
            var sources = CSharpEmitter.EmitWorld(world);
            var names = sources.Select(s => s.FileName).OrderBy(n => n).ToArray();

            // hello world has: 1 export interface (wasi:cli/run),
            // 2 import interfaces (wasi:cli/stdout, wasi:io/streams).
            // Each produces an (empty) Interop file; IRun / I*
            // interface files are TODO and not emitted yet. Plus the
            // world shell + the linkage attribute = 5 files total.
            Assert.Equal(5, names.Length);
            Assert.Contains("Hello.cs", names);
            Assert.Contains("HelloWorld_wasm_import_linkage_attribute.cs", names);
            Assert.Contains(
                "HelloWorld.wit.exports.wasi.cli.v0_2_3.RunInterop.cs", names);
            Assert.Contains(
                "HelloWorld.wit.imports.wasi.cli.v0_2_3.StdoutInterop.cs", names);
            Assert.Contains(
                "HelloWorld.wit.imports.wasi.io.v0_2_3.StreamsInterop.cs", names);
        }

        // ---- Naming convention unit tests ----------------------------------

        [Theory]
        [InlineData("input-stream", "InputStream")]
        [InlineData("last-operation-failed", "LastOperationFailed")]
        [InlineData("hello", "Hello")]
        [InlineData("a", "A")]
        [InlineData("", "")]
        public void ToPascalCase_converts_kebab(string input, string expected)
        {
            Assert.Equal(expected, NameConventions.ToPascalCase(input));
        }

        [Theory]
        [InlineData("last-operation-failed", "lastOperationFailed")]
        [InlineData("read", "read")]
        public void ToCamelCase_converts_kebab(string input, string expected)
        {
            Assert.Equal(expected, NameConventions.ToCamelCase(input));
        }

        [Theory]
        [InlineData("last-operation-failed", "LAST_OPERATION_FAILED")]
        [InlineData("read", "READ")]
        public void ToUpperSnake_converts_kebab(string input, string expected)
        {
            Assert.Equal(expected, NameConventions.ToUpperSnake(input));
        }

        [Theory]
        [InlineData("0.2.3", "v0_2_3")]
        [InlineData("1.0.0", "v1_0_0")]
        [InlineData(null, "")]
        [InlineData("", "")]
        public void SanitizeVersion_produces_wit_bindgen_namespace_form(
            string? input, string expected)
        {
            Assert.Equal(expected, NameConventions.SanitizeVersion(input));
        }

        [Theory]
        [InlineData("hello", "HelloWorld")]
        [InlineData("command", "CommandWorld")]
        [InlineData("proxy-world", "ProxyWorld")]
        [InlineData("my-world", "MyWorld")]
        public void WorldNamespaceName_suffixes_World(string input, string expected)
        {
            Assert.Equal(expected, NameConventions.WorldNamespaceName(input));
        }

        [Theory]
        [InlineData("hello", "Hello")]
        [InlineData("command", "Command")]
        public void WorldFileBaseName_is_pascal_case_without_World_suffix(
            string input, string expected)
        {
            Assert.Equal(expected, NameConventions.WorldFileBaseName(input));
        }

        [Fact]
        public void InterfaceNamespace_for_imports()
        {
            var pkg = new CtPackageName("wasi", new[] { "io" }, "0.2.3");
            Assert.Equal("HelloWorld.wit.imports.wasi.io.v0_2_3",
                         NameConventions.InterfaceNamespace("hello",
                                                            isExport: false,
                                                            pkg));
        }

        [Fact]
        public void InterfaceNamespace_for_exports()
        {
            var pkg = new CtPackageName("wasi", new[] { "cli" }, "0.2.3");
            Assert.Equal("HelloWorld.wit.exports.wasi.cli.v0_2_3",
                         NameConventions.InterfaceNamespace("hello",
                                                            isExport: true,
                                                            pkg));
        }
    }
}
