// Copyright 2026 Kelvin Nishikawa
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.

using System.IO;
using System.Linq;
using Wacs.ComponentModel.CSharpEmit;
using Wacs.ComponentModel.Types;
using Wacs.ComponentModel.WIT;
using Xunit;

namespace Wacs.ComponentModel.Test
{
    /// <summary>
    /// Phase 1a.2 snapshot tests comparing <see cref="CSharpEmitter"/>
    /// output to the pinned <c>wit-bindgen-csharp</c> 0.30.0 reference
    /// under <c>Spec.Test/components/fixtures/hello-world/reference/</c>.
    ///
    /// <para><b>Coverage this session:</b> world shell file,
    /// empty-interface Interop files, and the standalone
    /// <c>WasmImportLinkageAttribute</c> file. Interface files with
    /// methods, Interop files with DllImport trampolines, and the
    /// various type-level class/struct/enum emissions are explicit
    /// Phase 1a.2 follow-ups — see the TODOs in CSharpEmitter.cs.</para>
    ///
    /// <para>The roundtrip gate (Phase 1b verification) needs the
    /// full emitter to pass end-to-end; this test file is the
    /// incremental gate — each new emitter ships with its snapshot
    /// here.</para>
    /// </summary>
    public class CSharpEmitterTests
    {
        // ---- Fixture helpers -----------------------------------------------

        private static string FindFixturesDir()
        {
            var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
            while (dir != null && !File.Exists(Path.Combine(dir.FullName, "WACS.sln")))
                dir = dir.Parent;
            if (dir == null) return string.Empty;
            return Path.Combine(dir.FullName, "Spec.Test", "components",
                                "fixtures", "hello-world");
        }

        /// <summary>
        /// Load the hello-world WIT and parse it into
        /// <see cref="CtWorldType"/> for emitter input. Pulls from the
        /// pinned fixture so any grammar drift trips this test before
        /// it trips a downstream emitter test.
        /// </summary>
        private static CtWorldType LoadHelloWorld()
        {
            var dir = FindFixturesDir();
            var src = File.ReadAllText(Path.Combine(dir, "wit", "hello.wit"));
            var doc = WitParser.Parse(src);
            var pkgs = WitToTypes.Convert(doc);
            var pkg = Assert.Single(pkgs);
            return Assert.Single(pkg.Worlds);
        }

        private static string LoadReference(string fileName) =>
            File.ReadAllText(Path.Combine(FindFixturesDir(), "reference", fileName));

        // ---- World shell file ----------------------------------------------

        [Fact]
        public void World_shell_file_matches_reference_Hello_cs()
        {
            var world = LoadHelloWorld();
            var sources = CSharpEmitter.EmitWorld(world);
            var hello = sources.Single(s => s.FileName == "Hello.cs");

            var expected = LoadReference("Hello.cs");
            Assert.Equal(expected, hello.Content);
        }

        // ---- Linkage attribute standalone file -----------------------------

        [Fact]
        public void WasmImportLinkage_attribute_file_matches_reference()
        {
            var world = LoadHelloWorld();
            var sources = CSharpEmitter.EmitWorld(world);
            var attrFile = sources.Single(s =>
                s.FileName == "HelloWorld_wasm_import_linkage_attribute.cs");

            var expected = LoadReference(
                "HelloWorld_wasm_import_linkage_attribute.cs");
            Assert.Equal(expected, attrFile.Content);
        }

        // ---- Empty Interop files -------------------------------------------

        [Fact]
        public void Empty_interop_file_matches_reference_ErrorInterop_cs()
        {
            // wasi:io/error has only a resource type and no free
            // functions, so wit-bindgen-csharp emits an empty Interop.
            // We don't emit this file directly (hello-world doesn't
            // import wasi:io/error), but the file IS generated by
            // wit-bindgen because wasi:io/streams depends on
            // wasi:io/error. Skip for now — we'll revisit the
            // transitive-deps emission question in a later session.
            // For the immediate test, we have StreamsInterop.
            var world = LoadHelloWorld();
            var sources = CSharpEmitter.EmitWorld(world);
            var streamsInterop = sources.Single(s =>
                s.FileName == "HelloWorld.wit.imports.wasi.io.v0_2_3.StreamsInterop.cs");

            var expected = LoadReference(
                "HelloWorld.wit.imports.wasi.io.v0_2_3.StreamsInterop.cs");
            Assert.Equal(expected, streamsInterop.Content);
        }

        // ---- Output inventory ---------------------------------------------

        /// <summary>
        /// Phase 1a.2 scope: the emitter returns the world shell file,
        /// one empty Interop per imported/exported interface, and the
        /// linkage attribute support file. As we implement more of the
        /// emitter the expected count grows — update this alongside.
        /// </summary>
        [Fact]
        public void EmitWorld_returns_phase_1a2_file_set()
        {
            var world = LoadHelloWorld();
            var sources = CSharpEmitter.EmitWorld(world);
            var names = sources.Select(s => s.FileName).OrderBy(n => n).ToArray();

            // hello world has: 1 export interface (wasi:cli/run),
            // 2 import interfaces (wasi:cli/stdout, wasi:io/streams).
            // Each produces an (empty) Interop file; IRun / I*
            // interface files are TODO and not emitted yet. Plus the
            // world shell + the linkage attribute = 5 files total.
            Assert.Equal(5, names.Length);
            Assert.Contains("Hello.cs", names);
            Assert.Contains("HelloWorld_wasm_import_linkage_attribute.cs", names);
            Assert.Contains(
                "HelloWorld.wit.exports.wasi.cli.v0_2_3.RunInterop.cs", names);
            Assert.Contains(
                "HelloWorld.wit.imports.wasi.cli.v0_2_3.StdoutInterop.cs", names);
            Assert.Contains(
                "HelloWorld.wit.imports.wasi.io.v0_2_3.StreamsInterop.cs", names);
        }

        // ---- Naming convention unit tests ----------------------------------

        [Theory]
        [InlineData("input-stream", "InputStream")]
        [InlineData("last-operation-failed", "LastOperationFailed")]
        [InlineData("hello", "Hello")]
        [InlineData("a", "A")]
        [InlineData("", "")]
        public void ToPascalCase_converts_kebab(string input, string expected)
        {
            Assert.Equal(expected, NameConventions.ToPascalCase(input));
        }

        [Theory]
        [InlineData("last-operation-failed", "lastOperationFailed")]
        [InlineData("read", "read")]
        public void ToCamelCase_converts_kebab(string input, string expected)
        {
            Assert.Equal(expected, NameConventions.ToCamelCase(input));
        }

        [Theory]
        [InlineData("last-operation-failed", "LAST_OPERATION_FAILED")]
        [InlineData("read", "READ")]
        public void ToUpperSnake_converts_kebab(string input, string expected)
        {
            Assert.Equal(expected, NameConventions.ToUpperSnake(input));
        }

        [Theory]
        [InlineData("0.2.3", "v0_2_3")]
        [InlineData("1.0.0", "v1_0_0")]
        [InlineData(null, "")]
        [InlineData("", "")]
        public void SanitizeVersion_produces_wit_bindgen_namespace_form(
            string? input, string expected)
        {
            Assert.Equal(expected, NameConventions.SanitizeVersion(input));
        }

        [Theory]
        [InlineData("hello", "HelloWorld")]
        [InlineData("command", "CommandWorld")]
        // wit-bindgen-csharp 0.30.0 appends `World` unconditionally —
        // even when the kebab name already ends in `world`. Verified
        // by running wit-bindgen against a world literally named
        // `prim-world` and observing namespace `PrimWorldWorld`.
        [InlineData("prim-world", "PrimWorldWorld")]
        [InlineData("my-world", "MyWorldWorld")]
        public void WorldNamespaceName_suffixes_World(string input, string expected)
        {
            Assert.Equal(expected, NameConventions.WorldNamespaceName(input));
        }

        [Theory]
        [InlineData("hello", "Hello")]
        [InlineData("command", "Command")]
        public void WorldFileBaseName_is_pascal_case_without_World_suffix(
            string input, string expected)
        {
            Assert.Equal(expected, NameConventions.WorldFileBaseName(input));
        }

        [Fact]
        public void InterfaceNamespace_for_imports()
        {
            var pkg = new CtPackageName("wasi", new[] { "io" }, "0.2.3");
            Assert.Equal("HelloWorld.wit.imports.wasi.io.v0_2_3",
                         NameConventions.InterfaceNamespace("hello",
                                                            isExport: false,
                                                            pkg));
        }

        [Fact]
        public void InterfaceNamespace_for_exports()
        {
            var pkg = new CtPackageName("wasi", new[] { "cli" }, "0.2.3");
            Assert.Equal("HelloWorld.wit.exports.wasi.cli.v0_2_3",
                         NameConventions.InterfaceNamespace("hello",
                                                            isExport: true,
                                                            pkg));
        }

        // ---- Export interface file emission (IRun.cs shape) -----------------

        /// <summary>
        /// Hand-construct the <c>wasi:cli/run</c> interface — one
        /// function <c>run: func() -&gt; result</c>, which wit-bindgen
        /// lowers to <c>static abstract void Run()</c> on the guest
        /// side (the result is implicit in the export trampoline and
        /// doesn't appear on the interface method).
        ///
        /// <para>In Phase 1a.2's scope the interface file only carries
        /// the method signature; the <c>result</c> lowering lives in
        /// the <c>RunInterop</c> trampoline which is a separate
        /// follow-up emitter. So the input to the interface emitter
        /// is the void-returning signature, not the result-returning
        /// one — matching how wit-bindgen internally threads the
        /// shape through.</para>
        /// </summary>
        private static CtInterfaceType BuildRunInterface()
        {
            var pkg = new CtPackageName("wasi", new[] { "cli" }, "0.2.3");
            var runFnType = new CtFunctionType(
                new System.Collections.Generic.List<CtFuncParam>(),
                result: null,
                namedResults: null);
            var runFn = new CtInterfaceFunction("run", runFnType);
            return new CtInterfaceType(
                pkg, "run",
                new System.Collections.Generic.List<CtNamedType>(),
                new[] { runFn },
                new System.Collections.Generic.List<CtUse>());
        }

        [Fact]
        public void EmitExportInterfaceFile_matches_reference_IRun()
        {
            var iface = BuildRunInterface();
            var emitted = CSharpEmitter.EmitExportInterfaceFile(iface, "hello");

            Assert.Equal(
                "HelloWorld.wit.exports.wasi.cli.v0_2_3.IRun.cs",
                emitted.FileName);

            var expected = LoadReference(
                "HelloWorld.wit.exports.wasi.cli.v0_2_3.IRun.cs");
            Assert.Equal(expected, emitted.Content);
        }

        // ---- Type-ref emission -------------------------------------------

        [Theory]
        [InlineData(CtPrim.Bool, "bool")]
        [InlineData(CtPrim.S8, "sbyte")]
        [InlineData(CtPrim.U8, "byte")]
        [InlineData(CtPrim.S16, "short")]
        [InlineData(CtPrim.U16, "ushort")]
        [InlineData(CtPrim.S32, "int")]
        [InlineData(CtPrim.U32, "uint")]
        [InlineData(CtPrim.S64, "long")]
        [InlineData(CtPrim.U64, "ulong")]
        [InlineData(CtPrim.F32, "float")]
        [InlineData(CtPrim.F64, "double")]
        [InlineData(CtPrim.Char, "uint")]
        [InlineData(CtPrim.String, "string")]
        public void EmitPrim_maps_to_wit_bindgen_csharp_primitive(
            CtPrim kind, string expected)
        {
            Assert.Equal(expected, TypeRefEmit.EmitPrim(kind));
        }

        // ---- Function signature emission ----------------------------------

        [Fact]
        public void EmitStaticAbstractSignature_void_no_args()
        {
            var sig = new CtFunctionType(
                new System.Collections.Generic.List<CtFuncParam>(),
                result: null, namedResults: null);
            Assert.Equal(
                "    static abstract void Run();",
                FunctionEmit.EmitStaticAbstractSignature("run", sig));
        }

        [Fact]
        public void EmitStaticAbstractSignature_primitive_return()
        {
            var sig = new CtFunctionType(
                new[] { new CtFuncParam("x", CtPrimType.S32) },
                result: CtPrimType.S32,
                namedResults: null);
            Assert.Equal(
                "    static abstract int DoS32(int x);",
                FunctionEmit.EmitStaticAbstractSignature("do-s32", sig));
        }

        [Fact]
        public void EmitStaticAbstractSignature_multiple_args()
        {
            var sig = new CtFunctionType(
                new[]
                {
                    new CtFuncParam("a", CtPrimType.U32),
                    new CtFuncParam("b", CtPrimType.U32),
                },
                result: CtPrimType.U32,
                namedResults: null);
            Assert.Equal(
                "    static abstract uint TwoArgs(uint a, uint b);",
                FunctionEmit.EmitStaticAbstractSignature("two-args", sig));
        }

        [Fact]
        public void EmitStaticAbstractSignature_kebab_arg_becomes_camelCase()
        {
            var sig = new CtFunctionType(
                new[] { new CtFuncParam("max-length", CtPrimType.U64) },
                result: null, namedResults: null);
            Assert.Equal(
                "    static abstract void Process(ulong maxLength);",
                FunctionEmit.EmitStaticAbstractSignature("process", sig));
        }

        [Fact]
        public void EmitReturnType_result_with_no_payload_lowers_to_void()
        {
            var sig = new CtFunctionType(
                new System.Collections.Generic.List<CtFuncParam>(),
                result: new CtResultType(null, null),
                namedResults: null);
            Assert.Equal("void", FunctionEmit.EmitReturnType(sig));
        }

        // ---- Aggregate type ref emission ----------------------------------

        [Fact]
        public void EmitParam_list_of_primitive()
        {
            var t = new CtListType(CtPrimType.U32);
            Assert.Equal("uint[]", TypeRefEmit.EmitParam(t));
        }

        [Fact]
        public void EmitParam_option_of_primitive()
        {
            var t = new CtOptionType(CtPrimType.U32);
            Assert.Equal("uint?", TypeRefEmit.EmitParam(t));
        }

        [Fact]
        public void EmitParam_result_with_both_sides_is_generic()
        {
            var t = new CtResultType(CtPrimType.U32, CtPrimType.String);
            Assert.Equal("Result<uint, string>", TypeRefEmit.EmitParam(t));
        }

        [Fact]
        public void EmitParam_result_with_missing_side_uses_None()
        {
            // result<u32> (err-elided) as parameter.
            var t = new CtResultType(CtPrimType.U32, null);
            Assert.Equal("Result<uint, None>", TypeRefEmit.EmitParam(t));
        }

        [Fact]
        public void EmitReturn_result_with_ok_unwraps_to_ok()
        {
            var t = new CtResultType(CtPrimType.U32, CtPrimType.String);
            Assert.Equal("uint", TypeRefEmit.EmitReturn(t));
        }

        [Fact]
        public void EmitReturn_result_err_only_is_void()
        {
            var t = new CtResultType(null, CtPrimType.String);
            Assert.Equal("void", TypeRefEmit.EmitReturn(t));
        }

        [Fact]
        public void EmitParam_tuple_of_primitives()
        {
            var t = new CtTupleType(new CtValType[] { CtPrimType.U32, CtPrimType.String });
            Assert.Equal("(uint, string)", TypeRefEmit.EmitParam(t));
        }

        [Fact]
        public void EmitParam_nested_list_of_list()
        {
            var t = new CtListType(new CtListType(CtPrimType.U8));
            Assert.Equal("byte[][]", TypeRefEmit.EmitParam(t));
        }

        // ---- Aggregate fixture snapshot -----------------------------------

        private static string FindAggregatesFixtureDir()
        {
            var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
            while (dir != null && !File.Exists(Path.Combine(dir.FullName, "WACS.sln")))
                dir = dir.Parent;
            if (dir == null) return string.Empty;
            return Path.Combine(dir.FullName, "Spec.Test", "components",
                                "fixtures", "aggregates");
        }

        [Fact]
        public void EmitExportInterfaceFile_matches_reference_IOps_aggregates()
        {
            // Parse the pinned agg.wit and convert to Types. The
            // `ops` interface lives in the same file as the world, so
            // no cross-file resolution is needed — we pull the
            // CtInterfaceType straight out of the package.
            var fixtureDir = FindAggregatesFixtureDir();
            var src = File.ReadAllText(Path.Combine(fixtureDir, "wit", "agg.wit"));
            var pkgs = WitToTypes.Convert(WitParser.Parse(src));
            var iface = pkgs.Single().Interfaces.Single(i => i.Name == "ops");

            var emitted = CSharpEmitter.EmitExportInterfaceFile(
                iface, "agg-world");

            Assert.Equal(
                "AggWorldWorld.wit.exports.local.agg.IOps.cs",
                emitted.FileName);

            var expected = File.ReadAllText(Path.Combine(
                fixtureDir, "reference",
                "AggWorldWorld.wit.exports.local.agg.IOps.cs"));
            Assert.Equal(expected, emitted.Content);
        }

        // ---- Types: enum + flags nested in interface ----------------------

        private static string FindTypesEnumFlagsFixtureDir()
        {
            var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
            while (dir != null && !File.Exists(Path.Combine(dir.FullName, "WACS.sln")))
                dir = dir.Parent;
            if (dir == null) return string.Empty;
            return Path.Combine(dir.FullName, "Spec.Test", "components",
                                "fixtures", "types-enum-flags");
        }

        [Fact]
        public void EmitExportInterfaceFile_matches_reference_IDef_enum_and_flags()
        {
            var fixtureDir = FindTypesEnumFlagsFixtureDir();
            var src = File.ReadAllText(Path.Combine(fixtureDir, "wit", "typ.wit"));
            var pkgs = WitToTypes.Convert(WitParser.Parse(src));
            var iface = pkgs.Single().Interfaces.Single(i => i.Name == "def");

            var emitted = CSharpEmitter.EmitExportInterfaceFile(iface, "typ-world");

            Assert.Equal(
                "TypWorldWorld.wit.exports.local.typ.IDef.cs",
                emitted.FileName);
            var expected = File.ReadAllText(Path.Combine(
                fixtureDir, "reference",
                "TypWorldWorld.wit.exports.local.typ.IDef.cs"));
            Assert.Equal(expected, emitted.Content);
        }

        // ---- WitName metadata emission ------------------------------------

        [Fact]
        public void IncludeWitMetadata_off_omits_WitName_attributes()
        {
            var src = @"
                package local:decor;
                interface def {
                    enum color { red, green, blue }
                }
                world w { export def; }";
            var pkgs = WitToTypes.Convert(WitParser.Parse(src));
            var iface = pkgs.Single().Interfaces.Single(i => i.Name == "def");

            var emitted = CSharpEmitter.EmitExportInterfaceFile(iface, "w");

            Assert.DoesNotContain("WitName", emitted.Content);
        }

        [Fact]
        public void IncludeWitMetadata_on_decorates_type_defs()
        {
            var src = @"
                package local:decor;
                interface def {
                    enum my-kind { one, two }
                    record web-address { host-name: string, port: u16 }
                }
                world w { export def; }";
            var pkgs = WitToTypes.Convert(WitParser.Parse(src));
            var iface = pkgs.Single().Interfaces.Single(i => i.Name == "def");

            var emitted = CSharpEmitter.EmitExportInterfaceFile(
                iface, "w",
                new EmitOptions { IncludeWitMetadata = true });

            // Enum decorated with original kebab name.
            Assert.Contains(
                "[global::Wacs.ComponentModel.WitName(\"my-kind\")]",
                emitted.Content);
            // Record decorated.
            Assert.Contains(
                "[global::Wacs.ComponentModel.WitName(\"web-address\")]",
                emitted.Content);
        }

        // ---- Doc-comment passthrough --------------------------------------

        [Fact]
        public void WitTypeDef_doc_comments_propagate_to_AST()
        {
            // Multi-line /// block before a type def becomes
            // CtNamedType.DocLines.
            var src = @"package local:doc;
interface def {
    /// A color of the rainbow.
    /// Accepts only primary hues.
    enum color { red, green, blue }
}
world w { export def; }";
            var pkgs = WitToTypes.Convert(WitParser.Parse(src));
            var iface = pkgs.Single().Interfaces.Single(i => i.Name == "def");
            var color = iface.Types.Single(t => t.Name == "color");

            Assert.NotNull(color.DocLines);
            Assert.Equal(2, color.DocLines!.Count);
            Assert.Equal("A color of the rainbow.", color.DocLines[0]);
            Assert.Equal("Accepts only primary hues.", color.DocLines[1]);
        }

        [Fact]
        public void EmitExportInterfaceFile_wraps_doc_lines_in_summary_block()
        {
            // Doc comments from WIT → /// <summary> XML doc block in C#.
            // The indent matches the nested-type indent (4 spaces) so the
            // block reads naturally above the declaration.
            var src = @"package local:doc;
interface def {
    /// A color of the rainbow.
    /// Accepts only primary hues.
    enum color { red, green, blue }
}
world w { export def; }";
            var pkgs = WitToTypes.Convert(WitParser.Parse(src));
            var iface = pkgs.Single().Interfaces.Single(i => i.Name == "def");

            var emitted = CSharpEmitter.EmitExportInterfaceFile(iface, "w");

            Assert.Contains(
                "    /// <summary>\n" +
                "    /// A color of the rainbow.\n" +
                "    /// Accepts only primary hues.\n" +
                "    /// </summary>\n" +
                "    public enum Color",
                emitted.Content);
        }

        [Fact]
        public void EmitExportInterfaceFile_omits_summary_for_undocumented_types()
        {
            // No WIT doc comment → no /// block. Makes sure we don't
            // accidentally emit empty <summary> wrappers for types
            // without DocLines.
            var src = @"package local:doc;
interface def {
    enum color { red, green, blue }
}
world w { export def; }";
            var pkgs = WitToTypes.Convert(WitParser.Parse(src));
            var iface = pkgs.Single().Interfaces.Single(i => i.Name == "def");

            var emitted = CSharpEmitter.EmitExportInterfaceFile(iface, "w");

            Assert.DoesNotContain("/// <summary>", emitted.Content);
        }

        // ---- Types: record -----------------------------------------------

        private static string FindTypesRecordFixtureDir()
        {
            var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
            while (dir != null && !File.Exists(Path.Combine(dir.FullName, "WACS.sln")))
                dir = dir.Parent;
            if (dir == null) return string.Empty;
            return Path.Combine(dir.FullName, "Spec.Test", "components",
                                "fixtures", "types-record");
        }

        [Fact]
        public void EmitExportInterfaceFile_matches_reference_record_primitives()
        {
            var fixtureDir = FindTypesRecordFixtureDir();
            var src = File.ReadAllText(Path.Combine(fixtureDir, "wit", "rec.wit"));
            var pkgs = WitToTypes.Convert(WitParser.Parse(src));
            var iface = pkgs.Single().Interfaces.Single(i => i.Name == "def");

            var emitted = CSharpEmitter.EmitExportInterfaceFile(iface, "rec-world");

            var expected = File.ReadAllText(Path.Combine(
                fixtureDir, "reference",
                "RecWorldWorld.wit.exports.local.rec.IDef.cs"));
            Assert.Equal(expected, emitted.Content);
        }

        [Fact]
        public void EmitExportInterfaceFile_matches_reference_record_kebab_fields()
        {
            // Exercises kebab-case field names (host-name →
            // hostName, port-number → portNumber) and kebab-case
            // record name (web-address → WebAddress).
            var fixtureDir = FindTypesRecordFixtureDir();
            var src = File.ReadAllText(Path.Combine(fixtureDir, "wit", "rec2.wit"));
            var pkgs = WitToTypes.Convert(WitParser.Parse(src));
            var iface = pkgs.Single().Interfaces.Single(i => i.Name == "def");

            var emitted = CSharpEmitter.EmitExportInterfaceFile(iface, "rec2-world");

            var expected = File.ReadAllText(Path.Combine(
                fixtureDir, "reference",
                "Rec2WorldWorld.wit.exports.local.rec2.IDef.cs"));
            Assert.Equal(expected, emitted.Content);
        }

        // ---- Types: variant -----------------------------------------------

        private static string FindTypesVariantFixtureDir()
        {
            var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
            while (dir != null && !File.Exists(Path.Combine(dir.FullName, "WACS.sln")))
                dir = dir.Parent;
            if (dir == null) return string.Empty;
            return Path.Combine(dir.FullName, "Spec.Test", "components",
                                "fixtures", "types-variant");
        }

        [Fact]
        public void EmitExportInterfaceFile_matches_reference_variant_shape()
        {
            // Exercises: primitive-payload case (f32), tuple-payload
            // case (tuple<f32,f32> → (float, float)), no-payload
            // case (empty), string-payload case — covers the four
            // variant-case shapes in wit-bindgen 0.30.0's output.
            var fixtureDir = FindTypesVariantFixtureDir();
            var src = File.ReadAllText(Path.Combine(fixtureDir, "wit", "var.wit"));
            var pkgs = WitToTypes.Convert(WitParser.Parse(src));
            var iface = pkgs.Single().Interfaces.Single(i => i.Name == "def");

            var emitted = CSharpEmitter.EmitExportInterfaceFile(iface, "var-world");

            var expected = File.ReadAllText(Path.Combine(
                fixtureDir, "reference",
                "VarWorldWorld.wit.exports.local.var.IDef.cs"));
            Assert.Equal(expected, emitted.Content);
        }

        // ---- Resource methods with aggregate returns ---------------------

        private static string FindTypesResourceStringFixtureDir()
        {
            var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
            while (dir != null && !File.Exists(Path.Combine(dir.FullName, "WACS.sln")))
                dir = dir.Parent;
            if (dir == null) return string.Empty;
            return Path.Combine(dir.FullName, "Spec.Test", "components",
                                "fixtures", "types-resource-string");
        }

        /// <summary>
        /// Resource method with a string return. Uses the return-area
        /// buffer pattern (same as import free functions), but with
        /// <c>handle</c> declared first and passed as the first stub
        /// arg. Stub signature: void return + trailing <c>nint</c>
        /// ret-area pointer.
        /// </summary>
        [Fact]
        public void Resource_method_string_return_uses_return_area()
        {
            var fixtureDir = FindTypesResourceStringFixtureDir();
            var src = File.ReadAllText(Path.Combine(fixtureDir, "wit", "rs.wit"));
            var pkgs = WitToTypes.Convert(WitParser.Parse(src));
            var iface = pkgs.Single().Interfaces.Single(i => i.Name == "env");

            var emitted = CSharpEmitter.EmitImportInterfaceFile(
                iface, "rs-world");

            var expected = File.ReadAllText(Path.Combine(
                fixtureDir, "reference",
                "RsWorldWorld.wit.imports.local.rs.IEnv.cs"));
            Assert.Equal(expected, emitted.Content);
        }

        // ---- Types: resource ----------------------------------------------

        private static string FindTypesResourceFixtureDir()
        {
            var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
            while (dir != null && !File.Exists(Path.Combine(dir.FullName, "WACS.sln")))
                dir = dir.Parent;
            if (dir == null) return string.Empty;
            return Path.Combine(dir.FullName, "Spec.Test", "components",
                                "fixtures", "types-resource");
        }

        [Fact]
        public void EmitImportInterfaceFile_matches_reference_resource_primitives()
        {
            // Resource `clock` with three primitive-only methods:
            // tick (→ u64), set-offset (s32 →), is-running (→ bool).
            // Exercises IDisposable pattern, resource-drop DllImport,
            // per-method stub + wrapper with primitive lift/lower.
            var fixtureDir = FindTypesResourceFixtureDir();
            var src = File.ReadAllText(Path.Combine(fixtureDir, "wit", "res.wit"));
            var pkgs = WitToTypes.Convert(WitParser.Parse(src));
            var iface = pkgs.Single().Interfaces.Single(i => i.Name == "env");

            var emitted = CSharpEmitter.EmitImportInterfaceFile(
                iface, "res-world");

            Assert.Equal(
                "ResWorldWorld.wit.imports.local.res.IEnv.cs",
                emitted.FileName);
            var expected = File.ReadAllText(Path.Combine(
                fixtureDir, "reference",
                "ResWorldWorld.wit.imports.local.res.IEnv.cs"));
            Assert.Equal(expected, emitted.Content);
        }

        // ---- Types: resource constructor + static -------------------------

        private static string FindTypesResource2FixtureDir()
        {
            var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
            while (dir != null && !File.Exists(Path.Combine(dir.FullName, "WACS.sln")))
                dir = dir.Parent;
            if (dir == null) return string.Empty;
            return Path.Combine(dir.FullName, "Spec.Test", "components",
                                "fixtures", "types-resource2");
        }

        [Fact]
        public void EmitImportInterfaceFile_matches_reference_resource_constructor_static()
        {
            // Resource `counter` with:
            //   * `constructor(initial: u32)` — EntryPoint
            //     `[constructor]counter`, assigns to this.Handle.
            //   * `from-bytes: static func(data: u32) -> counter` —
            //     EntryPoint `[static]counter.from-bytes`, returns
            //     a fresh Counter constructed from the handle.
            //   * `get: func() -> u32` and `increment: func()` —
            //     standard instance methods.
            //
            // Exercises: constructor factory shape, static factory
            // with global:: qualified return, plus the existing
            // instance method pattern — all in one resource.
            var fixtureDir = FindTypesResource2FixtureDir();
            var src = File.ReadAllText(Path.Combine(fixtureDir, "wit", "res2.wit"));
            var pkgs = WitToTypes.Convert(WitParser.Parse(src));
            var iface = pkgs.Single().Interfaces.Single(i => i.Name == "env");

            var emitted = CSharpEmitter.EmitImportInterfaceFile(
                iface, "res2-world");

            var expected = File.ReadAllText(Path.Combine(
                fixtureDir, "reference",
                "Res2WorldWorld.wit.imports.local.res2.IEnv.cs"));
            Assert.Equal(expected, emitted.Content);
        }

        // ---- Cross-interface type references ------------------------------

        private static string FindCrossInterfaceFixtureDir()
        {
            var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
            while (dir != null && !File.Exists(Path.Combine(dir.FullName, "WACS.sln")))
                dir = dir.Parent;
            if (dir == null) return string.Empty;
            return Path.Combine(dir.FullName, "Spec.Test", "components",
                                "fixtures", "cross-interface");
        }

        [Fact]
        public void EmitExportInterfaceFile_qualifies_cross_interface_type_refs()
        {
            // WIT with two interfaces in the same file: `errors`
            // defines `kind`; `ops` uses `kind` in a function
            // signature via `use errors.{kind}`. wit-bindgen-csharp
            // emits the cross-interface reference as a fully
            // qualified `global::XfWorldWorld.wit.imports.local.xf
            // .IErrors.Kind` path — even though `errors` is not an
            // explicit import (it's implicitly imported via the
            // `use`).
            var fixtureDir = FindCrossInterfaceFixtureDir();
            var src = File.ReadAllText(Path.Combine(fixtureDir, "wit", "xface.wit"));
            var pkgs = WitToTypes.Convert(WitParser.Parse(src));
            WitResolver.Resolve(pkgs);
            var iface = pkgs.Single().Interfaces.Single(i => i.Name == "ops");

            var emitted = CSharpEmitter.EmitExportInterfaceFile(iface, "xf-world");

            var expected = File.ReadAllText(Path.Combine(
                fixtureDir, "reference",
                "XfWorldWorld.wit.exports.local.xf.IOps.cs"));
            Assert.Equal(expected, emitted.Content);
        }

        // ---- Interop: string-param marshaling -----------------------------

        private static string FindInteropStringParamFixtureDir()
        {
            var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
            while (dir != null && !File.Exists(Path.Combine(dir.FullName, "WACS.sln")))
                dir = dir.Parent;
            if (dir == null) return string.Empty;
            return Path.Combine(dir.FullName, "Spec.Test", "components",
                                "fixtures", "interop-string-param");
        }

        /// <summary>
        /// String param marshaling — diverges from wit-bindgen's
        /// local-variable naming by design. Public API + DllImport
        /// stub signatures match; wrapper body uses our clean
        /// <c>{paramName}Ptr</c> / <c>{paramName}Len</c> locals
        /// instead of wit-bindgen's <c>result</c> /
        /// <c>interopString</c> / <c>lengthresult</c> scheme.
        ///
        /// <para>Expected output is hand-written in the
        /// <c>expected/</c> directory (distinct from the
        /// wit-bindgen-pinned <c>reference/</c> used by primitive
        /// fixtures). Diff against the expected form locks down
        /// our emitter's shape.</para>
        /// </summary>
        [Fact]
        public void InteropEmit_string_params_marshals_via_InteropString()
        {
            var fixtureDir = FindInteropStringParamFixtureDir();
            var src = File.ReadAllText(Path.Combine(fixtureDir, "wit", "sp.wit"));
            var pkgs = WitToTypes.Convert(WitParser.Parse(src));
            var iface = pkgs.Single().Interfaces.Single(i => i.Name == "env");

            var content = InteropEmit.EmitImportInteropContent(iface, "sp-world");

            var expected = File.ReadAllText(Path.Combine(
                fixtureDir, "expected",
                "SpWorldWorld.wit.imports.local.sp.EnvInterop.cs"));
            Assert.Equal(expected, content);
        }

        // ---- Interop: string-return marshaling ----------------------------

        private static string FindInteropStringReturnFixtureDir()
        {
            var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
            while (dir != null && !File.Exists(Path.Combine(dir.FullName, "WACS.sln")))
                dir = dir.Parent;
            if (dir == null) return string.Empty;
            return Path.Combine(dir.FullName, "Spec.Test", "components",
                                "fixtures", "interop-string-return");
        }

        /// <summary>
        /// String return marshaling — via the return-area buffer.
        /// Stub signature changes: void return + trailing
        /// <c>nint</c> return-area pointer. Wrapper allocates
        /// <c>uint[2]</c>, fixes a pointer, calls the stub with
        /// the return-area <c>ptr</c>, then decodes
        /// <c>Encoding.UTF8.GetString(bytes, len)</c> from the
        /// ptr/len pair written at offsets 0 and 4.
        /// </summary>
        [Fact]
        public void InteropEmit_string_return_uses_return_area()
        {
            var fixtureDir = FindInteropStringReturnFixtureDir();
            var src = File.ReadAllText(Path.Combine(fixtureDir, "wit", "sr.wit"));
            var pkgs = WitToTypes.Convert(WitParser.Parse(src));
            var iface = pkgs.Single().Interfaces.Single(i => i.Name == "env");

            var content = InteropEmit.EmitImportInteropContent(iface, "sr-world");

            var expected = File.ReadAllText(Path.Combine(
                fixtureDir, "expected",
                "SrWorldWorld.wit.imports.local.sr.EnvInterop.cs"));
            Assert.Equal(expected, content);
        }

        // ---- Interop: list<u8> marshaling ---------------------------------

        private static string FindInteropListU8FixtureDir()
        {
            var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
            while (dir != null && !File.Exists(Path.Combine(dir.FullName, "WACS.sln")))
                dir = dir.Parent;
            if (dir == null) return string.Empty;
            return Path.Combine(dir.FullName, "Spec.Test", "components",
                                "fixtures", "interop-list-u8");
        }

        /// <summary>
        /// <c>list&lt;u8&gt;</c> — the byte-array special case.
        /// Params lower via <c>stackalloc byte[len]</c> +
        /// <c>AsSpan().CopyTo</c>; returns via the return-area
        /// buffer and <c>new byte[len]</c> + <c>Span.CopyTo</c>.
        /// Snapshot matches wit-bindgen 0.30.0 output byte-for-byte
        /// (the canonical ABI for list&lt;u8&gt; is (ptr, len) with
        /// no naming allocator we'd have to reverse-engineer).
        /// </summary>
        [Fact]
        public void InteropEmit_list_u8_matches_reference()
        {
            var fixtureDir = FindInteropListU8FixtureDir();
            var src = File.ReadAllText(Path.Combine(fixtureDir, "wit", "lst.wit"));
            var pkgs = WitToTypes.Convert(WitParser.Parse(src));
            var iface = pkgs.Single().Interfaces.Single(i => i.Name == "env");

            var content = InteropEmit.EmitImportInteropContent(iface, "lst-world");

            var expected = File.ReadAllText(Path.Combine(
                fixtureDir, "reference",
                "LstWorldWorld.wit.imports.local.lst.EnvInterop.cs"));
            Assert.Equal(expected, content);
        }

        // ---- Interop: list<u32> (non-byte list of primitives) -------------

        private static string FindInteropListU32FixtureDir()
        {
            var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
            while (dir != null && !File.Exists(Path.Combine(dir.FullName, "WACS.sln")))
                dir = dir.Parent;
            if (dir == null) return string.Empty;
            return Path.Combine(dir.FullName, "Spec.Test", "components",
                                "fixtures", "interop-list-u32");
        }

        /// <summary>
        /// <c>list&lt;u32&gt;</c> marshaling — the non-byte
        /// primitive-list case. Verifies the element-type
        /// parameterization: <c>stackalloc uint[…]</c> +
        /// <c>Span&lt;uint&gt;</c> instead of <c>Span&lt;byte&gt;</c>,
        /// and <c>new uint[…]</c> on the return path. The length
        /// word stays u32 regardless of element type.
        /// </summary>
        [Fact]
        public void InteropEmit_list_u32_matches_reference()
        {
            var fixtureDir = FindInteropListU32FixtureDir();
            var src = File.ReadAllText(Path.Combine(fixtureDir, "wit", "l32.wit"));
            var pkgs = WitToTypes.Convert(WitParser.Parse(src));
            var iface = pkgs.Single().Interfaces.Single(i => i.Name == "env");

            var content = InteropEmit.EmitImportInteropContent(iface, "l32-world");

            var expected = File.ReadAllText(Path.Combine(
                fixtureDir, "reference",
                "L32WorldWorld.wit.imports.local.l32.EnvInterop.cs"));
            Assert.Equal(expected, content);
        }

        // ---- Interop: option<string> marshaling --------------------------

        private static string FindInteropOptionStringFixtureDir()
        {
            var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
            while (dir != null && !File.Exists(Path.Combine(dir.FullName, "WACS.sln")))
                dir = dir.Parent;
            if (dir == null) return string.Empty;
            return Path.Combine(dir.FullName, "Spec.Test", "components",
                                "fixtures", "interop-option-string");
        }

        /// <summary>
        /// <c>option&lt;string&gt;</c> param + return. Stub takes
        /// (disc, ptr, len); return area is 3 uints (disc at 0,
        /// ptr at 4, len at 8). Param lowering emits
        /// <c>{arg}Tag</c> / <c>{arg}Ptr</c> / <c>{arg}Len</c>
        /// locals; the Some branch pins the UTF-8 GCHandle via
        /// <c>InteropString.FromString</c>. Return lifting switches
        /// on the discriminant and decodes with
        /// <c>Encoding.UTF8.GetString</c>. Param-side locals diverge
        /// from wit-bindgen's <c>lowered</c> / <c>lowered3</c> /
        /// <c>lowered4</c> shared-counter names (expected file
        /// rather than reference).
        /// </summary>
        [Fact]
        public void InteropEmit_option_string_matches_expected()
        {
            var fixtureDir = FindInteropOptionStringFixtureDir();
            var src = File.ReadAllText(Path.Combine(fixtureDir, "wit", "os.wit"));
            var pkgs = WitToTypes.Convert(WitParser.Parse(src));
            var iface = pkgs.Single().Interfaces.Single(i => i.Name == "env");

            var content = InteropEmit.EmitImportInteropContent(iface, "os-world");

            var expected = File.ReadAllText(Path.Combine(
                fixtureDir, "expected",
                "OsWorldWorld.wit.imports.local.os.EnvInterop.cs"));
            Assert.Equal(expected, content);
        }

        // ---- Interop: result<prim, prim> marshaling ----------------------

        private static string FindInteropResultPrimsFixtureDir()
        {
            var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
            while (dir != null && !File.Exists(Path.Combine(dir.FullName, "WACS.sln")))
                dir = dir.Parent;
            if (dir == null) return string.Empty;
            return Path.Combine(dir.FullName, "Spec.Test", "components",
                                "fixtures", "interop-result-prims");
        }

        /// <summary>
        /// <c>result&lt;prim, prim&gt;</c> return marshaling.
        /// Wrapper unwraps to the Ok type on success and throws
        /// <c>WitException</c> on failure. Return-area body builds
        /// a <c>Result&lt;Ok, Err&gt;</c> via <c>.ok(…)</c> /
        /// <c>.err(…)</c> factories in a discriminant switch,
        /// then branches on <c>IsOk</c>.
        /// </summary>
        [Fact]
        public void InteropEmit_result_prims_matches_reference()
        {
            var fixtureDir = FindInteropResultPrimsFixtureDir();
            var src = File.ReadAllText(Path.Combine(fixtureDir, "wit", "res.wit"));
            var pkgs = WitToTypes.Convert(WitParser.Parse(src));
            var iface = pkgs.Single().Interfaces.Single(i => i.Name == "env");

            var content = InteropEmit.EmitImportInteropContent(iface, "res-world");

            var expected = File.ReadAllText(Path.Combine(
                fixtureDir, "reference",
                "ResWorldWorld.wit.imports.local.res.EnvInterop.cs"));
            Assert.Equal(expected, content);
        }

        // ---- Interop: totally-elided result<_, _> -----------------------

        private static string FindInteropResultNoneFixtureDir()
        {
            var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
            while (dir != null && !File.Exists(Path.Combine(dir.FullName, "WACS.sln")))
                dir = dir.Parent;
            if (dir == null) return string.Empty;
            return Path.Combine(dir.FullName, "Spec.Test", "components",
                                "fixtures", "interop-result-none");
        }

        /// <summary>
        /// <c>result&lt;_, _&gt;</c> — the totally-elided case. No
        /// return area: stub returns the discriminant directly as
        /// i32. Wrapper captures the int, switches on the value
        /// (not a Span-byte read), builds <c>Result&lt;None, None&gt;</c>,
        /// and branches on <c>IsOk</c>: ok returns void
        /// (<c>return ;</c>), err throws <c>WitException</c>.
        /// </summary>
        [Fact]
        public void InteropEmit_result_none_matches_reference()
        {
            var fixtureDir = FindInteropResultNoneFixtureDir();
            var src = File.ReadAllText(Path.Combine(fixtureDir, "wit", "rn.wit"));
            var pkgs = WitToTypes.Convert(WitParser.Parse(src));
            var iface = pkgs.Single().Interfaces.Single(i => i.Name == "env");

            var content = InteropEmit.EmitImportInteropContent(iface, "rn-world");

            var expected = File.ReadAllText(Path.Combine(
                fixtureDir, "reference",
                "RnWorldWorld.wit.imports.local.rn.EnvInterop.cs"));
            Assert.Equal(expected, content);
        }

        // ---- Interop: result with elided sides ---------------------------

        private static string FindInteropResultElidedFixtureDir()
        {
            var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
            while (dir != null && !File.Exists(Path.Combine(dir.FullName, "WACS.sln")))
                dir = dir.Parent;
            if (dir == null) return string.Empty;
            return Path.Combine(dir.FullName, "Spec.Test", "components",
                                "fixtures", "interop-result-elided");
        }

        /// <summary>
        /// <c>result&lt;_, prim&gt;</c> (err-only) and
        /// <c>result&lt;prim, _&gt;</c> (ok-only) — the None side
        /// emits <c>new global::{WorldNs}.None()</c> inside the
        /// corresponding <c>.ok(…)</c> / <c>.err(…)</c> arm; the
        /// other arm lifts its payload normally. When Ok is None
        /// the wrapper returns <c>void</c>, emitting
        /// <c>return ;</c> (the wit-bindgen space-before-semi
        /// quirk) inside the <c>IsOk</c> branch.
        /// </summary>
        [Fact]
        public void InteropEmit_result_elided_matches_reference()
        {
            var fixtureDir = FindInteropResultElidedFixtureDir();
            var src = File.ReadAllText(Path.Combine(fixtureDir, "wit", "re.wit"));
            var pkgs = WitToTypes.Convert(WitParser.Parse(src));
            var iface = pkgs.Single().Interfaces.Single(i => i.Name == "env");

            var content = InteropEmit.EmitImportInteropContent(iface, "re-world");

            var expected = File.ReadAllText(Path.Combine(
                fixtureDir, "reference",
                "ReWorldWorld.wit.imports.local.re.EnvInterop.cs"));
            Assert.Equal(expected, content);
        }

        // ---- Interop: tuple<prim, …> marshaling ---------------------------

        private static string FindInteropTuplePrimsFixtureDir()
        {
            var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
            while (dir != null && !File.Exists(Path.Combine(dir.FullName, "WACS.sln")))
                dir = dir.Parent;
            if (dir == null) return string.Empty;
            return Path.Combine(dir.FullName, "Spec.Test", "components",
                                "fixtures", "interop-tuple-prims");
        }

        /// <summary>
        /// <c>tuple&lt;prim, prim, …&gt;</c> param + return. Params
        /// flatten inline — stub takes one arg per element; wrapper
        /// passes <c>p.Item1</c>, <c>p.Item2</c>, … after the
        /// usual primitive lower. Returns via return-area (one
        /// word per element) — wrapper emits
        /// <c>return (lift(+0), lift(+4), …);</c> with the closing
        /// <c>)</c> on its own line (a wit-bindgen 0.30.0 formatting
        /// quirk we match byte-for-byte).
        ///
        /// <para>Scoped to small primitives only (every element
        /// must fit in one core-wasm word). 64-bit and aggregate
        /// elements need alignment-aware stride handling.</para>
        /// </summary>
        [Fact]
        public void InteropEmit_tuple_prims_matches_reference()
        {
            var fixtureDir = FindInteropTuplePrimsFixtureDir();
            var src = File.ReadAllText(Path.Combine(fixtureDir, "wit", "tup.wit"));
            var pkgs = WitToTypes.Convert(WitParser.Parse(src));
            var iface = pkgs.Single().Interfaces.Single(i => i.Name == "env");

            var content = InteropEmit.EmitImportInteropContent(iface, "tup-world");

            var expected = File.ReadAllText(Path.Combine(
                fixtureDir, "reference",
                "TupWorldWorld.wit.imports.local.tup.EnvInterop.cs"));
            Assert.Equal(expected, content);
        }

        // ---- Interop: option<primitive> marshaling -----------------------

        private static string FindInteropOptionU32FixtureDir()
        {
            var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
            while (dir != null && !File.Exists(Path.Combine(dir.FullName, "WACS.sln")))
                dir = dir.Parent;
            if (dir == null) return string.Empty;
            return Path.Combine(dir.FullName, "Spec.Test", "components",
                                "fixtures", "interop-option-u32");
        }

        /// <summary>
        /// <c>option&lt;u32&gt;</c> parameter and return marshaling.
        /// Param lowers to a <c>(discriminant, payload)</c> pair —
        /// the wrapper emits a null-check that sets locals
        /// <c>{arg}Tag</c> / <c>{arg}Val</c>; the stub takes
        /// <c>(int, int)</c>. Return uses the return-area buffer —
        /// discriminant at byte offset 0, payload at byte offset 4,
        /// both u32-slotted. Wrapper switches on the discriminant
        /// and lifts <c>null</c> or the payload cast appropriately.
        ///
        /// <para>Param-side local naming diverges from wit-bindgen
        /// (which allocates shared-counter names like
        /// <c>lowered</c> / <c>lowered3</c>); we use per-arg
        /// naming. Return-side body matches wit-bindgen 0.30.0
        /// byte-for-byte. Expected output is hand-written (via
        /// <c>expected/</c>) to capture the divergence; the
        /// <c>reference/</c> file preserves the wit-bindgen
        /// original for diff-tracking against upstream.</para>
        /// </summary>
        [Fact]
        public void InteropEmit_option_u32_matches_expected()
        {
            var fixtureDir = FindInteropOptionU32FixtureDir();
            var src = File.ReadAllText(Path.Combine(fixtureDir, "wit", "opt.wit"));
            var pkgs = WitToTypes.Convert(WitParser.Parse(src));
            var iface = pkgs.Single().Interfaces.Single(i => i.Name == "env");

            var content = InteropEmit.EmitImportInteropContent(iface, "opt-world");

            var expected = File.ReadAllText(Path.Combine(
                fixtureDir, "expected",
                "OptWorldWorld.wit.imports.local.opt.EnvInterop.cs"));
            Assert.Equal(expected, content);
        }

        // ---- Interop: primitive-only import Interop file ------------------

        private static string FindInteropPrimitivesFixtureDir()
        {
            var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
            while (dir != null && !File.Exists(Path.Combine(dir.FullName, "WACS.sln")))
                dir = dir.Parent;
            if (dir == null) return string.Empty;
            return Path.Combine(dir.FullName, "Spec.Test", "components",
                                "fixtures", "interop-primitives");
        }

        [Fact]
        public void InteropEmit_matches_reference_EnvInterop_primitives()
        {
            var fixtureDir = FindInteropPrimitivesFixtureDir();
            var src = File.ReadAllText(Path.Combine(fixtureDir, "wit", "iop.wit"));
            var pkgs = WitToTypes.Convert(WitParser.Parse(src));
            var iface = pkgs.Single().Interfaces.Single(i => i.Name == "env");

            var content = InteropEmit.EmitImportInteropContent(iface, "iop-world");

            var expected = File.ReadAllText(Path.Combine(
                fixtureDir, "reference",
                "IopWorldWorld.wit.imports.local.iop.EnvInterop.cs"));
            Assert.Equal(expected, content);
        }

        /// <summary>
        /// Coverage for the remaining primitive lift/lower shapes —
        /// s8/s16 narrowing casts, bool ternary+compare, char's
        /// asymmetric plain-cast lower, u64 unchecked cast, f32
        /// direct.
        /// </summary>
        [Fact]
        public void InteropEmit_matches_reference_OpsInterop_edge_primitives()
        {
            var fixtureDir = FindInteropPrimitivesFixtureDir();
            var src = File.ReadAllText(Path.Combine(fixtureDir, "wit", "iop2.wit"));
            var pkgs = WitToTypes.Convert(WitParser.Parse(src));
            var iface = pkgs.Single().Interfaces.Single(i => i.Name == "ops");

            var content = InteropEmit.EmitImportInteropContent(iface, "iop2-world");

            var expected = File.ReadAllText(Path.Combine(
                fixtureDir, "reference",
                "Iop2WorldWorld.wit.imports.local.iop2.OpsInterop.cs"));
            Assert.Equal(expected, content);
        }

        // ---- Trampolines: primitive-only export trampolines ---------------

        private static string FindTrampolinesPrimitivesFixtureDir()
        {
            var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
            while (dir != null && !File.Exists(Path.Combine(dir.FullName, "WACS.sln")))
                dir = dir.Parent;
            if (dir == null) return string.Empty;
            return Path.Combine(dir.FullName, "Spec.Test", "components",
                                "fixtures", "trampolines-primitives");
        }

        [Fact]
        public void TrampolineEmit_matches_reference_OpsInterop_add_square_ping()
        {
            var fixtureDir = FindTrampolinesPrimitivesFixtureDir();
            var src = File.ReadAllText(Path.Combine(fixtureDir, "wit", "tramp.wit"));
            var pkgs = WitToTypes.Convert(WitParser.Parse(src));
            var iface = pkgs.Single().Interfaces.Single(i => i.Name == "ops");

            var content = TrampolineEmit.EmitExportTrampolineContent(
                iface, "tramp-world");

            var expected = File.ReadAllText(Path.Combine(
                fixtureDir, "reference",
                "TrampWorldWorld.wit.exports.local.tramp.OpsInterop.cs"));
            Assert.Equal(expected, content);
        }

        /// <summary>
        /// Edge-primitive trampolines: bool (ternary lower,
        /// compare lift), signed narrowing (s8), char asymmetry
        /// (unchecked lift, plain-cast lower), u64 (unchecked
        /// both ways).
        /// </summary>
        [Fact]
        public void TrampolineEmit_matches_reference_OpsInterop_edge_primitives()
        {
            var fixtureDir = FindTrampolinesPrimitivesFixtureDir();
            var src = File.ReadAllText(Path.Combine(fixtureDir, "wit", "tramp2.wit"));
            var pkgs = WitToTypes.Convert(WitParser.Parse(src));
            var iface = pkgs.Single().Interfaces.Single(i => i.Name == "ops");

            var content = TrampolineEmit.EmitExportTrampolineContent(
                iface, "tramp2-world");

            var expected = File.ReadAllText(Path.Combine(
                fixtureDir, "reference",
                "Tramp2WorldWorld.wit.exports.local.tramp2.OpsInterop.cs"));
            Assert.Equal(expected, content);
        }

        // ---- Helpers: conditional Option<T> / InteropString ---------------

        /// <summary>
        /// Helper emission is conditional on the world's signatures
        /// actually using <c>option</c> / <c>string</c>. A world
        /// that uses neither (like hello-world, where imports are
        /// unresolved CtExternInterfaceRefs) emits neither helper
        /// — which is what our existing Hello.cs snapshot already
        /// asserts bit-for-bit.
        /// </summary>
        [Fact]
        public void World_shell_omits_helpers_for_primitive_only_world()
        {
            var src = @"
                package local:prim;
                world app {
                    export run: func() -> u32;
                }";
            var pkgs = WitToTypes.Convert(WitParser.Parse(src));
            var world = pkgs.Single().Worlds.Single();
            var shell = CSharpEmitter.EmitWorldShellFile(
                world, new EmitOptions());

            Assert.DoesNotContain("public class Option<T>", shell.Content);
            Assert.DoesNotContain("InteropString", shell.Content);
        }

        [Fact]
        public void World_shell_emits_Option_when_world_uses_option()
        {
            var src = @"
                package local:opt;
                world app {
                    export get: func() -> option<u32>;
                }";
            var pkgs = WitToTypes.Convert(WitParser.Parse(src));
            var world = pkgs.Single().Worlds.Single();
            var shell = CSharpEmitter.EmitWorldShellFile(
                world, new EmitOptions());

            Assert.Contains("public class Option<T>", shell.Content);
            Assert.DoesNotContain("InteropString", shell.Content);
        }

        [Fact]
        public void World_shell_emits_InteropString_when_world_uses_string()
        {
            var src = @"
                package local:str;
                world app {
                    export greet: func(name: string);
                }";
            var pkgs = WitToTypes.Convert(WitParser.Parse(src));
            var world = pkgs.Single().Worlds.Single();
            var shell = CSharpEmitter.EmitWorldShellFile(
                world, new EmitOptions());

            Assert.Contains("public static class InteropString", shell.Content);
            Assert.DoesNotContain("public class Option<T>", shell.Content);
        }

        [Fact]
        public void World_shell_emits_both_helpers_when_both_used()
        {
            var src = @"
                package local:both;
                world app {
                    export get: func() -> option<string>;
                }";
            var pkgs = WitToTypes.Convert(WitParser.Parse(src));
            var world = pkgs.Single().Worlds.Single();
            var shell = CSharpEmitter.EmitWorldShellFile(
                world, new EmitOptions());

            Assert.Contains("public class Option<T>", shell.Content);
            Assert.Contains("public static class InteropString", shell.Content);
        }

        [Fact]
        public void TypeUsageScan_follows_resolved_external_interface_refs()
        {
            // A world that imports an interface using `option`
            // should report UsesOption=true once resolution binds
            // the ref target. Pre-resolution, the ref target is
            // null and scan is conservative (returns false).
            var providerSrc = @"
                package local:provider;
                interface opts { get: func() -> option<u32>; }";
            var consumerSrc = @"
                package local:consumer;
                world app { import local:provider/opts; }";
            var packages = new System.Collections.Generic.List<CtPackage>();
            packages.AddRange(WitToTypes.Convert(WitParser.Parse(providerSrc)));
            packages.AddRange(WitToTypes.Convert(WitParser.Parse(consumerSrc)));

            var world = packages.First(p => p.Name.Path.Single() == "consumer")
                                .Worlds.Single();

            // Pre-resolution: scan misses the imported interface.
            Assert.False(TypeUsageScan.UsesOption(world));

            WitResolver.Resolve(packages);

            // Post-resolution: target bound, scan walks into it.
            Assert.True(TypeUsageScan.UsesOption(world));
        }

        // ---- End-to-end: parse + resolve + emit ---------------------------

        /// <summary>
        /// The full contract roundtrip: parse <c>hello.wit</c> and
        /// wasi-cli's <c>run.wit</c> from the submodule, resolve
        /// cross-file refs, then <c>EmitWorld</c> and assert
        /// <c>IRun.cs</c> matches the pinned wit-bindgen-csharp 0.30.0
        /// reference. This is the emitter gate for Phase 1a.2: when
        /// it passes, we know a user can go from WIT source to
        /// wit-bindgen-shape C# without any hand-crafted Types.
        /// </summary>
        [Fact]
        public void EmitWorld_from_hello_wit_produces_RunInterop_matching_reference()
        {
            // Full export trampoline for wasi:cli/run — exercises
            // the result<_, _> elision rule: interface sees void,
            // stub returns int discriminant via try/catch/switch.
            var root = FindFixturesDir();
            var helloWit = File.ReadAllText(Path.Combine(root, "wit", "hello.wit"));
            var submoduleRoot = new DirectoryInfo(root).Parent!.Parent!.FullName;
            var runWit = File.ReadAllText(Path.Combine(
                submoduleRoot, "wasi-cli", "wit", "run.wit"));

            var packages = new System.Collections.Generic.List<CtPackage>();
            packages.AddRange(WitToTypes.Convert(WitParser.Parse(helloWit)));
            packages.AddRange(WitToTypes.Convert(WitParser.Parse(
                "package wasi:cli@0.2.3;\n" + runWit)));
            WitResolver.Resolve(packages);

            var world = packages.First(p => p.Name.Namespace == "local"
                && p.Name.Path.Single() == "hello").Worlds.Single();
            var sources = CSharpEmitter.EmitWorld(world);
            var runInterop = sources.Single(s => s.FileName ==
                "HelloWorld.wit.exports.wasi.cli.v0_2_3.RunInterop.cs");

            var expected = LoadReference(
                "HelloWorld.wit.exports.wasi.cli.v0_2_3.RunInterop.cs");
            Assert.Equal(expected, runInterop.Content);
        }

        [Fact]
        public void EmitWorld_from_hello_wit_produces_IRun_matching_reference()
        {
            var root = FindFixturesDir();
            var helloWit = File.ReadAllText(
                Path.Combine(root, "wit", "hello.wit"));

            var submoduleRoot = new DirectoryInfo(root).Parent!.Parent!.FullName;
            var runWit = File.ReadAllText(
                Path.Combine(submoduleRoot, "wasi-cli", "wit", "run.wit"));

            var packages = new System.Collections.Generic.List<CtPackage>();
            packages.AddRange(WitToTypes.Convert(WitParser.Parse(helloWit)));
            packages.AddRange(WitToTypes.Convert(WitParser.Parse(
                "package wasi:cli@0.2.3;\n" + runWit)));

            WitResolver.Resolve(packages);

            var helloPkg = packages.First(p => p.Name.Namespace == "local"
                && p.Name.Path.Single() == "hello");
            var world = helloPkg.Worlds.Single();

            var sources = CSharpEmitter.EmitWorld(world);
            var irunFile = sources.SingleOrDefault(s =>
                s.FileName == "HelloWorld.wit.exports.wasi.cli.v0_2_3.IRun.cs");
            Assert.NotNull(irunFile);

            var expected = LoadReference(
                "HelloWorld.wit.exports.wasi.cli.v0_2_3.IRun.cs");
            Assert.Equal(expected, irunFile!.Content);
        }
    }
}
