// Copyright 2026 Kelvin Nishikawa
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.

using System;

namespace Wacs.ComponentModel
{
    /// <summary>
    /// Carries the original kebab-case WIT name for a C# type or
    /// member that was generated by <c>Wacs.ComponentModel.CSharpEmit</c>.
    /// Lets consumers reflect on a generated assembly and recover
    /// the WIT-level identifier — essential for:
    /// <list type="bullet">
    /// <item><description>Round-tripping a WACS-transpiled <c>.dll</c>
    /// back through <c>componentize-dotnet</c>: the tool uses the
    /// original name to emit correct Component Model import/export
    /// entry points.</description></item>
    /// <item><description>Host-side binding surface discovery:
    /// <c>BindComponentInterface&lt;T&gt;</c> can resolve the C#
    /// method to a WIT function name without parsing the
    /// originating WIT.</description></item>
    /// <item><description>Reverse C# → WIT bindgen tooling: extract
    /// WIT text from a transpiled assembly.</description></item>
    /// </list>
    ///
    /// <para>Emission is gated on
    /// <see cref="CSharpEmit.EmitOptions.IncludeWitMetadata"/>,
    /// off by default for byte-for-byte parity with
    /// <c>wit-bindgen-csharp</c> output. Turn on for WACS-native
    /// artifacts that want the metadata baked in.</para>
    /// </summary>
    [AttributeUsage(
        AttributeTargets.Class |
        AttributeTargets.Struct |
        AttributeTargets.Interface |
        AttributeTargets.Enum |
        AttributeTargets.Method |
        AttributeTargets.Field |
        AttributeTargets.Property |
        AttributeTargets.Parameter,
        Inherited = false,
        AllowMultiple = false)]
    public sealed class WitNameAttribute : Attribute
    {
        /// <summary>The original kebab-case WIT identifier.</summary>
        public string Name { get; }

        public WitNameAttribute(string name) { Name = name; }
    }
}
