// Generated by `wit-bindgen` 0.30.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace TypWorldWorld.wit.exports.local.typ;

public interface IDef {

    public enum Color {
        RED, GREEN, BLUE
    }

    public enum Status {
        OK, WARN, ERR
    }

    public enum Perm : byte {
        READ = 1 << 0,
        WRITE = 1 << 1,
        EXECUTE = 1 << 2,
    }

    public enum Level : byte {
        DEBUG = 1 << 0,
        INFO = 1 << 1,
        WARN = 1 << 2,
        ERROR = 1 << 3,
        FATAL = 1 << 4,
    }
    static abstract Color Pick(Color c);

    static abstract Perm Check(Perm p);

}
