// Generated by `wit-bindgen` 0.30.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace RlWorldWorld.wit.imports.local.rl;

public interface IEnv {

    public class Buffer: IDisposable {
        internal int Handle { get; set; }

        public readonly record struct THandle(int Handle);

        public Buffer(THandle handle) {
            Handle = handle.Handle;
        }

        public void Dispose() {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        [DllImport("local:rl/env", EntryPoint = "[resource-drop]buffer"), WasmImportLinkage]
        private static extern void wasmImportResourceDrop(int p0);

        protected virtual void Dispose(bool disposing) {
            if (Handle != 0) {
                wasmImportResourceDrop(Handle);
                Handle = 0;
            }
        }

        ~Buffer() {
            Dispose(false);
        }

        internal static class ConstructorWasmInterop
        {
            [DllImport("local:rl/env", EntryPoint = "[constructor]buffer"), WasmImportLinkage]
            internal static extern int wasmImportConstructor();

        }

        public   unsafe  Buffer()
        {
            var result =  ConstructorWasmInterop.wasmImportConstructor();
            this.Handle = result;

            //TODO: free alloc handle (interopString) if exists
        }

        internal static class AppendWasmInterop
        {
            [DllImport("local:rl/env", EntryPoint = "[method]buffer.append"), WasmImportLinkage]
            internal static extern void wasmImportAppend(int p0, nint p1, int p2);

        }

        public   unsafe void Append(byte[] data)
        {
            var handle = this.Handle;

            void* buffer = stackalloc byte[(data).Length];
            data.AsSpan<byte>().CopyTo(new Span<byte>(buffer, data.Length));
            AppendWasmInterop.wasmImportAppend(handle, (int)buffer, (data).Length);

            //TODO: free alloc handle (interopString) if exists
        }

        internal static class TakeWasmInterop
        {
            [DllImport("local:rl/env", EntryPoint = "[method]buffer.take"), WasmImportLinkage]
            internal static extern void wasmImportTake(int p0, nint p1);

        }

        public   unsafe byte[] Take()
        {
            var handle = this.Handle;

            var retArea = new uint[2];
            fixed (uint* retAreaByte0 = &retArea[0])
            {
                var ptr = (nint)retAreaByte0;
                TakeWasmInterop.wasmImportTake(handle, ptr);

                var array = new byte[BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4))];
                new Span<byte>((void*)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 0), 4))), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4))).CopyTo(new Span<byte>(array));
                return array;
            }

            //TODO: free alloc handle (interopString) if exists
        }

    }

}
