// Generated by `wit-bindgen` 0.30.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace Iop2WorldWorld.wit.imports.local.iop2
{
    public static class OpsInterop {

        internal static class TakeS8WasmInterop
        {
            [DllImport("local:iop2/ops", EntryPoint = "take-s8"), WasmImportLinkage]
            internal static extern int wasmImportTakeS8(int p0);

        }

        public  static unsafe sbyte TakeS8(sbyte x)
        {
            var result =  TakeS8WasmInterop.wasmImportTakeS8(x);
            return ((sbyte)result);

            //TODO: free alloc handle (interopString) if exists
        }

        internal static class TakeS16WasmInterop
        {
            [DllImport("local:iop2/ops", EntryPoint = "take-s16"), WasmImportLinkage]
            internal static extern int wasmImportTakeS16(int p0);

        }

        public  static unsafe short TakeS16(short x)
        {
            var result =  TakeS16WasmInterop.wasmImportTakeS16(x);
            return ((short)result);

            //TODO: free alloc handle (interopString) if exists
        }

        internal static class TakeBoolWasmInterop
        {
            [DllImport("local:iop2/ops", EntryPoint = "take-bool"), WasmImportLinkage]
            internal static extern int wasmImportTakeBool(int p0);

        }

        public  static unsafe bool TakeBool(bool x)
        {
            var result =  TakeBoolWasmInterop.wasmImportTakeBool((x ? 1 : 0));
            return (result != 0);

            //TODO: free alloc handle (interopString) if exists
        }

        internal static class TakeCharWasmInterop
        {
            [DllImport("local:iop2/ops", EntryPoint = "take-char"), WasmImportLinkage]
            internal static extern int wasmImportTakeChar(int p0);

        }

        public  static unsafe uint TakeChar(uint x)
        {
            var result =  TakeCharWasmInterop.wasmImportTakeChar(((int)x));
            return unchecked((uint)(result));

            //TODO: free alloc handle (interopString) if exists
        }

        internal static class TakeU64WasmInterop
        {
            [DllImport("local:iop2/ops", EntryPoint = "take-u64"), WasmImportLinkage]
            internal static extern long wasmImportTakeU64(long p0);

        }

        public  static unsafe ulong TakeU64(ulong x)
        {
            var result =  TakeU64WasmInterop.wasmImportTakeU64(unchecked((long)(x)));
            return unchecked((ulong)(result));

            //TODO: free alloc handle (interopString) if exists
        }

        internal static class TakeF32WasmInterop
        {
            [DllImport("local:iop2/ops", EntryPoint = "take-f32"), WasmImportLinkage]
            internal static extern float wasmImportTakeF32(float p0);

        }

        public  static unsafe float TakeF32(float x)
        {
            var result =  TakeF32WasmInterop.wasmImportTakeF32(x);
            return result;

            //TODO: free alloc handle (interopString) if exists
        }

    }
}
