// Generated by `wit-bindgen` 0.30.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace IopWorldWorld.wit.imports.local.iop
{
    public static class EnvInterop {

        internal static class GetPidWasmInterop
        {
            [DllImport("local:iop/env", EntryPoint = "get-pid"), WasmImportLinkage]
            internal static extern int wasmImportGetPid();

        }

        public  static unsafe uint GetPid()
        {
            var result =  GetPidWasmInterop.wasmImportGetPid();
            return unchecked((uint)(result));

            //TODO: free alloc handle (interopString) if exists
        }

        internal static class SetLevelWasmInterop
        {
            [DllImport("local:iop/env", EntryPoint = "set-level"), WasmImportLinkage]
            internal static extern void wasmImportSetLevel(int p0);

        }

        public  static unsafe void SetLevel(byte level)
        {
            SetLevelWasmInterop.wasmImportSetLevel(level);

            //TODO: free alloc handle (interopString) if exists
        }

        internal static class AddWasmInterop
        {
            [DllImport("local:iop/env", EntryPoint = "add"), WasmImportLinkage]
            internal static extern int wasmImportAdd(int p0, int p1);

        }

        public  static unsafe uint Add(uint a, uint b)
        {
            var result =  AddWasmInterop.wasmImportAdd(unchecked((int)(a)), unchecked((int)(b)));
            return unchecked((uint)(result));

            //TODO: free alloc handle (interopString) if exists
        }

        internal static class NoopWasmInterop
        {
            [DllImport("local:iop/env", EntryPoint = "noop"), WasmImportLinkage]
            internal static extern void wasmImportNoop();

        }

        public  static unsafe void Noop()
        {
            NoopWasmInterop.wasmImportNoop();

            //TODO: free alloc handle (interopString) if exists
        }

    }
}
