// Generated by `wit-bindgen` 0.30.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace XfWorldWorld.wit.exports.local.xf;

public interface IOps {
    static abstract bool Check(global::XfWorldWorld.wit.imports.local.xf.IErrors.Kind k);

}
