// Generated by `wit-bindgen` 0.30.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace OsWorldWorld.wit.imports.local.os
{
    public static class EnvInterop {

        internal static class MaybeNameWasmInterop
        {
            [DllImport("local:os/env", EntryPoint = "maybe-name"), WasmImportLinkage]
            internal static extern void wasmImportMaybeName(nint p0);

        }

        public  static unsafe string? MaybeName()
        {

            var retArea = new uint[3];
            fixed (uint* retAreaByte0 = &retArea[0])
            {
                var ptr = (nint)retAreaByte0;
                MaybeNameWasmInterop.wasmImportMaybeName(ptr);

                string? lifted;

                switch (new Span<byte>((void*)(ptr + 0), 1)[0]) {
                    case 0: {
                        lifted = null;
                        break;
                    }

                    case 1: {

                        lifted = Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 8), 4)));
                        break;
                    }

                    default: throw new ArgumentException("invalid discriminant: " + (new Span<byte>((void*)(ptr + 0), 1)[0]));
                }
                return lifted;
            }

            //TODO: free alloc handle (interopString) if exists
        }

        internal static class TakeNameWasmInterop
        {
            [DllImport("local:os/env", EntryPoint = "take-name"), WasmImportLinkage]
            internal static extern void wasmImportTakeName(int p0, nint p1, int p2);

        }

        public  static unsafe void TakeName(string? n)
        {

            int lowered;
            nint lowered3;
            int lowered4;

            if (n != null) {
                var payload2 = (string) n;

                var result = payload2;
                IntPtr interopString = InteropString.FromString(result, out int lengthresult);

                lowered = 1;
                lowered3 = interopString.ToInt32();
                lowered4 = lengthresult;

            } else {

                lowered = 0;
                lowered3 = 0;
                lowered4 = 0;

            }
            TakeNameWasmInterop.wasmImportTakeName(lowered, lowered3, lowered4);

            //TODO: free alloc handle (interopString) if exists
        }

    }
}
