// Generated by `wit-bindgen` 0.30.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace AlWorldWorld.wit.imports.local.al;

public interface IEnv {

    public class Entry {
        public readonly uint id;
        public readonly string label;

        public Entry(uint id, string label) {
            this.id = id;
            this.label = label;
        }
    }

}
