// Copyright 2026 Kelvin Nishikawa
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Wacs.Compilation
{
    /// <summary>
    /// Source generator for the monolithic-switch WebAssembly interpreter.
    ///
    /// <para>Each method marked <c>[OpSource]</c> (stack-only numeric op) or <c>[OpHandler]</c>
    /// (any op including those with immediates or control-flow side effects) contributes a
    /// <c>case</c> to the generated <c>GeneratedDispatcher.Run</c> method. Inside that case
    /// we emit — inline, no wrappers:</para>
    /// <list type="number">
    ///   <item>Immediate reads from the annotated bytecode stream (one <c>StreamReader.ReadX</c>
    ///         call per <c>[Imm]</c> parameter, in declaration order; advances <c>pc</c>).</item>
    ///   <item>Stack pops into named locals matching the parameter names (reverse param order,
    ///         direct <c>ctx.OpStack.PopX()</c> calls — the handler body can reference them
    ///         by the same names it declared).</item>
    ///   <item>The handler body, with <c>return &lt;expr&gt;;</c> rewritten to <c>{ __r = &lt;expr&gt;;
    ///         goto __end_N; }</c> for non-void handlers, and <c>return;</c> rewritten to
    ///         <c>goto __end_N;</c> for void handlers.</item>
    ///   <item>A per-case label <c>__end_N:</c> followed by the result push (non-void only)
    ///         and <c>continue;</c> to return to the dispatch loop.</item>
    /// </list>
    /// <para>Rationale: every layer of function call — even an inlined <c>static __Op(...)</c>
    /// local function — demands a call frame in the IL and is IL the polymorphic dispatcher
    /// doesn't emit. The whole point of source-generating this dispatcher is to emit ONLY
    /// the instruction's semantics and nothing else.</para>
    ///
    /// <para>Dispatch structure: a single <c>while (pc &lt; code.Length)</c> loop at the top of
    /// <c>Run</c>, one <c>switch</c> on the primary byte, primary-only opcodes inlined in
    /// that switch. The five prefix opcodes (<c>0xFB..0xFF</c>) delegate to per-prefix
    /// sub-methods (<c>DispatchFB</c>, <c>DispatchFC</c>, ...) — they handle a single op and
    /// return. The benchmark-hot primaries stay in a single frame; SIMD/GC/atomics pay a
    /// call per op, which is tolerable since they aren't the hot path.</para>
    ///
    /// <para>AOT-safe: all introspection (attribute lookup, parameter classification) happens
    /// in the generator at build time. The emitted code uses no reflection, emit, or late
    /// binding. Roslyn lowers it to plain IL like any other C#.</para>
    /// </summary>
    [Generator]
    public class DispatchGenerator : IIncrementalGenerator
    {
        private const string OpSourceAttrFullName  = "Wacs.Core.Compilation.OpSourceAttribute";
        private const string OpHandlerAttrFullName = "Wacs.Core.Compilation.OpHandlerAttribute";
        private const string ImmAttrFullName       = "Wacs.Core.Compilation.ImmAttribute";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var entries = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => IsCandidateMethod(node),
                    transform: static (ctx, ct) => Extract(ctx, ct))
                .Where(static e => e != null)
                .Collect();

            context.RegisterSourceOutput(entries, (spc, items) =>
            {
                try
                {
                    Emit(spc, items);
                }
                catch (System.Exception ex)
                {
                    spc.AddSource("GeneratedDispatcher.Error.g.cs",
                        SourceText.From(
                            "// <auto-generated/>\n// DispatchGenerator threw:\n// " +
                            ex.GetType().FullName + ": " + ex.Message.Replace("\n", " ") + "\n" +
                            "// Stack:\n// " + (ex.StackTrace ?? "").Replace("\n", "\n// ") + "\n",
                            Encoding.UTF8));
                }
            });
        }

        private static bool IsCandidateMethod(SyntaxNode node)
        {
            if (node is not MethodDeclarationSyntax m) return false;
            if (m.AttributeLists.Count == 0) return false;
            foreach (var list in m.AttributeLists)
                foreach (var attr in list.Attributes)
                {
                    var name = attr.Name.ToString();
                    if (name.Contains("OpSource") || name.Contains("OpHandler"))
                        return true;
                }
            return false;
        }

        private static DispatchEntry Extract(GeneratorSyntaxContext ctx, CancellationToken ct)
        {
            var method = (MethodDeclarationSyntax)ctx.Node;
            var symbol = ctx.SemanticModel.GetDeclaredSymbol(method, ct) as IMethodSymbol;
            if (symbol == null) return null;

            AttributeData opAttr = null;
            bool isHandler = false;
            foreach (var a in symbol.GetAttributes())
            {
                var full = a.AttributeClass?.ToDisplayString();
                if (full == OpSourceAttrFullName)  { opAttr = a; isHandler = false; break; }
                if (full == OpHandlerAttrFullName) { opAttr = a; isHandler = true;  break; }
            }
            if (opAttr == null) return null;
            if (opAttr.ConstructorArguments.Length != 1) return null;

            var arg = opAttr.ConstructorArguments[0];
            if (arg.Kind != TypedConstantKind.Enum || arg.Type == null || arg.Value == null) return null;

            int rawValue = System.Convert.ToInt32(arg.Value);
            string enumTypeName = arg.Type.Name;
            string enumName = arg.Type.ToDisplayString();
            string enumMember = arg.Type.GetMembers()
                .OfType<IFieldSymbol>()
                .FirstOrDefault(f => f.HasConstantValue && System.Convert.ToInt32(f.ConstantValue) == rawValue)?.Name
                ?? rawValue.ToString();

            var parameters = ImmutableArray.CreateBuilder<ParamInfo>(symbol.Parameters.Length);
            foreach (var p in symbol.Parameters)
            {
                parameters.Add(ClassifyParam(p, isHandler));
            }

            string returnType = symbol.ReturnType.SpecialType == SpecialType.System_Void
                ? "void"
                : symbol.ReturnType.ToDisplayString();

            // Body text: for expression-bodied methods we keep just the expression; for
            // block bodies we keep the raw { ... } text. Both go through the same return-
            // rewriter at emit time.
            string bodyText;
            bool bodyIsExpression;
            if (method.ExpressionBody != null)
            {
                bodyText = method.ExpressionBody.Expression.ToFullString().Trim();
                bodyIsExpression = true;
            }
            else if (method.Body != null)
            {
                bodyText = method.Body.ToFullString();
                bodyIsExpression = false;
            }
            else
            {
                return null;
            }

            return new DispatchEntry(enumTypeName, rawValue, symbol.Name, enumName, enumMember,
                                     parameters.ToImmutable(), returnType, bodyText, bodyIsExpression,
                                     isHandler);
        }

        private static ParamInfo ClassifyParam(IParameterSymbol p, bool isHandler)
        {
            string type = p.Type.ToDisplayString();
            if (isHandler && p.RefKind == RefKind.Ref && p.Type.SpecialType == SpecialType.System_Int32 && p.Name == "pc")
                return new ParamInfo(p.Name, type, ParamKind.RefPc);
            if (isHandler && type == "Wacs.Core.Runtime.ExecContext")
                return new ParamInfo(p.Name, type, ParamKind.Ctx);
            if (isHandler && type == "System.ReadOnlySpan<byte>")
                return new ParamInfo(p.Name, type, ParamKind.Code);
            if (isHandler)
            {
                foreach (var a in p.GetAttributes())
                {
                    if (a.AttributeClass?.ToDisplayString() == ImmAttrFullName)
                        return new ParamInfo(p.Name, type, ParamKind.Immediate);
                }
            }
            return new ParamInfo(p.Name, type, ParamKind.Stack);
        }

        private static void Emit(SourceProductionContext spc, ImmutableArray<DispatchEntry> entries)
        {
            // Dedup by (enum, value) — if a handler is declared twice with the same key,
            // keep the first. Primary ops and prefix ops can collide on rawValue but not
            // on enum type, so the dedup key is the pair.
            var deduped = new Dictionary<string, DispatchEntry>();
            foreach (var e in entries)
            {
                if (e == null) continue;
                var key = e.EnumTypeName + ":" + e.RawValue;
                if (!deduped.ContainsKey(key)) deduped[key] = e;
            }
            var ordered = deduped.Values.ToList();

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable disable");
            // CS0164: label defined but never used (bodies without `return` leave their __end_N label unused).
            // CS0162: unreachable code (bodies ending with `throw` leave the trailing goto unreachable).
            sb.AppendLine("#pragma warning disable 164, 162");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Buffers.Binary;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Runtime.InteropServices;");
            sb.AppendLine("using Wacs.Core.OpCodes;");
            sb.AppendLine("using Wacs.Core.Runtime;");
            sb.AppendLine("using Wacs.Core.Runtime.Exceptions;");
            sb.AppendLine("using Wacs.Core.Runtime.GC;");
            sb.AppendLine("using Wacs.Core.Runtime.Types;");
            sb.AppendLine("using Wacs.Core.Types;");
            sb.AppendLine("using Wacs.Core.Types.Defs;");
            sb.AppendLine("using Wacs.Core.Instructions;");
            sb.AppendLine("using Wacs.Core.Instructions.SIMD;");
            sb.AppendLine("using Wacs.Core.Instructions.GC;");
            sb.AppendLine("using Wacs.Core.Utilities;");
            sb.AppendLine();
            sb.AppendLine("namespace Wacs.Core.Compilation");
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class GeneratedDispatcher");
            sb.AppendLine("    {");
            // Mirror bit-manipulation constants that live as `private const` inside the
            // instruction classes. Bodies copied verbatim into this partial class reference
            // these by unqualified name — this block keeps the names resolvable. Values are
            // identical to the originals; update in lockstep if ever changed.
            sb.AppendLine("        // Mirrored from InstF32BinOp");
            sb.AppendLine("        private const uint F32SignMask = 0x8000_0000u;");
            sb.AppendLine("        private const uint F32NotSignMask = ~F32SignMask;");
            sb.AppendLine("        // Mirrored from InstF64BinOp");
            sb.AppendLine("        private const ulong F64SignMask = 0x8000_0000_0000_0000ul;");
            sb.AppendLine("        private const ulong F64NotSignMask = ~F64SignMask;");
            sb.AppendLine("        // Mirrored from InstI32SignExtension");
            sb.AppendLine("        private const uint ByteSign = 0x80u;");
            sb.AppendLine("        private const uint I32ByteExtend = 0xFFFF_FF80u;");
            sb.AppendLine("        private const uint ByteMask = 0xFFu;");
            sb.AppendLine("        private const uint ShortSign = 0x8000u;");
            sb.AppendLine("        private const uint I32ShortExtend = 0xFFFF_8000u;");
            sb.AppendLine("        private const uint ShortMask = 0xFFFFu;");
            sb.AppendLine("        // Mirrored from InstI64SignExtension");
            sb.AppendLine("        private const ulong I64ByteExtend = 0xFFFF_FFFF_FFFF_FF80ul;");
            sb.AppendLine("        private const ulong I64ShortExtend = 0xFFFF_FFFF_FFFF_8000ul;");
            sb.AppendLine("        private const ulong WordSign = 0x8000_0000ul;");
            sb.AppendLine("        private const ulong WordExtend = 0xFFFF_FFFF_8000_0000ul;");
            sb.AppendLine("        private const ulong WordMask = 0xFFFF_FFFFul;");
            sb.AppendLine();

            // Group entries by prefix. Primary ops (OpCode enum) inline into Run; the rest
            // go to a per-prefix sub-method.
            var primaryOps = ordered.Where(e => e.EnumTypeName == "OpCode").ToList();
            var prefixGroups = new[]
            {
                ("GcCode",   (byte)0xFB),
                ("ExtCode",  (byte)0xFC),
                ("SimdCode", (byte)0xFD),
                ("AtomCode", (byte)0xFE),
                ("WacsCode", (byte)0xFF),
            };

            // Emit Run — the top-level dispatch method. While-loop + primary-byte switch +
            // prefix cases that delegate to sub-methods. pcBefore is stored on ExecContext
            // and updated each iteration so the exception-handler range check in
            // SwitchRuntime can reconstruct the pc of the throwing op (pc itself has
            // already advanced past the op's bytes by the time the throw propagates).
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Dispatch loop. Reads the primary byte, switches on it, and runs the inlined");
            sb.AppendLine("        /// body of each opcode to completion before looping. Prefix opcodes (0xFB-0xFF)");
            sb.AppendLine("        /// delegate to per-prefix sub-methods that handle their secondary byte(s).");
            sb.AppendLine("        /// </summary>");
            // SkipLocalsInit elides the method's .locals init flag, so the JIT doesn't emit
            // the frame-zeroing loop at entry. Run has a ~1.6 KiB frame (many per-case locals),
            // so the default dczva-based zero-fill is several hundred bytes of prologue. Safe
            // here because every local is explicitly assigned before any read — the generator
            // emits `{T} name = ...;` on first use in each case, and the method-level hoists
            // (_pc, _pcBefore, _opStack, etc.) are all initialized immediately.
            sb.AppendLine("        [System.Runtime.CompilerServices.SkipLocalsInit]");
            sb.AppendLine("        public static void Run(ExecContext ctx, ReadOnlySpan<byte> code, ref int pc, ref int pcBefore)");
            sb.AppendLine("        {");
            // Hoist the OpStack and the current frame's locals out of the hot loop. OpStack
            // is a readonly field (bound at ExecContext construction), so it's trivially safe.
            // Frame.Locals is fixed for the duration of THIS Run invocation — Call opcodes
            // recurse into nested InvokeWasm which saves+restores ctx.Frame around the inner
            // Run, so our hoisted span is never observed stale from within our own switch.
            sb.AppendLine("            var _opStack = ctx.OpStack;");
            sb.AppendLine("            var _localsSpan = ctx.Frame.Locals.Span;");
            // Hoist pc and pcBefore from the caller's refs into method-local ints. Two wins:
            //   1) Eliminates JIT aliasing-conservatism: with two <c>ref int</c> parameters,
            //      a write to pcBefore forces pc to reload through memory on every iteration.
            //      Locals live in registers and the write becomes a reg-to-reg mov.
            //   2) Call-immediate reads (<c>StreamReader.ReadX(code, ref _pc)</c>) still spill
            //      the local for the call, but that only happens in cases with immediates —
            //      not every iteration's fetch/branch/pop/push.
            // The try/finally writes back on both normal and abnormal exit so the caller
            // sees final pc / pcBefore values (needed for exception-handler range checks).
            sb.AppendLine("            int _pc = pc;");
            sb.AppendLine("            int _pcBefore = pcBefore;");
            // Hoist the span's raw byte reference + length so the per-iteration fetch can
            // use Unsafe.Add (no bounds check) — the while-loop guard already ensures
            // _pc &lt; _codeLen at the read site. GetReference is an intrinsic that lowers
            // to a single pointer read; stays AOT-safe.
            sb.AppendLine("            ref byte _codeBase = ref System.Runtime.InteropServices.MemoryMarshal.GetReference(code);");
            sb.AppendLine("            int _codeLen = code.Length;");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine("                while (_pc < _codeLen)");
            sb.AppendLine("                {");
            sb.AppendLine("                    _pcBefore = _pc;");
            sb.AppendLine("                    byte primary = System.Runtime.CompilerServices.Unsafe.Add(ref _codeBase, _pc);");
            sb.AppendLine("                    _pc++;");
            sb.AppendLine("                    switch (primary)");
            sb.AppendLine("                    {");
            int caseCounter = 0;
            foreach (var e in primaryOps.OrderBy(e => e.RawValue))
            {
                EmitCase(sb, e, "                        ", ref caseCounter, singleByteKey: true, inLoop: true, pcVar: "_pc");
            }
            foreach (var (_, pb) in prefixGroups)
            {
                sb.AppendLine($"                        case 0x{pb:X2}: Dispatch{pb:X2}(ctx, code, ref _pc); continue;");
            }
            sb.AppendLine("                        default:");
            sb.AppendLine("                            throw new NotSupportedException(");
            sb.AppendLine("                                $\"Opcode 0x{primary:X2} at pc={_pc - 1} has no [OpSource]/[OpHandler] coverage.\");");
            sb.AppendLine("                    }");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("            finally");
            sb.AppendLine("            {");
            sb.AppendLine("                pc = _pc;");
            sb.AppendLine("                pcBefore = _pcBefore;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();

            // Per-prefix sub-methods. Each reads its secondary byte (or u16 for SIMD) and
            // dispatches a single op. Returns control to Run's loop after.
            foreach (var (enumType, prefixByte) in prefixGroups)
            {
                var subEntries = ordered.Where(e => e.EnumTypeName == enumType).OrderBy(e => e.RawValue).ToList();
                EmitPrefixSubMethod(sb, enumType, prefixByte, subEntries, ref caseCounter);
            }

            sb.AppendLine();
            sb.AppendLine("        /// <summary>The number of ops the generator emitted cases for.</summary>");
            sb.AppendLine($"        public const int HandledOpcodeCount = {ordered.Count};");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource("GeneratedDispatcher.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        /// <summary>
        /// Emit a per-prefix sub-dispatcher. Reads the secondary byte (single byte for all
        /// prefixes except SIMD, which uses a u16 to accommodate relaxed-SIMD opcodes >=
        /// 0x100), switches on it, and runs one op to completion before returning.
        /// </summary>
        private static void EmitPrefixSubMethod(StringBuilder sb, string enumType, byte prefixByte,
                                                 List<DispatchEntry> entries, ref int caseCounter)
        {
            bool isSimd = enumType == "SimdCode";
            string keyType = isSimd ? "ushort" : "byte";
            sb.AppendLine($"        private static void Dispatch{prefixByte:X2}(ExecContext ctx, ReadOnlySpan<byte> code, ref int pc)");
            sb.AppendLine("        {");
            // Hoist the same locals Run hoists, so emitted case bodies (_opStack.XXX,
            // _localsSpan[idx], Unsafe.ReadUnaligned(ref _codeBase, ...)) compile uniformly
            // here too. The hoist cost is tiny in a per-op sub-method — a few field reads —
            // and keeps the generator's per-case emit identical between Run and each
            // Dispatch<prefix>.
            sb.AppendLine("            var _opStack = ctx.OpStack;");
            sb.AppendLine("            var _localsSpan = ctx.Frame.Locals.Span;");
            sb.AppendLine("            ref byte _codeBase = ref System.Runtime.InteropServices.MemoryMarshal.GetReference(code);");
            if (isSimd)
            {
                // Two-byte secondary (relaxed-SIMD opcodes go past 0xFF). Unsafe.ReadUnaligned
                // avoids the Slice bounds check that BinaryPrimitives would demand.
                sb.AppendLine("            ushort sec = System.Runtime.CompilerServices.Unsafe.ReadUnaligned<ushort>(ref System.Runtime.CompilerServices.Unsafe.Add(ref _codeBase, pc));");
                sb.AppendLine("            pc += 2;");
            }
            else
            {
                sb.AppendLine("            byte sec = System.Runtime.CompilerServices.Unsafe.Add(ref _codeBase, pc); pc += 1;");
            }
            sb.AppendLine("            switch (sec)");
            sb.AppendLine("            {");
            foreach (var e in entries)
            {
                EmitCase(sb, e, "                ", ref caseCounter, singleByteKey: false, inLoop: false, pcVar: "pc");
            }
            sb.AppendLine("                default:");
            sb.AppendLine($"                    throw new NotSupportedException(");
            sb.AppendLine($"                        $\"Prefix 0x{prefixByte:X2} secondary 0x{{sec:X}} has no [OpSource]/[OpHandler] coverage.\");");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        /// <summary>
        /// Emit one case: reads immediates, pops stack operands into named locals, inlines
        /// the handler body with returns rewritten to the per-case push+continue pattern.
        /// No wrappers, no static local functions — each case is raw inlined logic.
        /// </summary>
        /// <param name="singleByteKey">True when this case lives in <c>Run</c>'s primary
        /// switch (key is the primary byte, same as the opcode value for OpCode-enum ops).
        /// False when inside a prefix sub-method (key is the secondary byte/u16).</param>
        /// <param name="inLoop">True when the switch is inside <c>Run</c>'s while loop — we
        /// end each case with <c>continue;</c>. False inside a prefix sub-method — we end
        /// with <c>return;</c> to hand control back to the caller's loop.</param>
        /// <param name="pcVar">Name of the pc variable in this enclosing scope — <c>"_pc"</c>
        /// in <c>Run</c> (where pc is hoisted from the ref param to a local), <c>"pc"</c> in
        /// prefix sub-methods (where pc is still the ref parameter). Used both for emitted
        /// <c>StreamReader.ReadX(code, ref {pcVar})</c> immediate reads and to textually
        /// rewrite <c>pc</c> identifiers inside handler bodies that take a <c>ref int pc</c>.</param>
        private static void EmitCase(StringBuilder sb, DispatchEntry e, string indent,
                                      ref int caseCounter, bool singleByteKey, bool inLoop,
                                      string pcVar)
        {
            int caseId = caseCounter++;
            // Key = raw enum value masked to keyType width. For primary ops (OpCode enum),
            // values already fit in a byte; for prefix ops, SimdCode values can exceed a byte
            // (relaxed-SIMD is 0x100+), so mask accordingly.
            string keyHex = singleByteKey
                ? $"0x{(e.RawValue & 0xFF):X2}"
                : (e.EnumTypeName == "SimdCode"
                    ? $"0x{(e.RawValue & 0xFFFF):X}"
                    : $"0x{(e.RawValue & 0xFF):X2}");

            sb.Append(indent).AppendLine($"case {keyHex}: // {e.EnumName}.{e.EnumMember} — {e.MethodName}");
            sb.Append(indent).AppendLine("{");

            string inner = indent + "    ";

            // 0. Alias the outer Run's ctx/code/pc when the handler's declared parameter
            //    uses a different name (e.g. handlers that named their ExecContext param
            //    `context`). Aliasing lets us inline the body verbatim without textual
            //    parameter renaming. Reference-type aliases (ctx) and span-struct
            //    aliases (code) just copy the 64-bit / 16-byte value; a ref alias for
            //    pc is a single ldloca in IL. No observable overhead after inlining.
            foreach (var p in e.Parameters)
            {
                switch (p.Kind)
                {
                    case ParamKind.Ctx when p.Name != "ctx":
                        sb.Append(inner).AppendLine($"ExecContext {p.Name} = ctx;");
                        break;
                    case ParamKind.Code when p.Name != "code":
                        sb.Append(inner).AppendLine($"System.ReadOnlySpan<byte> {p.Name} = code;");
                        break;
                    // RefPc is not aliased — we textually rewrite the body's `pc` → pcVar
                    // (done in RewriteCtxAccess below). A ref alias would force the JIT to
                    // treat writes through the alias as going through memory, defeating the
                    // register-hoist of _pc in Run.
                }
            }

            // 1. Read immediates in declaration order. Emit inline Unsafe.ReadUnaligned<T>
            //    off the hoisted ref-byte _codeBase instead of calling StreamReader.ReadX —
            //    Run is too large for the JIT to honour StreamReader's [AggressiveInlining]
            //    attribute, so the call would otherwise turn into an out-of-line PLT-style
            //    indirect dispatch per immediate (~11 instructions + a blr). With the
            //    inline form each immediate reduces to one unaligned load + a pc increment.
            //
            //    Little-endian only: .NET supported platforms (x64, ARM64) are all LE, and
            //    the annotated bytecode stream is always emitted LE by BytecodeCompiler. A
            //    big-endian host would need a byte-swap here, but that's a non-goal.
            foreach (var p in e.Parameters.Where(p => p.Kind == ParamKind.Immediate))
            {
                int width = ImmWidth(p.Type);
                if (width == 0)
                {
                    sb.Append(inner).AppendLine($"// skipped — unsupported [Imm] type {p.Type}");
                    sb.Append(inner).AppendLine("throw new NotSupportedException(\"Unsupported immediate type\");");
                    sb.Append(indent).AppendLine("}");
                    return;
                }
                if (p.Type == "byte")
                {
                    // Single-byte read: one Unsafe.Add + deref, no need for ReadUnaligned.
                    sb.Append(inner).AppendLine(
                        $"{p.Type} {p.Name} = System.Runtime.CompilerServices.Unsafe.Add(ref _codeBase, {pcVar}); {pcVar} += 1;");
                }
                else
                {
                    sb.Append(inner).AppendLine(
                        $"{p.Type} {p.Name} = System.Runtime.CompilerServices.Unsafe.ReadUnaligned<{p.Type}>(" +
                        $"ref System.Runtime.CompilerServices.Unsafe.Add(ref _codeBase, {pcVar})); {pcVar} += {width};");
                }
            }

            // 2. Pop stack operands in REVERSE parameter order (WASM semantics: last param
            //    was pushed last, so it's the top of stack). Each pop lands in a local
            //    named after the parameter — the handler body references these by name
            //    verbatim, no renaming needed.
            var stackParams = e.Parameters.Where(p => p.Kind == ParamKind.Stack).ToList();
            for (int i = stackParams.Count - 1; i >= 0; i--)
            {
                var p = stackParams[i];
                var popOp = TypeToPop(p.Type);
                if (popOp == null)
                {
                    sb.Append(inner).AppendLine($"// skipped — unsupported stack parameter type {p.Type}");
                    sb.Append(inner).AppendLine("throw new NotSupportedException(\"Unsupported stack type\");");
                    sb.Append(indent).AppendLine("}");
                    return;
                }
                sb.Append(inner).AppendLine($"{p.Type} {p.Name} = _opStack.{popOp}();");
            }

            // 3. Inline the body. Fast path for the overwhelmingly common case
            //    (expression-bodied handler, i.e. `=> expr;`): emit a single push-continue
            //    with the raw expression — no __r temp, no goto, no label. Matches the
            //    MinimalDispatcher shape byte-for-byte.
            //
            //    For block bodies (multi-return, trap paths): declare a result local,
            //    rewrite `return <expr>;` to `{ __r = <expr>; goto __end_N; }`, rewrite
            //    `return;` (void) to `goto __end_N;`, converge at __end_N.
            string endLabel = $"__end_{caseId}";
            string pushOp = e.ReturnType == "void" ? null : TypeToPush(e.ReturnType);
            if (e.ReturnType != "void" && pushOp == null)
            {
                sb.Append(inner).AppendLine($"// skipped — unsupported return type {e.ReturnType}");
                sb.Append(inner).AppendLine("throw new NotSupportedException(\"Unsupported return type\");");
                sb.Append(indent).AppendLine("}");
                return;
            }

            string terminator = inLoop ? "continue;" : "return;";

            if (e.BodyIsExpression)
            {
                string exprBody = RewriteCtxAccess(e.Body, pcVar);
                if (e.ReturnType == "void")
                {
                    sb.Append(inner).AppendLine($"{exprBody}; {terminator}");
                }
                else
                {
                    sb.Append(inner).AppendLine($"_opStack.{pushOp}({exprBody}); {terminator}");
                }
                // No label emitted for expression bodies — nothing jumps to it.
                sb.Append(indent).AppendLine("}");
                return;
            }

            // Block body: needs the result-capture + label pattern for multi-return safety.
            if (e.ReturnType != "void")
                sb.Append(inner).AppendLine($"{e.ReturnType} __r = default;");

            string rewritten = RewriteBody(e.Body, e.BodyIsExpression, e.ReturnType, endLabel, pcVar);
            foreach (var line in rewritten.Split('\n'))
            {
                if (line.Length == 0) { sb.AppendLine(); continue; }
                sb.Append(inner).AppendLine(line.TrimEnd('\r'));
            }

            if (e.ReturnType == "void")
            {
                sb.Append(inner).AppendLine($"{endLabel}: {terminator}");
            }
            else
            {
                sb.Append(inner).AppendLine($"{endLabel}: _opStack.{pushOp}(__r); {terminator}");
            }

            sb.Append(indent).AppendLine("}");
        }

        /// <summary>
        /// Rewrite <c>return</c> statements in a handler body to the push+goto pattern the
        /// inlined case wants.
        ///
        /// <para>For expression bodies (single <c>=&gt; expr</c>), we emit just
        /// <c>__r = &lt;expr&gt;; goto END;</c> (non-void) or <c>&lt;expr&gt;; goto END;</c> (void).</para>
        ///
        /// <para>For block bodies we preserve the original <c>{ ... }</c>, stripping the outer
        /// braces so nested locals defined in the body share the case's scope (immediates +
        /// popped operands live at the case scope, the body sees them through the same
        /// names), then apply a textual rewrite: <c>return &lt;expr&gt;;</c> becomes
        /// <c>{ __r = &lt;expr&gt;; goto END; }</c>, and bare <c>return;</c> becomes
        /// <c>goto END;</c>. Because C# <c>return</c> statements cannot appear inside
        /// sub-expressions (the keyword is statement-level), a simple non-greedy regex is
        /// safe for every handler body in the codebase (no nested lambdas or local
        /// functions in any annotated method).</para>
        /// </summary>
        private static string RewriteBody(string body, bool isExpression, string returnType, string endLabel, string pcVar)
        {
            body = RewriteCtxAccess(body, pcVar);
            if (isExpression)
            {
                // The body is the raw expression (no braces, no `return` keyword).
                if (returnType == "void")
                    return $"{body};";
                return $"__r = {body}; goto {endLabel};";
            }

            // Block body. Strip the outer braces (first `{` and last `}`); keep the rest.
            string inner = body.Trim();
            if (inner.StartsWith("{")) inner = inner.Substring(1);
            if (inner.EndsWith("}"))   inner = inner.Substring(0, inner.Length - 1);

            if (returnType == "void")
            {
                // Bare `return;` → `goto END;`.
                inner = Regex.Replace(inner, @"\breturn\s*;",
                                      $"goto {endLabel};");
                return inner;
            }
            else
            {
                // `return <expr>;` → `{ __r = <expr>; goto END; }`. The non-greedy match
                // stops at the first semicolon — safe because return-expressions can't
                // contain unescaped semicolons.
                inner = Regex.Replace(inner, @"\breturn\s+(.+?);",
                                      "{ __r = $1; goto " + endLabel + "; }",
                                      RegexOptions.Singleline);
                return inner;
            }
        }

        /// <summary>
        /// Rewrite hoistable ctx accesses in a handler body to their hoisted-local names.
        /// <list type="bullet">
        ///   <item><c>ctx.OpStack</c> → <c>_opStack</c></item>
        ///   <item><c>ctx.Frame.Locals.Span</c> → <c>_localsSpan</c></item>
        ///   <item><c>pc</c> → <c>{pcVar}</c> (whole-word; skipped when pcVar == "pc")</item>
        /// </list>
        /// All handlers with a <c>ref int pc</c> parameter name it <c>pc</c>, so the word-
        /// boundary rewrite reliably retargets the body at Run's local <c>_pc</c> without
        /// introducing a ref alias (which would force writes through memory, defeating the
        /// register hoist).
        ///
        /// <para>The rewrites are token-safe for today's handler bodies: none of
        /// <c>ctx.OpStack</c>, <c>ctx.Frame.Locals.Span</c>, or the identifier <c>pc</c>
        /// appears inside strings or as substrings of other identifiers. If a future
        /// handler introduces either, spell it in a form these patterns don't match
        /// (e.g. fully-qualified <c>Wacs.Core.Runtime.ExecContext.OpStack</c>, or a
        /// differently-named pc parameter).</para>
        /// </summary>
        private static string RewriteCtxAccess(string body, string pcVar)
        {
            body = body
                .Replace("ctx.OpStack", "_opStack")
                .Replace("ctx.Frame.Locals.Span", "_localsSpan");
            if (pcVar != "pc")
                body = System.Text.RegularExpressions.Regex.Replace(body, @"\bpc\b", pcVar);
            return body;
        }

        private static string TypeToPop(string t) => t switch
        {
            "int"    => "PopI32",
            "uint"   => "PopU32",
            "long"   => "PopI64",
            "ulong"  => "PopU64",
            "float"  => "PopF32",
            "double" => "PopF64",
            "Wacs.Core.Runtime.Value" => "PopAny",
            "Wacs.Core.Runtime.V128"  => "PopV128",
            _ => null,
        };

        private static string TypeToPush(string t) => t switch
        {
            "int"    => "PushI32",
            "uint"   => "PushU32",
            "long"   => "PushI64",
            "ulong"  => "PushU64",
            "float"  => "PushF32",
            "double" => "PushF64",
            "Wacs.Core.Runtime.Value" => "PushValue",
            "Wacs.Core.Runtime.V128"  => "PushV128",
            _ => null,
        };

        private static string TypeToImmReader(string t) => t switch
        {
            "int"    => "ReadS32",
            "uint"   => "ReadU32",
            "long"   => "ReadS64",
            "ulong"  => "ReadU64",
            "float"  => "ReadF32",
            "double" => "ReadF64",
            "byte"   => "ReadU8",
            "Wacs.Core.Runtime.V128" => "ReadV128",
            _ => null,
        };

        /// <summary>
        /// Byte width of each supported immediate type. 0 means unsupported (the generator
        /// falls through to its <c>NotSupportedException</c> path for that case). Matches
        /// the widths produced by <see cref="Wacs.Core.Compilation.BytecodeCompiler"/>.
        /// </summary>
        private static int ImmWidth(string t) => t switch
        {
            "int"    => 4,
            "uint"   => 4,
            "long"   => 8,
            "ulong"  => 8,
            "float"  => 4,
            "double" => 8,
            "byte"   => 1,
            "Wacs.Core.Runtime.V128" => 16,
            _ => 0,
        };

        private enum ParamKind { Stack, Immediate, Ctx, RefPc, Code }

        private sealed class DispatchEntry
        {
            public readonly string EnumTypeName;
            public readonly int RawValue;
            public readonly string MethodName;
            public readonly string EnumName;
            public readonly string EnumMember;
            public readonly ImmutableArray<ParamInfo> Parameters;
            public readonly string ReturnType;
            public readonly string Body;
            public readonly bool BodyIsExpression;
            public readonly bool IsHandler;

            public DispatchEntry(string enumTypeName, int rawValue, string methodName, string enumName,
                                 string enumMember, ImmutableArray<ParamInfo> parameters, string returnType,
                                 string body, bool bodyIsExpression, bool isHandler)
            {
                EnumTypeName = enumTypeName;
                RawValue = rawValue;
                MethodName = methodName;
                EnumName = enumName;
                EnumMember = enumMember;
                Parameters = parameters;
                ReturnType = returnType;
                Body = body;
                BodyIsExpression = bodyIsExpression;
                IsHandler = isHandler;
            }
        }

        private readonly struct ParamInfo
        {
            public readonly string Name;
            public readonly string Type;
            public readonly ParamKind Kind;
            public ParamInfo(string name, string type, ParamKind kind) { Name = name; Type = type; Kind = kind; }
        }
    }
}
