// Copyright 2026 Kelvin Nishikawa
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Wacs.Compilation
{
    /// <summary>
    /// Source generator for the monolithic-switch WebAssembly interpreter. Consumes methods
    /// marked with <c>[OpSource]</c> (stack-only pure ops) or <c>[OpHandler]</c> (any op,
    /// including those with immediates or control-flow side effects) and emits
    /// <c>Wacs.Core.Compilation.GeneratedDispatcher.TryDispatch</c> — a single switch over
    /// the opcode ushort that runs each handler with its operands popped off the OpStack
    /// and its immediates read inline from the annotated bytecode stream.
    ///
    /// AOT-safe: no runtime reflection. All introspection happens in the generator at build time.
    /// </summary>
    [Generator]
    public class DispatchGenerator : IIncrementalGenerator
    {
        private const string OpSourceAttrFullName  = "Wacs.Core.Compilation.OpSourceAttribute";
        private const string OpHandlerAttrFullName = "Wacs.Core.Compilation.OpHandlerAttribute";
        private const string ImmAttrFullName       = "Wacs.Core.Compilation.ImmAttribute";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var entries = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => IsCandidateMethod(node),
                    transform: static (ctx, ct) => Extract(ctx, ct))
                .Where(static e => e != null)
                .Collect();

            context.RegisterSourceOutput(entries, (spc, items) =>
            {
                try
                {
                    Emit(spc, items);
                }
                catch (System.Exception ex)
                {
                    spc.AddSource("GeneratedDispatcher.Error.g.cs",
                        SourceText.From(
                            "// <auto-generated/>\n// DispatchGenerator threw:\n// " +
                            ex.GetType().FullName + ": " + ex.Message.Replace("\n", " ") + "\n" +
                            "// Stack:\n// " + (ex.StackTrace ?? "").Replace("\n", "\n// ") + "\n",
                            Encoding.UTF8));
                }
            });
        }

        private static bool IsCandidateMethod(SyntaxNode node)
        {
            if (node is not MethodDeclarationSyntax m) return false;
            if (m.AttributeLists.Count == 0) return false;
            // Quick textual prefilter — avoids semantic model work on the 99% of methods that don't apply.
            foreach (var list in m.AttributeLists)
                foreach (var attr in list.Attributes)
                {
                    var name = attr.Name.ToString();
                    if (name.Contains("OpSource") || name.Contains("OpHandler"))
                        return true;
                }
            return false;
        }

        private static DispatchEntry Extract(GeneratorSyntaxContext ctx, CancellationToken ct)
        {
            var method = (MethodDeclarationSyntax)ctx.Node;
            var symbol = ctx.SemanticModel.GetDeclaredSymbol(method, ct) as IMethodSymbol;
            if (symbol == null) return null;

            AttributeData opAttr = null;
            bool isHandler = false;
            foreach (var a in symbol.GetAttributes())
            {
                var full = a.AttributeClass?.ToDisplayString();
                if (full == OpSourceAttrFullName)  { opAttr = a; isHandler = false; break; }
                if (full == OpHandlerAttrFullName) { opAttr = a; isHandler = true;  break; }
            }
            if (opAttr == null) return null;
            if (opAttr.ConstructorArguments.Length != 1) return null;

            var arg = opAttr.ConstructorArguments[0];
            if (arg.Kind != TypedConstantKind.Enum || arg.Type == null || arg.Value == null) return null;

            int rawValue = System.Convert.ToInt32(arg.Value);
            ushort opKey = ComputeOpcodeKey(arg.Type.Name, rawValue);
            string enumName = arg.Type.ToDisplayString();
            string enumMember = arg.Type.GetMembers()
                .OfType<IFieldSymbol>()
                .FirstOrDefault(f => f.HasConstantValue && System.Convert.ToInt32(f.ConstantValue) == rawValue)?.Name
                ?? rawValue.ToString();

            var parameters = ImmutableArray.CreateBuilder<ParamInfo>(symbol.Parameters.Length);
            foreach (var p in symbol.Parameters)
            {
                parameters.Add(ClassifyParam(p, isHandler));
            }

            string returnType = symbol.ReturnType.SpecialType == SpecialType.System_Void
                ? "void"
                : symbol.ReturnType.ToDisplayString();

            string bodyText;
            if (method.Body != null)
            {
                bodyText = method.Body.ToFullString();
            }
            else if (method.ExpressionBody != null)
            {
                // Expression-bodied method: the expression IS the body. For non-void returns,
                // wrap as `{ return expr; }`; for void returns, wrap as `{ expr; }` (the
                // expression must be a statement-type expression such as an invocation).
                string expr = method.ExpressionBody.Expression.ToFullString().Trim();
                bodyText = returnType == "void"
                    ? "{ " + expr + "; }"
                    : "{ return " + expr + "; }";
            }
            else
            {
                return null;
            }

            return new DispatchEntry(opKey, symbol.Name, enumName, enumMember,
                                     parameters.ToImmutable(), returnType, bodyText, isHandler);
        }

        private static ParamInfo ClassifyParam(IParameterSymbol p, bool isHandler)
        {
            string type = p.Type.ToDisplayString();
            // ref int pc — only legal on [OpHandler].
            if (isHandler && p.RefKind == RefKind.Ref && p.Type.SpecialType == SpecialType.System_Int32 && p.Name == "pc")
            {
                return new ParamInfo(p.Name, type, ParamKind.RefPc);
            }
            // ExecContext — only legal on [OpHandler].
            if (isHandler && type == "Wacs.Core.Runtime.ExecContext")
            {
                return new ParamInfo(p.Name, type, ParamKind.Ctx);
            }
            // ReadOnlySpan<byte> code — the raw bytecode span. Useful for variable-length
            // immediates (br_table) where the handler wants to read ad-hoc.
            if (isHandler && type == "System.ReadOnlySpan<byte>")
            {
                return new ParamInfo(p.Name, type, ParamKind.Code);
            }
            // [Imm] → Immediate (must be [OpHandler]).
            if (isHandler)
            {
                foreach (var a in p.GetAttributes())
                {
                    if (a.AttributeClass?.ToDisplayString() == ImmAttrFullName)
                        return new ParamInfo(p.Name, type, ParamKind.Immediate);
                }
            }
            // Default: Stack (popped value).
            return new ParamInfo(p.Name, type, ParamKind.Stack);
        }

        private static ushort ComputeOpcodeKey(string enumTypeName, int value)
        {
            byte b = (byte)value;
            return enumTypeName switch
            {
                "OpCode"   => (ushort)(b << 8),
                "GcCode"   => (ushort)((0xFB << 8) | b),
                "ExtCode"  => (ushort)((0xFC << 8) | b),
                "SimdCode" => (ushort)((0xFD << 8) | b),
                "AtomCode" => (ushort)((0xFE << 8) | b),
                "WacsCode" => (ushort)((0xFF << 8) | b),
                _ => (ushort)(b << 8),
            };
        }

        private static void Emit(SourceProductionContext spc, ImmutableArray<DispatchEntry> entries)
        {
            var deduped = new Dictionary<ushort, DispatchEntry>();
            foreach (var e in entries)
            {
                if (e == null) continue;
                if (!deduped.ContainsKey(e.OpKey)) deduped[e.OpKey] = e;
            }
            var ordered = deduped.Values.OrderBy(e => e.OpKey).ToList();

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable disable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Runtime.InteropServices;");
            sb.AppendLine("using Wacs.Core.OpCodes;");
            sb.AppendLine("using Wacs.Core.Runtime;");
            sb.AppendLine("using Wacs.Core.Runtime.Exceptions;");
            // TrapException sits in Runtime.Types despite living in the Runtime/Exceptions folder.
            sb.AppendLine("using Wacs.Core.Runtime.Types;");
            // GlobalIdx / FuncIdx / etc. live here — needed whenever a handler body casts an index.
            sb.AppendLine("using Wacs.Core.Types;");
            // Handler bodies may qualify sibling helper methods as `ControlHandlers.Xyz` etc.;
            // the generator copies them into GeneratedDispatcher, which lives in
            // Wacs.Core.Compilation, so those short names only resolve via this using.
            sb.AppendLine("using Wacs.Core.Instructions;");
            sb.AppendLine();
            sb.AppendLine("namespace Wacs.Core.Compilation");
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class GeneratedDispatcher");
            sb.AppendLine("    {");
            // Mirror bit-manipulation constants that live as `private const` inside the instruction
            // classes. Copying the bodies verbatim into this partial class would otherwise fail to
            // resolve these identifiers. Values are identical to the originals — if they're ever
            // changed, update this block to match.
            sb.AppendLine("        // Mirrored from InstF32BinOp");
            sb.AppendLine("        private const uint F32SignMask = 0x8000_0000u;");
            sb.AppendLine("        private const uint F32NotSignMask = ~F32SignMask;");
            sb.AppendLine("        // Mirrored from InstF64BinOp");
            sb.AppendLine("        private const ulong F64SignMask = 0x8000_0000_0000_0000ul;");
            sb.AppendLine("        private const ulong F64NotSignMask = ~F64SignMask;");
            sb.AppendLine("        // Mirrored from InstI32SignExtension");
            sb.AppendLine("        private const uint ByteSign = 0x80u;");
            sb.AppendLine("        private const uint I32ByteExtend = 0xFFFF_FF80u;");
            sb.AppendLine("        private const uint ByteMask = 0xFFu;");
            sb.AppendLine("        private const uint ShortSign = 0x8000u;");
            sb.AppendLine("        private const uint I32ShortExtend = 0xFFFF_8000u;");
            sb.AppendLine("        private const uint ShortMask = 0xFFFFu;");
            sb.AppendLine("        // Mirrored from InstI64SignExtension");
            sb.AppendLine("        private const ulong I64ByteExtend = 0xFFFF_FFFF_FFFF_FF80ul;");
            sb.AppendLine("        private const ulong I64ShortExtend = 0xFFFF_FFFF_FFFF_8000ul;");
            sb.AppendLine("        private const ulong WordSign = 0x8000_0000ul;");
            sb.AppendLine("        private const ulong WordExtend = 0xFFFF_FFFF_8000_0000ul;");
            sb.AppendLine("        private const ulong WordMask = 0xFFFF_FFFFul;");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Dispatches <paramref name=\"op\"/> (primary &lt;&lt; 8 | secondary; matches (ushort)ByteCode).");
            sb.AppendLine("        /// Each handler reads its own immediates inline from <paramref name=\"code\"/> starting at");
            sb.AppendLine("        /// <paramref name=\"pc\"/>, advancing it as it consumes bytes. Returns true if the op was");
            sb.AppendLine("        /// handled. Returns false for ops without [OpSource]/[OpHandler] coverage yet.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static bool TryDispatch(ExecContext ctx, ReadOnlySpan<byte> code, ref int pc, ushort op)");
            sb.AppendLine("        {");
            sb.AppendLine("            switch (op)");
            sb.AppendLine("            {");
            foreach (var e in ordered)
            {
                EmitCase(sb, e);
            }
            sb.AppendLine("                default: return false;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>The number of ops the generator emitted cases for.</summary>");
            sb.AppendLine($"        public const int HandledOpcodeCount = {ordered.Count};");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource("GeneratedDispatcher.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private static void EmitCase(StringBuilder sb, DispatchEntry e)
        {
            sb.AppendLine($"                case 0x{e.OpKey:X4}: // {e.EnumName}.{e.EnumMember} — {e.MethodName}");
            sb.AppendLine("                {");

            // 1. Read immediates FIRST (left-to-right), advancing pc. Order matters — a handler
            //    could, in principle, have immediate-then-stack interleaved, but WASM semantics
            //    separate them: immediates are encoded in the instruction, stack values in the
            //    operand stack. Read all immediates before touching the stack.
            foreach (var p in e.Parameters.Where(p => p.Kind == ParamKind.Immediate))
            {
                var reader = TypeToImmReader(p.Type);
                if (reader == null)
                {
                    sb.AppendLine($"                    // skipped — unsupported [Imm] type {p.Type}");
                    sb.AppendLine("                    return false;");
                    sb.AppendLine("                }");
                    return;
                }
                sb.AppendLine($"                    {p.Type} {p.Name} = StreamReader.{reader}(code, ref pc);");
            }

            // 2. Pop stack operands in REVERSE parameter order so i1/i2 pop naturally (WASM pushes
            //    left-to-right; we pop right-to-left). This matches the pre-existing convention
            //    used by every polymorphic Execute method.
            var stackParams = e.Parameters.Where(p => p.Kind == ParamKind.Stack).ToList();
            for (int i = stackParams.Count - 1; i >= 0; i--)
            {
                var p = stackParams[i];
                var popOp = TypeToPop(p.Type);
                if (popOp == null)
                {
                    sb.AppendLine($"                    // skipped — unsupported stack parameter type {p.Type}");
                    sb.AppendLine("                    return false;");
                    sb.AppendLine("                }");
                    return;
                }
                sb.AppendLine($"                    {p.Type} {p.Name} = ctx.OpStack.{popOp}();");
            }

            // 3. Emit the body via a static local function so multi-return / throw bodies port
            //    verbatim. The JIT inlines small static locals — no allocation, no closure.
            //    Parameters of the local function match the original method signature order,
            //    with ExecContext and `ref int pc` forwarded as-is when present.
            var localSigParts = e.Parameters.Select(p => p.Kind switch
            {
                ParamKind.Ctx       => $"ExecContext {p.Name}",
                ParamKind.RefPc     => $"ref int {p.Name}",
                ParamKind.Code      => $"System.ReadOnlySpan<byte> {p.Name}",
                _                   => $"{p.Type} {p.Name}",
            });
            string paramList = string.Join(", ", localSigParts);
            string body = IndentBody(e.Body, "                    ");
            sb.AppendLine($"                    static {e.ReturnType} __Op({paramList})");
            sb.AppendLine(body);

            // 4. Call the local function with args in original parameter order.
            var argList = string.Join(", ", e.Parameters.Select(p => p.Kind switch
            {
                ParamKind.Ctx   => "ctx",
                ParamKind.RefPc => "ref pc",
                ParamKind.Code  => "code",
                _               => p.Name,
            }));

            if (e.ReturnType == "void")
            {
                sb.AppendLine($"                    __Op({argList});");
            }
            else
            {
                var pushOp = TypeToPush(e.ReturnType);
                if (pushOp == null)
                {
                    sb.AppendLine($"                    // skipped — unsupported return type {e.ReturnType}");
                    sb.AppendLine("                    return false;");
                    sb.AppendLine("                }");
                    return;
                }
                sb.AppendLine($"                    ctx.OpStack.{pushOp}(__Op({argList}));");
            }

            sb.AppendLine("                    return true;");
            sb.AppendLine("                }");
        }

        private static string IndentBody(string body, string indent)
        {
            var lines = body.Replace("\r\n", "\n").Split('\n');
            var sb = new StringBuilder();
            for (int i = 0; i < lines.Length; i++)
            {
                var line = lines[i];
                if (line.Length == 0 && i == lines.Length - 1) continue;
                sb.Append(indent);
                sb.Append(line);
                if (i < lines.Length - 1) sb.Append('\n');
            }
            return sb.ToString();
        }

        private static string TypeToPop(string t) => t switch
        {
            "int"    => "PopI32",
            "uint"   => "PopU32",
            "long"   => "PopI64",
            "ulong"  => "PopU64",
            "float"  => "PopF32",
            "double" => "PopF64",
            // Type-agnostic stack values (Value struct) — used by variable + parametric ops.
            "Wacs.Core.Runtime.Value" => "PopAny",
            _ => null,
        };

        private static string TypeToPush(string t) => t switch
        {
            "int"    => "PushI32",
            "uint"   => "PushU32",
            "long"   => "PushI64",
            "ulong"  => "PushU64",
            "float"  => "PushF32",
            "double" => "PushF64",
            "Wacs.Core.Runtime.Value" => "PushValue",
            _ => null,
        };

        private static string TypeToImmReader(string t) => t switch
        {
            "int"    => "ReadS32",
            "uint"   => "ReadU32",
            "long"   => "ReadS64",
            "ulong"  => "ReadU64",
            "float"  => "ReadF32",
            "double" => "ReadF64",
            "byte"   => "ReadU8",
            _ => null,
        };

        private enum ParamKind { Stack, Immediate, Ctx, RefPc, Code }

        private sealed class DispatchEntry
        {
            public readonly ushort OpKey;
            public readonly string MethodName;
            public readonly string EnumName;
            public readonly string EnumMember;
            public readonly ImmutableArray<ParamInfo> Parameters;
            public readonly string ReturnType;
            public readonly string Body;
            public readonly bool IsHandler;

            public DispatchEntry(ushort opKey, string methodName, string enumName, string enumMember,
                                 ImmutableArray<ParamInfo> parameters, string returnType, string body,
                                 bool isHandler)
            {
                OpKey = opKey;
                MethodName = methodName;
                EnumName = enumName;
                EnumMember = enumMember;
                Parameters = parameters;
                ReturnType = returnType;
                Body = body;
                IsHandler = isHandler;
            }
        }

        private readonly struct ParamInfo
        {
            public readonly string Name;
            public readonly string Type;
            public readonly ParamKind Kind;
            public ParamInfo(string name, string type, ParamKind kind) { Name = name; Type = type; Kind = kind; }
        }
    }
}
