// Copyright 2026 Kelvin Nishikawa
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Wacs.Compilation
{
    /// <summary>
    /// Source generator for the monolithic-switch WebAssembly interpreter. Consumes methods
    /// marked with <c>[OpSource]</c> (stack-only pure ops) or <c>[OpHandler]</c> (any op,
    /// including those with immediates or control-flow side effects) and emits
    /// <c>Wacs.Core.Compilation.GeneratedDispatcher.TryDispatch</c> — a single switch over
    /// the opcode ushort that runs each handler with its operands popped off the OpStack
    /// and its immediates read inline from the annotated bytecode stream.
    ///
    /// AOT-safe: no runtime reflection. All introspection happens in the generator at build time.
    /// </summary>
    [Generator]
    public class DispatchGenerator : IIncrementalGenerator
    {
        private const string OpSourceAttrFullName  = "Wacs.Core.Compilation.OpSourceAttribute";
        private const string OpHandlerAttrFullName = "Wacs.Core.Compilation.OpHandlerAttribute";
        private const string ImmAttrFullName       = "Wacs.Core.Compilation.ImmAttribute";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var entries = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => IsCandidateMethod(node),
                    transform: static (ctx, ct) => Extract(ctx, ct))
                .Where(static e => e != null)
                .Collect();

            context.RegisterSourceOutput(entries, (spc, items) =>
            {
                try
                {
                    Emit(spc, items);
                }
                catch (System.Exception ex)
                {
                    spc.AddSource("GeneratedDispatcher.Error.g.cs",
                        SourceText.From(
                            "// <auto-generated/>\n// DispatchGenerator threw:\n// " +
                            ex.GetType().FullName + ": " + ex.Message.Replace("\n", " ") + "\n" +
                            "// Stack:\n// " + (ex.StackTrace ?? "").Replace("\n", "\n// ") + "\n",
                            Encoding.UTF8));
                }
            });
        }

        private static bool IsCandidateMethod(SyntaxNode node)
        {
            if (node is not MethodDeclarationSyntax m) return false;
            if (m.AttributeLists.Count == 0) return false;
            // Quick textual prefilter — avoids semantic model work on the 99% of methods that don't apply.
            foreach (var list in m.AttributeLists)
                foreach (var attr in list.Attributes)
                {
                    var name = attr.Name.ToString();
                    if (name.Contains("OpSource") || name.Contains("OpHandler"))
                        return true;
                }
            return false;
        }

        private static DispatchEntry Extract(GeneratorSyntaxContext ctx, CancellationToken ct)
        {
            var method = (MethodDeclarationSyntax)ctx.Node;
            var symbol = ctx.SemanticModel.GetDeclaredSymbol(method, ct) as IMethodSymbol;
            if (symbol == null) return null;

            AttributeData opAttr = null;
            bool isHandler = false;
            foreach (var a in symbol.GetAttributes())
            {
                var full = a.AttributeClass?.ToDisplayString();
                if (full == OpSourceAttrFullName)  { opAttr = a; isHandler = false; break; }
                if (full == OpHandlerAttrFullName) { opAttr = a; isHandler = true;  break; }
            }
            if (opAttr == null) return null;
            if (opAttr.ConstructorArguments.Length != 1) return null;

            var arg = opAttr.ConstructorArguments[0];
            if (arg.Kind != TypedConstantKind.Enum || arg.Type == null || arg.Value == null) return null;

            int rawValue = System.Convert.ToInt32(arg.Value);
            uint opKey = ComputeOpcodeKey(arg.Type.Name, rawValue);
            string enumName = arg.Type.ToDisplayString();
            string enumMember = arg.Type.GetMembers()
                .OfType<IFieldSymbol>()
                .FirstOrDefault(f => f.HasConstantValue && System.Convert.ToInt32(f.ConstantValue) == rawValue)?.Name
                ?? rawValue.ToString();

            var parameters = ImmutableArray.CreateBuilder<ParamInfo>(symbol.Parameters.Length);
            foreach (var p in symbol.Parameters)
            {
                parameters.Add(ClassifyParam(p, isHandler));
            }

            string returnType = symbol.ReturnType.SpecialType == SpecialType.System_Void
                ? "void"
                : symbol.ReturnType.ToDisplayString();

            string bodyText;
            if (method.Body != null)
            {
                bodyText = method.Body.ToFullString();
            }
            else if (method.ExpressionBody != null)
            {
                // Expression-bodied method: the expression IS the body. For non-void returns,
                // wrap as `{ return expr; }`; for void returns, wrap as `{ expr; }` (the
                // expression must be a statement-type expression such as an invocation).
                string expr = method.ExpressionBody.Expression.ToFullString().Trim();
                bodyText = returnType == "void"
                    ? "{ " + expr + "; }"
                    : "{ return " + expr + "; }";
            }
            else
            {
                return null;
            }

            return new DispatchEntry(opKey, symbol.Name, enumName, enumMember,
                                     parameters.ToImmutable(), returnType, bodyText, isHandler);
        }

        private static ParamInfo ClassifyParam(IParameterSymbol p, bool isHandler)
        {
            string type = p.Type.ToDisplayString();
            // ref int pc — only legal on [OpHandler].
            if (isHandler && p.RefKind == RefKind.Ref && p.Type.SpecialType == SpecialType.System_Int32 && p.Name == "pc")
            {
                return new ParamInfo(p.Name, type, ParamKind.RefPc);
            }
            // ExecContext — only legal on [OpHandler].
            if (isHandler && type == "Wacs.Core.Runtime.ExecContext")
            {
                return new ParamInfo(p.Name, type, ParamKind.Ctx);
            }
            // ReadOnlySpan<byte> code — the raw bytecode span. Useful for variable-length
            // immediates (br_table) where the handler wants to read ad-hoc.
            if (isHandler && type == "System.ReadOnlySpan<byte>")
            {
                return new ParamInfo(p.Name, type, ParamKind.Code);
            }
            // [Imm] → Immediate (must be [OpHandler]).
            if (isHandler)
            {
                foreach (var a in p.GetAttributes())
                {
                    if (a.AttributeClass?.ToDisplayString() == ImmAttrFullName)
                        return new ParamInfo(p.Name, type, ParamKind.Immediate);
                }
            }
            // Default: Stack (popped value).
            return new ParamInfo(p.Name, type, ParamKind.Stack);
        }

        private static uint ComputeOpcodeKey(string enumTypeName, int value)
        {
            // Key layout: (primary << 16) | (secondary & 0xFFFF). Primary-only ops
            // (single-byte opcodes) go in the upper 8 bits of the primary slot so the
            // switch key matches the first stream byte shifted into place. Relaxed-SIMD
            // opcodes (0x100+) overflow a single byte — keeping the secondary as a full
            // u16 lets the whole SimdCode enum fit without truncation collisions.
            uint v = (uint)value & 0xFFFFu;
            return enumTypeName switch
            {
                "OpCode"   => (uint)(((uint)(byte)value) << 16),
                "GcCode"   => (0xFBu << 16) | (uint)(byte)value,
                "ExtCode"  => (0xFCu << 16) | (uint)(byte)value,
                "SimdCode" => (0xFDu << 16) | v,
                "AtomCode" => (0xFEu << 16) | (uint)(byte)value,
                "WacsCode" => (0xFFu << 16) | (uint)(byte)value,
                _ => ((uint)(byte)value) << 16,
            };
        }

        private static void Emit(SourceProductionContext spc, ImmutableArray<DispatchEntry> entries)
        {
            var deduped = new Dictionary<uint, DispatchEntry>();
            foreach (var e in entries)
            {
                if (e == null) continue;
                if (!deduped.ContainsKey(e.OpKey)) deduped[e.OpKey] = e;
            }
            var ordered = deduped.Values.OrderBy(e => e.OpKey).ToList();

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable disable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Buffers.Binary;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Runtime.InteropServices;");
            sb.AppendLine("using Wacs.Core.OpCodes;");
            sb.AppendLine("using Wacs.Core.Runtime;");
            sb.AppendLine("using Wacs.Core.Runtime.Exceptions;");
            // I31Ref (GC proposal) lives here — needed by the i31 handlers.
            sb.AppendLine("using Wacs.Core.Runtime.GC;");
            // TrapException sits in Runtime.Types despite living in the Runtime/Exceptions folder.
            sb.AppendLine("using Wacs.Core.Runtime.Types;");
            // GlobalIdx / FuncIdx / etc. live here — needed whenever a handler body casts an index.
            sb.AppendLine("using Wacs.Core.Types;");
            // ValType (used by ref.null and elsewhere) lives in the Defs sub-namespace.
            sb.AppendLine("using Wacs.Core.Types.Defs;");
            // Handler bodies may qualify sibling helper methods as `ControlHandlers.Xyz` etc.;
            // the generator copies them into GeneratedDispatcher, which lives in
            // Wacs.Core.Compilation, so those short names only resolve via this using.
            sb.AppendLine("using Wacs.Core.Instructions;");
            // Sibling handler classes in sub-namespaces — SIMD, GC — get explicit usings so
            // `VMemoryHandlers.WriteV128` / `StructArrayHandlers.X` resolve.
            sb.AppendLine("using Wacs.Core.Instructions.SIMD;");
            sb.AppendLine("using Wacs.Core.Instructions.GC;");
            // Numeric conversion [OpSource] bodies reference FloatConversion.LongToFloat etc.
            sb.AppendLine("using Wacs.Core.Utilities;");
            sb.AppendLine();
            sb.AppendLine("namespace Wacs.Core.Compilation");
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class GeneratedDispatcher");
            sb.AppendLine("    {");
            // Mirror bit-manipulation constants that live as `private const` inside the instruction
            // classes. Copying the bodies verbatim into this partial class would otherwise fail to
            // resolve these identifiers. Values are identical to the originals — if they're ever
            // changed, update this block to match.
            sb.AppendLine("        // Mirrored from InstF32BinOp");
            sb.AppendLine("        private const uint F32SignMask = 0x8000_0000u;");
            sb.AppendLine("        private const uint F32NotSignMask = ~F32SignMask;");
            sb.AppendLine("        // Mirrored from InstF64BinOp");
            sb.AppendLine("        private const ulong F64SignMask = 0x8000_0000_0000_0000ul;");
            sb.AppendLine("        private const ulong F64NotSignMask = ~F64SignMask;");
            sb.AppendLine("        // Mirrored from InstI32SignExtension");
            sb.AppendLine("        private const uint ByteSign = 0x80u;");
            sb.AppendLine("        private const uint I32ByteExtend = 0xFFFF_FF80u;");
            sb.AppendLine("        private const uint ByteMask = 0xFFu;");
            sb.AppendLine("        private const uint ShortSign = 0x8000u;");
            sb.AppendLine("        private const uint I32ShortExtend = 0xFFFF_8000u;");
            sb.AppendLine("        private const uint ShortMask = 0xFFFFu;");
            sb.AppendLine("        // Mirrored from InstI64SignExtension");
            sb.AppendLine("        private const ulong I64ByteExtend = 0xFFFF_FFFF_FFFF_FF80ul;");
            sb.AppendLine("        private const ulong I64ShortExtend = 0xFFFF_FFFF_FFFF_8000ul;");
            sb.AppendLine("        private const ulong WordSign = 0x8000_0000ul;");
            sb.AppendLine("        private const ulong WordExtend = 0xFFFF_FFFF_8000_0000ul;");
            sb.AppendLine("        private const ulong WordMask = 0xFFFF_FFFFul;");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Dispatches <paramref name=\"op\"/> — key layout is (primary &lt;&lt; 16) | secondary. The");
            sb.AppendLine("        /// secondary is a full u16 so relaxed-SIMD opcodes (0x100+) don't collide with the core");
            sb.AppendLine("        /// FD set when packed. Each handler reads its own immediates inline from <paramref name=\"code\"/>");
            sb.AppendLine("        /// starting at <paramref name=\"pc\"/>, advancing it as it consumes bytes.");
            sb.AppendLine("        /// </summary>");
            // Split the flat set of opcodes by prefix byte. Each prefix group gets
            // its own TryDispatchX method — giving RyuJIT a smaller switch table per
            // method to reason about, rather than one monolithic 300+-case switch
            // that blows past its internal budget thresholds. The outer TryDispatch
            // routes to one of them based on the top 8 bits of the op key.
            var byPrefix = ordered.GroupBy(e => (byte)(e.OpKey >> 16))
                                  .OrderBy(g => g.Key)
                                  .ToList();

            sb.AppendLine("        public static bool TryDispatch(ExecContext ctx, ReadOnlySpan<byte> code, ref int pc, uint op)");
            sb.AppendLine("        {");
            sb.AppendLine("            byte primary = (byte)(op >> 16);");
            sb.AppendLine("            switch (primary)");
            sb.AppendLine("            {");
            foreach (var g in byPrefix)
            {
                sb.AppendLine($"                case 0x{g.Key:X2}: return TryDispatch_{g.Key:X2}(ctx, code, ref pc, op);");
            }
            sb.AppendLine("                default: return false;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();

            foreach (var g in byPrefix)
            {
                EmitSubDispatch(sb, g.Key, g.ToList());
            }
            sb.AppendLine();
            sb.AppendLine("        /// <summary>The number of ops the generator emitted cases for.</summary>");
            sb.AppendLine($"        public const int HandledOpcodeCount = {ordered.Count};");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource("GeneratedDispatcher.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        /// <summary>
        /// Emit a per-prefix sub-dispatch method: <c>TryDispatch_XX</c>. Each owns its
        /// own register bank + immediate-union declaration, so the method's frame stays
        /// independent of the others. Splitting keeps each switch table small enough
        /// that RyuJIT's size heuristics don't kick in and regress performance.
        /// </summary>
        private static void EmitSubDispatch(StringBuilder sb, byte prefix, List<DispatchEntry> entries)
        {
            sb.AppendLine($"        private static bool TryDispatch_{prefix:X2}(ExecContext ctx, ReadOnlySpan<byte> code, ref int pc, uint op)");
            sb.AppendLine("        {");
            sb.AppendLine("            // Stack-operand register bank (reused across cases in this prefix).");
            sb.AppendLine("            int    _a32 = 0, _b32 = 0, _c32 = 0;");
            sb.AppendLine("            uint   _au32 = 0, _bu32 = 0, _cu32 = 0;");
            sb.AppendLine("            long   _a64 = 0, _b64 = 0, _c64 = 0;");
            sb.AppendLine("            ulong  _au64 = 0, _bu64 = 0, _cu64 = 0;");
            sb.AppendLine("            float  _af32 = 0, _bf32 = 0, _cf32 = 0;");
            sb.AppendLine("            double _af64 = 0, _bf64 = 0, _cf64 = 0;");
            sb.AppendLine("            V128   _avec = default, _bvec = default, _cvec = default;");
            sb.AppendLine("            Value  _aval = default, _bval = default, _cval = default;");
            sb.AppendLine("            ImmUnion _imm0 = default, _imm1 = default, _imm2 = default, _imm3 = default;");
            sb.AppendLine("            ImmUnion _imm4 = default, _imm5 = default, _imm6 = default, _imm7 = default;");
            sb.AppendLine("            _ = _a32 + _b32 + _c32; _ = _au32 + _bu32 + _cu32;");
            sb.AppendLine("            _ = _a64 + _b64 + _c64; _ = _au64 + _bu64 + _cu64;");
            sb.AppendLine("            _ = _af32 + _bf32 + _cf32; _ = _af64 + _bf64 + _cf64;");
            sb.AppendLine("            _ = _avec; _ = _bvec; _ = _cvec;");
            sb.AppendLine("            _ = _aval; _ = _bval; _ = _cval;");
            sb.AppendLine("            _ = _imm0; _ = _imm1; _ = _imm2; _ = _imm3;");
            sb.AppendLine("            _ = _imm4; _ = _imm5; _ = _imm6; _ = _imm7;");
            sb.AppendLine();
            sb.AppendLine("            switch (op)");
            sb.AppendLine("            {");
            foreach (var e in entries)
                EmitCase(sb, e);
            sb.AppendLine("                default: return false;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void EmitCase(StringBuilder sb, DispatchEntry e)
        {
            sb.AppendLine($"                case 0x{e.OpKey:X6}: // {e.EnumName}.{e.EnumMember} — {e.MethodName}");
            sb.AppendLine("                {");

            // Per-type usage counters so we know which bank slot to assign each
            // stack / immediate operand.
            var bankCount = new Dictionary<string, int>();
            var immCount = 0;
            var paramSlot = new Dictionary<string, string>();

            string BankSlot(string type)
            {
                var key = type;
                bankCount.TryGetValue(key, out int n);
                bankCount[key] = n + 1;
                var prefix = n switch { 0 => "_a", 1 => "_b", _ => "_c" };
                var suffix = type switch
                {
                    "int"                     => "32",
                    "uint"                    => "u32",
                    "long"                    => "64",
                    "ulong"                   => "u64",
                    "float"                   => "f32",
                    "double"                  => "f64",
                    "Wacs.Core.Runtime.V128"  => "vec",
                    "Wacs.Core.Runtime.Value" => "val",
                    _ => null,
                };
                return suffix == null ? null : prefix + suffix;
            }

            string ImmSlotName() => immCount switch
            {
                0 => "_imm0", 1 => "_imm1", 2 => "_imm2", 3 => "_imm3",
                4 => "_imm4", 5 => "_imm5", 6 => "_imm6", 7 => "_imm7",
                _ => null,
            };

            string ImmField(string type) => type switch
            {
                "int"                    => "S32",
                "uint"                   => "U32",
                "long"                   => "S64",
                "ulong"                  => "U64",
                "float"                  => "F32",
                "double"                 => "F64",
                "byte"                   => "U8",
                "Wacs.Core.Runtime.V128" => "V128",
                _                        => null,
            };

            // 1. Read immediates FIRST — assign each to a shared ImmUnion slot.
            foreach (var p in e.Parameters.Where(p => p.Kind == ParamKind.Immediate))
            {
                var reader = TypeToImmReader(p.Type);
                var field = ImmField(p.Type);
                var slot = ImmSlotName();
                if (reader == null || field == null || slot == null)
                {
                    sb.AppendLine($"                    // skipped — unsupported [Imm] type {p.Type}");
                    sb.AppendLine("                    return false;");
                    sb.AppendLine("                }");
                    return;
                }
                sb.AppendLine($"                    {slot}.{field} = StreamReader.{reader}(code, ref pc);");
                paramSlot[p.Name] = $"{slot}.{field}";
                immCount++;
            }

            // 2. Pop stack operands in REVERSE parameter order into typed bank slots.
            var stackParams = e.Parameters.Where(p => p.Kind == ParamKind.Stack).ToList();
            // Bank slot assignment mirrors parameter order (left-to-right) even though
            // pops happen in reverse; we pop into the correct slot directly.
            var stackSlots = new string[stackParams.Count];
            for (int i = 0; i < stackParams.Count; i++)
            {
                var slot = BankSlot(stackParams[i].Type);
                if (slot == null)
                {
                    sb.AppendLine($"                    // skipped — unsupported stack parameter type {stackParams[i].Type}");
                    sb.AppendLine("                    return false;");
                    sb.AppendLine("                }");
                    return;
                }
                stackSlots[i] = slot;
                paramSlot[stackParams[i].Name] = slot;
            }
            for (int i = stackParams.Count - 1; i >= 0; i--)
            {
                var p = stackParams[i];
                var popOp = TypeToPop(p.Type);
                if (popOp == null)
                {
                    sb.AppendLine($"                    // skipped — unsupported stack parameter type {p.Type}");
                    sb.AppendLine("                    return false;");
                    sb.AppendLine("                }");
                    return;
                }
                sb.AppendLine($"                    {stackSlots[i]} = ctx.OpStack.{popOp}();");
            }

            // 3. Emit the body as a static local function. Args come from bank/imm
            //    slots instead of per-case named locals — the JIT will (usually)
            //    inline the local function, leaving handler bodies referencing the
            //    shared slots directly. Keeping the local-function wrapper preserves
            //    handler-body portability (the bodies still look like the polymorphic
            //    methods they came from).
            var localSigParts = e.Parameters.Select(p => p.Kind switch
            {
                ParamKind.Ctx       => $"ExecContext {p.Name}",
                ParamKind.RefPc     => $"ref int {p.Name}",
                ParamKind.Code      => $"System.ReadOnlySpan<byte> {p.Name}",
                _                   => $"{p.Type} {p.Name}",
            });
            string paramList = string.Join(", ", localSigParts);
            string body = IndentBody(e.Body, "                    ");
            sb.AppendLine($"                    static {e.ReturnType} __Op({paramList})");
            sb.AppendLine(body);

            // 4. Call the local function with bank/imm slots as the args.
            var argList = string.Join(", ", e.Parameters.Select(p => p.Kind switch
            {
                ParamKind.Ctx   => "ctx",
                ParamKind.RefPc => "ref pc",
                ParamKind.Code  => "code",
                _               => paramSlot[p.Name],
            }));

            if (e.ReturnType == "void")
            {
                sb.AppendLine($"                    __Op({argList});");
            }
            else
            {
                var pushOp = TypeToPush(e.ReturnType);
                if (pushOp == null)
                {
                    sb.AppendLine($"                    // skipped — unsupported return type {e.ReturnType}");
                    sb.AppendLine("                    return false;");
                    sb.AppendLine("                }");
                    return;
                }
                sb.AppendLine($"                    ctx.OpStack.{pushOp}(__Op({argList}));");
            }

            sb.AppendLine("                    return true;");
            sb.AppendLine("                }");
        }

        private static string IndentBody(string body, string indent)
        {
            var lines = body.Replace("\r\n", "\n").Split('\n');
            var sb = new StringBuilder();
            for (int i = 0; i < lines.Length; i++)
            {
                var line = lines[i];
                if (line.Length == 0 && i == lines.Length - 1) continue;
                sb.Append(indent);
                sb.Append(line);
                if (i < lines.Length - 1) sb.Append('\n');
            }
            return sb.ToString();
        }

        private static string TypeToPop(string t) => t switch
        {
            "int"    => "PopI32",
            "uint"   => "PopU32",
            "long"   => "PopI64",
            "ulong"  => "PopU64",
            "float"  => "PopF32",
            "double" => "PopF64",
            // Type-agnostic stack values (Value struct) — used by variable + parametric ops.
            "Wacs.Core.Runtime.Value" => "PopAny",
            // V128 — 128-bit SIMD value.
            "Wacs.Core.Runtime.V128" => "PopV128",
            _ => null,
        };

        private static string TypeToPush(string t) => t switch
        {
            "int"    => "PushI32",
            "uint"   => "PushU32",
            "long"   => "PushI64",
            "ulong"  => "PushU64",
            "float"  => "PushF32",
            "double" => "PushF64",
            "Wacs.Core.Runtime.Value" => "PushValue",
            "Wacs.Core.Runtime.V128" => "PushV128",
            _ => null,
        };

        private static string TypeToImmReader(string t) => t switch
        {
            "int"    => "ReadS32",
            "uint"   => "ReadU32",
            "long"   => "ReadS64",
            "ulong"  => "ReadU64",
            "float"  => "ReadF32",
            "double" => "ReadF64",
            "byte"   => "ReadU8",
            "Wacs.Core.Runtime.V128" => "ReadV128",
            _ => null,
        };

        private enum ParamKind { Stack, Immediate, Ctx, RefPc, Code }

        private sealed class DispatchEntry
        {
            public readonly uint OpKey;
            public readonly string MethodName;
            public readonly string EnumName;
            public readonly string EnumMember;
            public readonly ImmutableArray<ParamInfo> Parameters;
            public readonly string ReturnType;
            public readonly string Body;
            public readonly bool IsHandler;

            public DispatchEntry(uint opKey, string methodName, string enumName, string enumMember,
                                 ImmutableArray<ParamInfo> parameters, string returnType, string body,
                                 bool isHandler)
            {
                OpKey = opKey;
                MethodName = methodName;
                EnumName = enumName;
                EnumMember = enumMember;
                Parameters = parameters;
                ReturnType = returnType;
                Body = body;
                IsHandler = isHandler;
            }
        }

        private readonly struct ParamInfo
        {
            public readonly string Name;
            public readonly string Type;
            public readonly ParamKind Kind;
            public ParamInfo(string name, string type, ParamKind kind) { Name = name; Type = type; Kind = kind; }
        }
    }
}
