// Generated by `wit-bindgen` 0.30.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace LstWorldWorld.wit.imports.local.lst
{
    public static class EnvInterop {

        internal static class WriteWasmInterop
        {
            [DllImport("local:lst/env", EntryPoint = "write"), WasmImportLinkage]
            internal static extern void wasmImportWrite(nint p0, int p1);

        }

        public  static unsafe void Write(byte[] data)
        {

            void* buffer = stackalloc byte[(data).Length];
            data.AsSpan<byte>().CopyTo(new Span<byte>(buffer, data.Length));
            WriteWasmInterop.wasmImportWrite((int)buffer, (data).Length);

            //TODO: free alloc handle (interopString) if exists
        }

        internal static class ReadWasmInterop
        {
            [DllImport("local:lst/env", EntryPoint = "read"), WasmImportLinkage]
            internal static extern void wasmImportRead(nint p0);

        }

        public  static unsafe byte[] Read()
        {

            var retArea = new uint[2];
            fixed (uint* retAreaByte0 = &retArea[0])
            {
                var ptr = (nint)retAreaByte0;
                ReadWasmInterop.wasmImportRead(ptr);

                var array = new byte[BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4))];
                new Span<byte>((void*)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 0), 4))), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4))).CopyTo(new Span<byte>(array));
                return array;
            }

            //TODO: free alloc handle (interopString) if exists
        }

    }
}
