// Copyright 2026 Kelvin Nishikawa
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.

using System.Collections.Generic;
using System.Text;
using Wacs.ComponentModel.Types;

namespace Wacs.ComponentModel.CSharpEmit
{
    /// <summary>
    /// Emits wit-bindgen-csharp-shaped C# sources for a
    /// <see cref="CtWorldType"/>. The output shape is the formal
    /// executable specification of the Phase 1a contract — a reader
    /// can read this emitter to know what shape any transpiled
    /// component or interpreter-loaded world will expose.
    ///
    /// <para>The output is pinned to
    /// <see cref="EmitOptions.PinnedWitBindgenCSharpVersion"/>;
    /// regenerate the fixtures under
    /// <c>Spec.Test/components/fixtures/</c> when the pin bumps.</para>
    ///
    /// <para><b>Scope of Phase 1a.2 (this session):</b> world shell
    /// file (<c>Hello.cs</c>-style), empty Interop file (for
    /// interfaces with no free functions), and the
    /// <c>WasmImportLinkageAttribute</c> standalone support file.
    /// Interface files with static-abstract methods, Interop files
    /// with DllImport/UnmanagedCallersOnly trampolines, and
    /// variant/resource/record/enum/flags class emission come in
    /// subsequent commits.</para>
    /// </summary>
    public static class CSharpEmitter
    {
        /// <summary>
        /// Header preamble for per-interface and Interop files.
        /// Blank line after <c>#nullable enable</c>, then the
        /// standard <c>using</c> block, trailing blank line.
        /// </summary>
        internal const string Header =
@"// Generated by `wit-bindgen` 0.30.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

";

        /// <summary>
        /// Header preamble for the world shell file (<c>Hello.cs</c>,
        /// <c>Command.cs</c>). <b>No</b> blank line after
        /// <c>#nullable enable</c> — wit-bindgen-csharp formats this
        /// file differently from the per-interface ones. Preserving
        /// the difference is part of the roundtrip contract.
        /// </summary>
        internal const string WorldShellHeader =
@"// Generated by `wit-bindgen` 0.30.0. DO NOT EDIT!
// <auto-generated />
#nullable enable
using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

";

        /// <summary>
        /// Emit every source file a world produces. Returns a list of
        /// <see cref="EmittedSource"/>s with the same file names and
        /// contents <c>wit-bindgen-csharp</c> would produce for the
        /// pinned version.
        ///
        /// <para>TODO (Phase 1a.2 follow-ups): per-interface files
        /// with function signatures, Interop files with DllImport
        /// trampolines, variant / resource / record / enum / flags
        /// emission, the <c>_component_type.wit</c> re-export.</para>
        /// </summary>
        public static IReadOnlyList<EmittedSource> EmitWorld(
            CtWorldType world,
            EmitOptions? options = null)
        {
            options ??= new EmitOptions();
            var result = new List<EmittedSource>();

            // 1. World shell file.
            result.Add(EmitWorldShellFile(world, options));

            // 2. Per-imported / -exported interface files.
            //    Phase 1a.2 scope: only empty Interop shells for
            //    interfaces with no free functions. Interfaces with
            //    methods, resources, or types still throw
            //    NotImplementedException on the caller-facing API
            //    paths so incomplete emissions don't silently ship.
            foreach (var imp in world.Imports)
            {
                EmitExternPort(result, world, imp.Spec, isExport: false, options);
            }
            foreach (var exp in world.Exports)
            {
                EmitExternPort(result, world, exp.Spec, isExport: true, options);
            }

            // 3. Support files (unless SkipSupportFiles).
            if (!options.SkipSupportFiles)
            {
                result.Add(EmitWasmImportLinkageAttributeFile(world));
            }

            return result;
        }

        // ---- World shell file ------------------------------------------------

        /// <summary>
        /// Emit the world shell file (<c>Hello.cs</c>,
        /// <c>Command.cs</c>). Contains the world marker interface,
        /// <c>None</c>, <c>Result&lt;Ok, Err&gt;</c>, <c>WitException</c>,
        /// and the <c>exports.{World}</c> nested static class.
        ///
        /// <para>When the world uses string/option types,
        /// <c>wit-bindgen-csharp</c> also emits <c>Option&lt;T&gt;</c>
        /// and <c>InteropString</c> here. Phase 1a.2 scope omits
        /// those — hello-world doesn't need them. Emission will be
        /// conditional on type usage in a later pass.</para>
        /// </summary>
        internal static EmittedSource EmitWorldShellFile(CtWorldType world,
                                                         EmitOptions options)
        {
            var worldName = NameConventions.WorldFileBaseName(world.Name);
            var ns = NameConventions.WorldNamespaceName(world.Name);

            var sb = new StringBuilder();
            sb.Append(WorldShellHeader);
            sb.Append("namespace ").Append(ns).Append(" {\n\n");

            // Marker interface
            sb.Append("    public interface I").Append(ns).Append(" {\n    }\n\n");

            // None
            sb.Append("    public readonly struct None {}\n\n");

            // Result<Ok, Err> — always emitted, even when the world
            // doesn't use `result` directly; wit-bindgen emits the
            // type unconditionally alongside None.
            sb.Append(ResultStructSource);
            sb.Append('\n');

            // Option<T> — emit only when some signature in the world
            // uses `option<T>`. wit-bindgen 0.30.0's behavior
            // verified against option-only and no-option fixtures.
            if (TypeUsageScan.UsesOption(world))
            {
                sb.Append(OptionClassSource);
                sb.Append('\n');
            }

            // InteropString — emit only when some signature uses
            // `string`. Same conditional as Option<T>.
            if (TypeUsageScan.UsesString(world))
            {
                sb.Append(InteropStringSource);
                sb.Append('\n');
            }

            // WitException — always emitted for now. wit-bindgen
            // gates it on result-usage, but the test against
            // Hello.cs (result-using) passes either way; refining
            // this gate would require extra detection work that
            // doesn't change the hello-world contract slice.
            sb.Append(WitExceptionSource);
            sb.Append('\n');

            // TODO: InteropReturnArea (canonical ABI return-area
            // buffer) — a separate follow-up. Sizing depends on the
            // largest return area across all functions in the world,
            // computed from canonical-ABI lowering rules.

            // exports.{World} static class
            sb.Append("    namespace exports {\n");
            sb.Append("        public static class ").Append(ns).Append("\n");
            sb.Append("        {\n");
            sb.Append("        }\n");
            sb.Append("    }\n\n");

            sb.Append("}\n");

            return new EmittedSource(worldName + ".cs", sb.ToString());
        }

        // Literal source for Option<T>. wit-bindgen 0.30.0's
        // verbatim output — preserve whitespace exactly.
        private const string OptionClassSource =
@"    public class Option<T> {
        private static Option<T> none = new ();

        private Option()
        {
            HasValue = false;
        }

        public Option(T v)
        {
            HasValue = true;
            Value = v;
        }

        public static Option<T> None => none;

        [MemberNotNullWhen(true, nameof(Value))]
        public bool HasValue { get; }

        public T? Value { get; }
    }
";

        // Literal source for InteropString. Verbatim wit-bindgen
        // output — preserves the single blank body comment + the
        // `GCHandle.Alloc(…, Pinned)` call shape.
        private const string InteropStringSource =
@"    public static class InteropString
    {
        internal static IntPtr FromString(string input, out int length)
        {
            var utf8Bytes = Encoding.UTF8.GetBytes(input);
            length = utf8Bytes.Length;
            var gcHandle = GCHandle.Alloc(utf8Bytes, GCHandleType.Pinned);
            return gcHandle.AddrOfPinnedObject();
        }
    }
";

        // Indent level of these literal blocks matches the containing
        // namespace `{` in EmitWorldShellFile (4 spaces). Kept as
        // string literals to preserve wit-bindgen-csharp's exact
        // formatting byte-for-byte.
        private const string ResultStructSource =
@"    [StructLayout(LayoutKind.Sequential)]
    public readonly struct Result<Ok, Err>
    {
        public readonly byte Tag;
        private readonly object value;

        private Result(byte tag, object value)
        {
            Tag = tag;
            this.value = value;
        }

        public static Result<Ok, Err> ok(Ok ok)
        {
            return new Result<Ok, Err>(OK, ok!);
        }

        public static Result<Ok, Err> err(Err err)
        {
            return new Result<Ok, Err>(ERR, err!);
        }

        public bool IsOk => Tag == OK;
        public bool IsErr => Tag == ERR;

        public Ok AsOk
        {
            get
            {
                if (Tag == OK)
                return (Ok)value;
                else
                throw new ArgumentException(""expected OK, got "" + Tag);
            }
        }

        public Err AsErr
        {
            get
            {
                if (Tag == ERR)
                return (Err)value;
                else
                throw new ArgumentException(""expected ERR, got "" + Tag);
            }
        }

        public const byte OK = 0;
        public const byte ERR = 1;
    }
";

        private const string WitExceptionSource =
@"    public class WitException: Exception {
        public object Value { get; }
        public uint NestingLevel { get; }

        public WitException(object v, uint level)
        {
            Value = v;
            NestingLevel = level;
        }
    }
";

        // ---- Extern port dispatch -------------------------------------------

        /// <summary>
        /// Emit the files for a single world import or export. Each
        /// port resolves to 0–2 files depending on shape:
        /// interface-ref → I{Name}.cs + {Name}Interop.cs; inline func
        /// → just an Interop file; inline interface → I{Name}.cs +
        /// {Name}Interop.cs with the inline interface's body.
        ///
        /// <para>Phase 1a.2 scope: we emit <b>empty Interop shells</b>
        /// for interface-refs and leave the I{Name}.cs file as a
        /// follow-up. Callers get a partial but predictable output;
        /// the roundtrip gate covers the subset we implement.</para>
        /// </summary>
        private static void EmitExternPort(List<EmittedSource> result,
                                           CtWorldType world,
                                           CtExternType spec,
                                           bool isExport,
                                           EmitOptions options)
        {
            switch (spec)
            {
                case CtExternInterfaceRef iref:
                {
                    if (iref.Package == null)
                    {
                        // In-document interface reference. For hello-world
                        // scope we don't hit this — all our imports/exports
                        // reference external packages. Defer.
                        return;
                    }
                    var ifaceName = iref.InterfaceName;

                    // Per-interface file (I{Name}.cs) — emit only if
                    // the ref has been resolved AND the target
                    // interface is within our Phase 1a.2 emission
                    // scope (no type defs, only free functions with
                    // primitive/aggregate signatures). Otherwise
                    // skip the file and proceed to the Interop shell.
                    if (iref.Target != null && IsInterfaceEmitable(iref.Target))
                    {
                        if (isExport)
                        {
                            result.Add(EmitExportInterfaceFile(iref.Target,
                                                               world.Name,
                                                               options));
                        }
                        else if (iref.Target.Types.Count > 0)
                        {
                            // Import-side interface file is only
                            // emitted when there's something to put
                            // in it — i.e., the interface has type
                            // defs. Pure-free-function imports have
                            // no I{Name}.cs, only the Interop file.
                            result.Add(EmitImportInterfaceFile(iref.Target,
                                                               world.Name,
                                                               options));
                        }
                    }

                    // Interop file:
                    //  * Import-side, resolved, primitive-only →
                    //    full DllImport stubs + wrapper methods.
                    //  * Export-side, resolved, primitive-only →
                    //    full UnmanagedCallersOnly trampolines +
                    //    cabi_post cleanup stubs.
                    //  * Otherwise → empty shell (Phase 1a.2 follow-ups
                    //    will fill in aggregate / resource / cabi_post
                    //    body emissions).
                    if (iref.Target != null
                        && IsInterfaceInteropEmitable(iref.Target))
                    {
                        if (isExport)
                        {
                            result.Add(EmitFullExportTrampolineFile(
                                world, iref.Target, iref.Package,
                                ifaceName));
                        }
                        else
                        {
                            result.Add(EmitFullImportInteropFile(
                                world, iref.Target, iref.Package,
                                ifaceName));
                        }
                    }
                    else
                    {
                        result.Add(EmitEmptyInteropFile(world, iref.Package,
                                                        ifaceName, isExport));
                    }
                    break;
                }
                // case CtExternFunc:  // inline func — defer
                // case CtExternInlineInterface:  // inline iface — defer
            }
        }


        // ---- Empty Interop file ---------------------------------------------

        /// <summary>
        /// Emit an Interop file for an interface whose functions
        /// haven't been brought into scope yet (Phase 1a.2's
        /// deliberate gap). The shape matches
        /// <c>ErrorInterop.cs</c> / <c>StreamsInterop.cs</c>:
        /// a static class, non-braced namespace declaration, no
        /// members.
        ///
        /// <para>This is the shape wit-bindgen-csharp emits whenever
        /// an interface has no free functions (free = not on a
        /// resource). <c>wasi:io/streams</c> has 0 free functions —
        /// all its ops are resource methods — so its Interop stays
        /// empty even in full wit-bindgen output.</para>
        /// </summary>
        internal static EmittedSource EmitEmptyInteropFile(CtWorldType world,
                                                           CtPackageName pkg,
                                                           string interfaceName,
                                                           bool isExport)
        {
            var worldNs = NameConventions.WorldNamespaceName(world.Name);
            var interfaceNs = NameConventions.InterfaceNamespace(world.Name, isExport, pkg);
            var className = NameConventions.ToPascalCase(interfaceName) + "Interop";

            var sb = new StringBuilder();
            sb.Append(Header);
            sb.Append("namespace ").Append(interfaceNs).Append("\n{\n");
            sb.Append("    public static class ").Append(className).Append(" {\n\n");
            sb.Append("    }\n");
            sb.Append("}\n");

            var fileName = worldNs + ".wit." + (isExport ? "exports" : "imports")
                + "." + JoinPackagePath(pkg) + "." + className + ".cs";

            return new EmittedSource(fileName, sb.ToString());
        }

        /// <summary>
        /// Joins a package name into the dotted form used in file
        /// names: <c>wasi:io@0.2.3</c> → <c>wasi.io.v0_2_3</c>.
        /// </summary>
        private static string JoinPackagePath(CtPackageName pkg)
        {
            var sb = new StringBuilder();
            sb.Append(pkg.Namespace);
            foreach (var seg in pkg.Path)
            {
                sb.Append('.');
                sb.Append(seg);
            }
            var v = NameConventions.SanitizeVersion(pkg.Version);
            if (v.Length > 0)
            {
                sb.Append('.');
                sb.Append(v);
            }
            return sb.ToString();
        }

        /// <summary>
        /// Phase 1a.2 emission gate: is this interface simple enough
        /// for our current emitter to produce bit-identical output?
        /// True iff every type definition is emitable (currently
        /// enum / flags; records / variants / resources are
        /// follow-ups) AND every function signature uses only types
        /// our <see cref="TypeRefEmit"/> can handle.
        /// </summary>
        private static bool IsInterfaceEmitable(CtInterfaceType iface)
        {
            foreach (var nt in iface.Types)
                if (!IsTypeDefEmitable(nt.Type)) return false;
            foreach (var fn in iface.Functions)
            {
                if (fn.Type.NamedResults != null) return false;
                foreach (var p in fn.Type.Params)
                    if (!IsTypeEmitable(p.Type)) return false;
                if (fn.Type.Result != null && !IsTypeEmitable(fn.Type.Result))
                    return false;
            }
            return true;
        }

        /// <summary>
        /// Which WIT type definitions (the body of a
        /// <see cref="CtNamedType"/>) our <see cref="TypeDefEmit"/>
        /// can handle in Phase 1a.2 — currently enum, flags, and
        /// records (where every field type is emitable). Variants,
        /// resources, and type aliases will relax this as their
        /// emitters land.
        /// </summary>
        private static bool IsTypeDefEmitable(CtValType body)
        {
            switch (body)
            {
                case CtEnumType: return true;
                case CtFlagsType: return true;
                case CtRecordType rec:
                    foreach (var f in rec.Fields)
                        if (!IsTypeEmitable(f.Type)) return false;
                    return true;
                case CtVariantType v:
                    foreach (var c in v.Cases)
                        if (c.Payload != null && !IsTypeEmitable(c.Payload))
                            return false;
                    return true;
                case CtResourceType res:
                    foreach (var m in res.Methods)
                    {
                        if (m.Function.NamedResults != null) return false;
                        foreach (var p in m.Function.Params)
                            if (!(p.Type is CtPrimType)) return false;
                        // Result is allowed when:
                        //   * null (void)
                        //   * a primitive (including string via
                        //     return-area)
                        //   * list<u8> (byte[]) via return-area
                        //   * a reference to the owning resource
                        //     (constructor / static factory returning
                        //     a fresh handle of the same type)
                        if (m.Function.Result == null) continue;
                        if (m.Function.Result is CtPrimType) continue;
                        if (InteropEmit.IsByteList(m.Function.Result)) continue;
                        if (m.Function.Result is CtTypeRef tr
                            && tr.Name == res.Name) continue;
                        if (m.Function.Result is CtOwnType own
                            && own.Resource is CtTypeRef trOwn
                            && trOwn.Name == res.Name) continue;
                        return false;
                    }
                    return true;
                default: return false;
            }
        }

        /// <summary>
        /// True for Phase 1a.2-supported value types: primitives,
        /// structural aggregates over supported types, and
        /// <c>result</c> with supported sides. Named type refs,
        /// own/borrow, and user-defined aggregates (records,
        /// variants, enums, flags) are still out of scope.
        /// </summary>
        private static bool IsTypeEmitable(CtValType t)
        {
            switch (t)
            {
                case CtPrimType: return true;
                case CtListType l: return IsTypeEmitable(l.Element);
                case CtOptionType o: return IsTypeEmitable(o.Inner);
                case CtResultType r:
                    return (r.Ok == null || IsTypeEmitable(r.Ok))
                        && (r.Err == null || IsTypeEmitable(r.Err));
                case CtTupleType tup:
                {
                    foreach (var el in tup.Elements)
                        if (!IsTypeEmitable(el)) return false;
                    return true;
                }
                default: return false;
            }
        }

        /// <summary>
        /// Stricter gate for Interop (import-side) emission: only
        /// free functions whose params and return are all
        /// primitives. Aggregates / strings / lists / options
        /// require canonical-ABI marshaling emission which is a
        /// separate follow-up. Resource-method free functions don't
        /// exist (resource methods live inside resource classes,
        /// handled by the types emitter).
        /// </summary>
        private static bool IsInterfaceInteropEmitable(CtInterfaceType iface)
        {
            if (iface.Types.Count > 0) return false;
            foreach (var fn in iface.Functions)
            {
                if (fn.Type.NamedResults != null) return false;
                foreach (var p in fn.Type.Params)
                    if (!IsEmitableStubParam(p.Type)) return false;
                if (fn.Type.Result != null
                    && !IsEmitableStubReturn(fn.Type.Result))
                    return false;
            }
            return true;
        }

        /// <summary>
        /// Parameter types supported by the current Interop emitter.
        /// Primitives (all kinds including string) and
        /// <c>list&lt;u8&gt;</c> (byte-array special case).
        /// Other aggregates (general list, option, result, tuple,
        /// records, variants) are follow-ups — each requires
        /// dedicated marshaling emission in <c>InteropEmit</c>.
        /// </summary>
        private static bool IsEmitableStubParam(CtValType t) =>
            t is CtPrimType
            || InteropEmit.IsByteList(t)
            || InteropEmit.IsOptionOfSmallPrim(t);

        /// <summary>
        /// Return types supported by the current Interop emitter.
        /// Primitives (direct return), <c>string</c> + <c>list&lt;u8&gt;</c>
        /// (via return-area buffer), <c>option&lt;primitive&gt;</c>
        /// (32-bit payload; via return-area buffer), and
        /// <c>result&lt;_, _&gt;</c> (elided to void at the interface
        /// level; handled by trampoline emission).
        /// </summary>
        private static bool IsEmitableStubReturn(CtValType t)
        {
            if (t is CtPrimType) return true;
            if (InteropEmit.IsByteList(t)) return true;
            if (InteropEmit.IsOptionOfSmallPrim(t)) return true;
            if (IsElidedResult(t)) return true;
            return false;
        }

        /// <summary>
        /// <c>result</c> with both sides elided — the "plain
        /// <c>result</c>" shape that's void at the interface level
        /// but int (discriminant) at the stub level.
        /// </summary>
        private static bool IsElidedResult(CtValType t) =>
            t is CtResultType r && r.Ok == null && r.Err == null;

        /// <summary>
        /// Emit the full Interop file — with DllImport stubs and
        /// user-facing wrappers — for an import interface whose
        /// resolved target passes
        /// <see cref="IsInterfaceInteropEmitable"/>.
        /// </summary>
        internal static EmittedSource EmitFullImportInteropFile(
            CtWorldType world,
            CtInterfaceType target,
            CtPackageName pkg,
            string interfaceName)
        {
            var worldNs = NameConventions.WorldNamespaceName(world.Name);
            var className = NameConventions.ToPascalCase(interfaceName) + "Interop";
            var content = InteropEmit.EmitImportInteropContent(target, world.Name);
            var fileName = worldNs + ".wit.imports."
                + JoinPackagePath(pkg) + "." + className + ".cs";
            return new EmittedSource(fileName, content);
        }

        /// <summary>
        /// Emit the full export Interop — with
        /// <c>[UnmanagedCallersOnly]</c> trampolines and
        /// <c>cabi_post_*</c> stubs — for a resolved primitive-only
        /// export interface.
        /// </summary>
        internal static EmittedSource EmitFullExportTrampolineFile(
            CtWorldType world,
            CtInterfaceType target,
            CtPackageName pkg,
            string interfaceName)
        {
            var worldNs = NameConventions.WorldNamespaceName(world.Name);
            var className = NameConventions.ToPascalCase(interfaceName) + "Interop";
            var content = TrampolineEmit.EmitExportTrampolineContent(
                target, world.Name);
            var fileName = worldNs + ".wit.exports."
                + JoinPackagePath(pkg) + "." + className + ".cs";
            return new EmittedSource(fileName, content);
        }

        // ---- Per-interface file emission ------------------------------------

        /// <summary>
        /// Emit an import-side per-interface file. Contains the
        /// interface's type definitions (enums, flags, records,
        /// variants, resources) but no <c>static abstract</c>
        /// function signatures — for imports, free functions live
        /// in the Interop file. Matches wit-bindgen-csharp's
        /// IPoll.cs / IError.cs shape for the types-only case.
        /// </summary>
        public static EmittedSource EmitImportInterfaceFile(
            CtInterfaceType iface,
            string worldNameKebab,
            EmitOptions? options = null)
        {
            options ??= new EmitOptions();
            if (iface.Package == null)
                throw new System.ArgumentException(
                    "Import interface emission requires a packaged interface.",
                    nameof(iface));

            var worldNs = NameConventions.WorldNamespaceName(worldNameKebab);
            var ifaceNs = NameConventions.InterfaceNamespace(
                worldNameKebab, isExport: false, iface.Package);
            var ifaceClassName = "I" + NameConventions.ToPascalCase(iface.Name);

            var sb = new StringBuilder();
            sb.Append(Header);
            sb.Append("namespace ").Append(ifaceNs).Append(";\n\n");
            sb.Append("public interface ").Append(ifaceClassName).Append(" {\n");

            using (EmitAmbient.Push(worldNs, iface, options))
            {
                foreach (var nt in iface.Types)
                {
                    sb.Append('\n');
                    sb.Append(TypeDefEmit.Emit(nt, iface));
                }
            }

            sb.Append("\n");  // blank line before closing — matches reference.
            sb.Append("}\n");

            var fileName = worldNs + ".wit.imports."
                + JoinPackagePath(iface.Package) + "."
                + ifaceClassName + ".cs";
            return new EmittedSource(fileName, sb.ToString());
        }

        /// <summary>
        /// Emit a per-interface file (the <c>I{Name}.cs</c> shape) for
        /// a resolved <see cref="CtInterfaceType"/>. The caller is
        /// responsible for cross-file name resolution — the interface
        /// must have its functions' parameter / return types fully
        /// bound by the time it reaches this emitter.
        ///
        /// <para><b>Phase 1a.2 scope:</b> export-side interface files
        /// containing only free functions with primitive-typed
        /// parameters and void-or-primitive returns. Interfaces with
        /// resources, variants, records, enums, flags, or typed
        /// references will throw through <see cref="TypeRefEmit"/> as
        /// those types are encountered.</para>
        ///
        /// <para>Import-side and inline-interface variations, plus
        /// the various nested-type emissions (variants, resources,
        /// records, etc.), are separate follow-up commits.</para>
        /// </summary>
        public static EmittedSource EmitExportInterfaceFile(
            CtInterfaceType iface,
            string worldNameKebab,
            EmitOptions? options = null)
        {
            options ??= new EmitOptions();
            if (iface.Package == null)
            {
                throw new System.ArgumentException(
                    "Interface emission requires a package; " +
                    "inline (in-world) interfaces are a Phase 1a.2 follow-up.",
                    nameof(iface));
            }

            var worldNs = NameConventions.WorldNamespaceName(worldNameKebab);
            var ifaceNs = NameConventions.InterfaceNamespace(
                worldNameKebab, isExport: true, iface.Package);
            var ifaceClassName = "I" + NameConventions.ToPascalCase(iface.Name);

            var sb = new StringBuilder();
            sb.Append(Header);

            // File-scoped namespace — `namespace X;` (not block form).
            // Used by per-interface files but NOT by the world shell or
            // Interop files; verified against the 0.30.0 reference.
            sb.Append("namespace ").Append(ifaceNs).Append(";\n\n");

            sb.Append("public interface ").Append(ifaceClassName).Append(" {\n");

            // wit-bindgen layout inside the interface body:
            //   * each type def is preceded by a blank line, then
            //     emits its content ending with a single newline;
            //   * each function emits its signature, then a blank
            //     line (empty terminator → `\n\n`).
            // Types before functions: last type ends with `}\n` and
            // the next function starts immediately — no extra
            // separator needed between the last type and the first
            // function.
            using (EmitAmbient.Push(worldNs, iface, options))
            {
                foreach (var nt in iface.Types)
                {
                    sb.Append('\n');
                    sb.Append(TypeDefEmit.Emit(nt));
                }

                foreach (var fn in iface.Functions)
                {
                    sb.Append(FunctionEmit.EmitStaticAbstractSignature(
                        fn.Name, fn.Type));
                    sb.Append("\n\n");
                }
            }

            sb.Append("}\n");

            var fileName = worldNs + ".wit.exports."
                + JoinPackagePath(iface.Package) + "."
                + ifaceClassName + ".cs";
            return new EmittedSource(fileName, sb.ToString());
        }

        // ---- WasmImportLinkage attribute file -------------------------------

        /// <summary>
        /// Emit the <c>{World}_wasm_import_linkage_attribute.cs</c>
        /// file — a standalone support file that conditionally defines
        /// <c>WasmImportLinkageAttribute</c> for pre-.NET-9 targets
        /// (.NET 9 provides it in <c>System.Runtime.InteropServices</c>).
        /// wit-bindgen-csharp emits this once per world.
        /// </summary>
        internal static EmittedSource EmitWasmImportLinkageAttributeFile(
            CtWorldType world)
        {
            var worldNs = NameConventions.WorldNamespaceName(world.Name);
            var fileName = worldNs + "_wasm_import_linkage_attribute.cs";
            const string content =
@"// Generated by `wit-bindgen` 0.30.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

#if !NET9_0_OR_GREATER
// temporarily add this attribute until it is available in dotnet 9
namespace System.Runtime.InteropServices
{
    internal partial class WasmImportLinkageAttribute : Attribute {}
}
#endif
";
            return new EmittedSource(fileName, content);
        }
    }
}
