// Generated by `wit-bindgen` 0.30.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace RecWorldWorld.wit.imports.local.rec
{
    public static class EnvInterop {

        internal static class TranslateWasmInterop
        {
            [DllImport("local:rec/env", EntryPoint = "translate"), WasmImportLinkage]
            internal static extern void wasmImportTranslate(int p0, int p1, int p2, int p3, nint p4);

        }

        public  static unsafe global::RecWorldWorld.wit.imports.local.rec.IEnv.Point Translate(global::RecWorldWorld.wit.imports.local.rec.IEnv.Point p, int dx, int dy)
        {

            var retArea = new uint[2];
            fixed (uint* retAreaByte0 = &retArea[0])
            {
                var ptr = (nint)retAreaByte0;
                TranslateWasmInterop.wasmImportTranslate(unchecked((int)(p.x)), unchecked((int)(p.y)), dx, dy, ptr);
                return new global::RecWorldWorld.wit.imports.local.rec.IEnv.Point (
                unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 0), 4)))), unchecked((uint)(BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4)))));
            }

            //TODO: free alloc handle (interopString) if exists
        }

    }
}
