// Generated by `wit-bindgen` 0.30.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace SrWorldWorld.wit.imports.local.sr
{
    public static class EnvInterop {

        internal static class GetNameWasmInterop
        {
            [DllImport("local:sr/env", EntryPoint = "get-name"), WasmImportLinkage]
            internal static extern void wasmImportGetName(nint p0);

        }

        public  static unsafe string GetName()
        {
            var retArea = new uint[2];
            fixed (uint* retAreaByte0 = &retArea[0])
            {
                var ptr = (nint)retAreaByte0;
                GetNameWasmInterop.wasmImportGetName(ptr);
                return Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4)));
            }

            //TODO: free alloc handle (interopString) if exists
        }

        internal static class GreetWasmInterop
        {
            [DllImport("local:sr/env", EntryPoint = "greet"), WasmImportLinkage]
            internal static extern void wasmImportGreet(nint p0, int p1, nint p2);

        }

        public  static unsafe string Greet(string name)
        {
            IntPtr namePtr = InteropString.FromString(name, out int nameLen);
            var retArea = new uint[2];
            fixed (uint* retAreaByte0 = &retArea[0])
            {
                var ptr = (nint)retAreaByte0;
                GreetWasmInterop.wasmImportGreet(namePtr.ToInt32(), nameLen, ptr);
                return Encoding.UTF8.GetString((byte*)BitConverter.ToInt32(new Span<byte>((void*)(ptr + 0), 4)), BitConverter.ToInt32(new Span<byte>((void*)(ptr + 4), 4)));
            }

            //TODO: free alloc handle (interopString) if exists
        }

    }
}
